### ISSUE TITLE
Recommend some new feature File preview PDF DOC

### ISSUE THREAD

**Issue by PhucSD** [projectsend/projectsend#10]
I recommend that you should add File Preview feature to ProjectSend, thanks

**Comment by PhucSD** [comment]
I want it's can preview PDF, DOC and some basic types of music and video.

**Comment by ignacionelson** [comment]
How should PS handle the use of previews? Because it will allow you to view the content of a file without downloading it, this will defeat the purpose of the actions log. Should we record that the file was downloaded even if it's not true?

**Comment by savagela** [comment]
I'm just a user, but another program I use, Efile cabinet, handles  it this way:  if you click on a preview button you get a full-size readable preview.

**Comment by ilackskills** [comment]
I have done this with my images, no other previews.

**Comment by GG02Echo** [comment]
Hi there...
Sorry I am not able to see image previews in my ProjectSend platform. It is really important that my clients can preview those pix before they download them. I understand it should be possible to do so... Could you please help me to set or configure the platform to see images preview? ty in advance.,
![no-img-preview01](https://user-images.githubusercontent.com/32843972/31617768-6d6be42a-b290-11e7-9db9-4b55326c8792.png)
![no-img-preview02](https://user-images.githubusercontent.com/32843972/31617769-6d8700ac-b290-11e7-8866-30afa1a0e856.png)

**Comment by ignacionelson** [comment]
Hi @GG02Echo! Have you tried unchecking the absolute path checkbox?

**Comment by mschop** [comment]
I created a new Issue #595 as a collective issue for file previews. Because of this I close this issue.

**Comment by ignacionelson** [comment]
Added in r1265
