### ISSUE TITLE
clients cannot delete files

### ISSUE THREAD

**Issue by shoulders** [projectsend/projectsend#1009]
it would be useful for clients to be able to delete files. sometimes they upload the wrong thing. perhaps a request to admin to delete or a delete button inside the edit page of the particular file.

This functionality might be against how you want the software to run, but it is not a deal breaker.

**Comment by eletromotiva** [comment]
Hi, this is already possible.

![Screenshot_1](https://user-images.githubusercontent.com/81834105/133948494-711ffd1e-fc20-42f4-a75c-4d22abade534.png)

**Comment by shoulders** [comment]
thanks, i feel a bit dumb now 😄
