### ISSUE TITLE
Using Project Send wit 20.000 Files

### ISSUE THREAD

**Issue by eletromotiva** [projectsend/projectsend#1011]
Hey, I have a problem, with 20.000 files on server the projectsend page slow to open about 25 seconds, any solution?

**Comment by phuongdzu** [comment]
> 
> 
> Hey, I have a problem, with 20.000 files on server the projectsend page slow to open about 25 seconds, any solution?
I think put each 2000 files / 1 directory

**Comment by eletromotiva** [comment]
Projectsend do not work with multiple directorys

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by iincitr** [comment]
Any solution?
