### ISSUE TITLE
Multiple Orphan files assigment

### ISSUE THREAD

**Issue by iincitr** [projectsend/projectsend#1020]
Multiple files need to be transferred to the Upload/Files folder. But  Orphan files assignment needs to be by one by. We need to assign multiple orphan files to a client via multiple choices and the action menu.

Thank you.

**Comment by michaelvips** [comment]
I have seen this problem recently, the only way to make this is through the  data base mysql, so I inform you that there are more than 20 thousand files or software starts to work slowly.
