### ISSUE TITLE
HTTP 500 after upgrade from r1070 to r1295

### ISSUE THREAD

**Issue by timo320** [projectsend/projectsend#1026]
After following the update steps provided on the projectsend homepage, we receive a HTTP 500 after trying to log in following the update from r1070 to r1295.
**Current env information:**
- PHP 7.4.25
- MySQL 5.7.36
- Ubuntu Server 18.04

**Following steps have already been taken:**
- Installed all required PHP extensions
- Doublechecked and adjusted Access rights to root folder and files of Project Send
- Uploaded through SCP client
- Downloaded through Curl
- Tried updating from r1070 to r1270 first. Same result 

PHP is currently not outputting any logs even though log output is set to apache2/error.log and logging is enabled with E_ALL set. Sadly Im not a PHP expert and therefore am having a hard time with this update.
Help would be much appreciated! Please let me know if you need anything from my side!

**Comment by timo320** [comment]
**Short update:**
After completing steps: https://github.com/projectsend/projectsend/issues/626
The site successfully loads however file upload is not possible.

After uploading a file, progress says 100% but 0/1 file uploaded.
Have gotten PHP to also log, however it's only logging some warnings of loaded extensions it's not able to find. These extensions have been disabled in the php.ini but no change in the behaviour of ProjectSend.

**Comment by robbterr** [comment]
I had the same problem today. Updated also from r1070 to r1295.

The problem was 
```
/**
* r1115 updates
* Set nullable columns
*/
if ($last_update < 1115) {
	$statement = $dbh->query("ALTER TABLE `" . TABLE_FILES . "` CHANGE `description` `description` TEXT NULL");

	$updates_made++;
}
```

The error was something like `Invalid default value for expiry_date`.
So i changed the default date from `0000-00-00 00:00:00` to `2022-01-01 00:00:00` 

And now the DB updates are working.

BR

**Comment by timo320** [comment]
@robbterr Much appreciated!
I will try this and see if it resolves our issue.

BR

**Comment by ignacionelson** [comment]
@robbterr Thanks. Have you made this change manually, or with an update via code?

**Comment by guitoulefoux** [comment]
> I had the same problem today. Updated also from r1070 to r1295.
> 
> The problem was
> 
> ```
> /**
> * r1115 updates
> * Set nullable columns
> */
> if ($last_update < 1115) {
> 	$statement = $dbh->query("ALTER TABLE `" . TABLE_FILES . "` CHANGE `description` `description` TEXT NULL");
> 
> 	$updates_made++;
> }
> ```
> 
> The error was something like `Invalid default value for expiry_date`. So i changed the default date from `0000-00-00 00:00:00` to `2022-01-01 00:00:00`
> 
> And now the DB updates are working.
> 
> BR

I had the same error on migration from r754 to r1295
https://github.com/projectsend/projectsend/pull/1017

**Comment by timo320** [comment]
Just updated core.update.php as described in https://github.com/projectsend/projectsend/pull/1017/commits/c3dd67743e4fad5585296bcb32d50b11d63956a8

This resolved the issue for us. Many thanks to all for the support!
Special thanks to @guitoulefoux and @robbterr for giving insight to this issue and providing a fix!
