### ISSUE TITLE
Error loading and displaying Log

### ISSUE THREAD

**Issue by JoranOut** [projectsend/projectsend#103]
After using this project for 3 months, I encountered an error while trying to read the log.file. It has exceeded 2500 activities and now gets stuck in action-log.php. It just freezes and after a while my browser suggests to retry.  
I can think of a couple possible reasons:
- Somehow a memory problem occurs
- maybe the time-out occurs because its just taking too long

Testing with a log of 500 activities worked fine. The server also worked fine during the freeze, so it seems that it only freezes at this particular task. 

Does anyone else have this problem or do you know how to solve this?

thank you in advance

**Comment by crashff00** [comment]
I have also experienced this issue.

**Comment by lenamtl** [comment]
Does the solution on #86 can fix the problem?
define('FOOTABLE_PAGING_NUMBER_LOG', '50');

**Comment by FloorOut** [comment]
No, #86 is not the right answer! :-<

Checking Chrome dev tool now

**Comment by FloorOut** [comment]
It looks like a timeout of some way. See picture.
![timelineviewgoogledevtools](https://cloud.githubusercontent.com/assets/15262149/14737744/f7799c20-087d-11e6-814f-ac27e07b8f2f.jpg)

After  about 500 lines it freezes. Any suggestions please.

**Comment by lenamtl** [comment]
Maybe we can have a setting to delete old record after X day
There are a lot of lof every login logout are recorded that may be huge list after a while

**Comment by ignacionelson** [comment]
The page should load 20 or so at a time, and handle the pagination via php, and not loading all entries and paginating with javascript like it does now.

**Comment by lenamtl** [comment]
If this is a new way it's load (since PDO)  or it was loading like that?
Because if it's a new way they should try the latest version to see if they still have the problem.

**Comment by FloorOut** [comment]
Hi gays, I have send Ingnasio a new disigned action-log.php/action-log-export.php/css-file to check and impliment in this projects new version update. I am not familiar on how to do this in GitHub so leave this to the pro's. I wanted to olso attached the files to this message. But the inteface did not exeped the Zip-file!
Any suggestions?

**Comment by FloorOut** [comment]
Hi Ignasio, I have send you a new disigned action-log.php/action-log-export.php/css-file to check and impliment in this projects new version update. Did you get the new files?

**Comment by ignacionelson** [comment]
Fixed as the log does use mysql pagination
