### ISSUE TITLE
Are folders not supported?

### ISSUE THREAD

**Issue by MCKLtech** [projectsend/projectsend#1032]
I've possibly missed something but is it not possible to create folders?

We want to create a folder for clients with sub-folders within it e.g. Project which contains Scope, Drafts and Contracts, each of which contains files.

Is this not supported by ProjectSend? The only workaround I've found is Categories but it's really hard to navigate for the end-user.

**Comment by cjohnson46** [comment]
No, I don't think you've missed anything.  The file structure doesn't include folders from what I can see.  It's a bit unfortunate it doesn't because my users are having a hard time remembering to click 'All categories" then clicking "Filter".

It might help in the meantime if "All categories" was named "Folders" and it also directed them to that "Folder" after selecting.  I still think a folder structure would be easier for end users.

**Comment by ignacionelson** [comment]
@MCKLtech indeed as @cjohnson46 said, there are no folders right now. I've tried to work on this but didn't get far.
Another option I've been thinking about would be to have a template that handles categories as folder. It would be a  dirty workaround, but might help in cases like yours.

**Comment by Philippe-M** [comment]
Unfortunately the management of files is requested regularly for several versions and for the moment there has been no advance on the subject. I could use ProjectSend for several projects but without this function I have to switch to Nextcloud :(

A long time ago I had made a patch to be able to manage them but it was not integrated and I did not follow the evolutions.

**Comment by Philippe-M** [comment]
Just an idea: directories don't have to be physical, they can be virtual. ;)

**Comment by ignacionelson** [comment]
@Philippe-M Indeed! That's the way I've tried to implement this (the table on the database is there, tbl_folders), but the issue is that the whole UI for managing files needs to be different and it's a task hard to tackle

**Comment by MCKLtech** [comment]
Being transparent, we went ahead and built a custom solution on Tailwind and Laravel to solve this issue. ProjectSend is amazing but it really needs to support folders to be a viable solution for non-technical end-users.
