### ISSUE TITLE
ProjectSend r1330 throws SQLSTATE[42S22] error while adding client

### ISSUE THREAD

**Issue by prbt2016** [projectsend/projectsend#1034]
Hello,

I was in the process of manual installation of ProjectSend version r1330 downloaded from official website i.e : 

https://www.projectsend.org/download/409/ on PHP 7.1, MYSQL 5.5, Apache 2.2. 

However post successful installation I encountered an issue while adding client from admin panel : 

i.e Clients -> Add new and then I enter client details and click on Add client, blank page is shown. 

So to debug further I enabled debug in /includes/app.php by setting define('DEBUG', true); , the following error is thrown : 

```

Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'can_upload_public' in 'field list' in /{{PATH}}/{{TO}}/{{PROJECTSEND}}/includes/database.php:25 Stack trace: #0 /{{PATH}}/{{TO}}/{{PROJECTSEND}}/includes/database.php(25): PDO->prepare('INSERT INTO tbl...') #1 /{{PATH}}/{{TO}}/{{PROJECTSEND}}/includes/Classes/Users.php(420): PDOEx->prepare('INSERT INTO tbl...') #2 /{{PATH}}/{{TO}}/{{PROJECTSEND}}/clients-add.php(60): ProjectSend\Classes\Users->create() #3 {main} thrown in /{{PATH}}/{{TO}}/{{PROJECTSEND}}/includes/database.php on line 25

```

Could you please try to replicate this at your end?.

Awaiting your reply.

**Comment by uruk-hai-21** [comment]
Same for me
PHP 7.2/7.3/7.4

**Comment by kkplein** [comment]
Interesting. I just tried adding a new client on our (upgraded) r1330, and it worked fine: "Client created successfully."

**Comment by ignacionelson** [comment]
@prbt2016 Thanks for your report. This happened on a new installation instead of upgrading, right?

**Comment by ignacionelson** [comment]
@prbt2016 It was an issue with new installations. Please download again, I've replaced the file with the correct one

**Comment by prbt2016** [comment]
Hello @ignacionelson ,

Thanks for looking into the issue and fixing it  . Shall check it out .

Regards.
