### ISSUE TITLE
Cannot login after IP address change

### ISSUE THREAD

**Issue by jjmacneil** [projectsend/projectsend#1035]
I had to change the IP address on the Ubuntu VM and now can’t login to ProjectSend. It appears to be looking for the old IP address according to the unable to connect message which displays the old IP address.

Is there a way to update the IP address or URL outside the GUI not sure if the info is in the database itself or within a PHP config file.

**Comment by ignacionelson** [comment]
Hi! Check includes/sys.config.php
The IP might be used there as the database host

**Comment by jjmacneil** [comment]
Thank you. I was able to get back into the site, but when changing the URL under options to what I want like portal.example.com/projectsend/ I get an error message stating the URL doesn’t exist on the Apache2 server. If I replace the portal.example.com with the IP address of the server it works correctly.

How can configure custom URL as mentioned above without reinstalling ProjectSend again?

   -Josh

**Comment by ignacionelson** [comment]
Sorry for the delay. You need to manually change the base_url row in the settings table, that will fix the issue.
