### ISSUE TITLE
https://www.projectsend.org/download/409/ gives a 500 error. Can't download projectsend r1330

### ISSUE THREAD

**Issue by xzenor** [projectsend/projectsend#1036]
**Internal Server Error**

The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at webmaster@projectsend.org to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by ignacionelson** [comment]
Fixed it, thanks for letting me know!

**Comment by xzenor** [comment]
You're welcome. Thanks for fixing it and have a nice weekend.
