### ISSUE TITLE
Update caused a couple of Errors so far

### ISSUE THREAD

**Issue by sjgarth** [projectsend/projectsend#1037]
Hi,
Updated to R1330, replaced all files as instructed. Database reported as updated.
Using PHP7.4 (PHP8.0 causes system crash completely)
Using MySQL 5.7.36

**ERROR 1**
Click on manage files results in;
Warning: shell_exec() has been disabled for security reasons in /home/xxxxx/cftp/includes/functions.php on line 1046
With files displayed below about 38 of the above error line.

**ERROR 2**
In Manage Clients, and Manage Groups, everything is listed, however if I click to sort by any column, I get;
Not Found
The requested URL was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**ERROR 3**
Files cannot be downloaded due to a number of warnings stating 'Warning: Cannot modify header information - headers already sent by...' the n random characters.

**Comment by kkplein** [comment]
I just tried the three errors here in our 1330, but they all work here. (updated install as well)

**Comment by skipper0922** [comment]
Hi, 

I also updated platform to R1130. 
Regarding the above( ERROR 1), I found a solution, the hosting provider activated some options in php (extensions). Now I don't get those warning errors, but all the files I download are corrupt, the word ones can't be opened (error unreadable content) and the pdfs have some erroneous characters, which I've never seen before, practically a destroyed document.
If I try to open the documents, downloading them from the ftp / upload folder, there is no problem, are readable, everything is fine..
I mention that I did not make any changes to the download method settings, I still use php. The php version is 7.4

**Comment by oecruz** [comment]
Files corrupted here too. Videos about 1Gb arent readable after dowloading them. Version is 1330.

**Comment by sjgarth** [comment]
My hosting company has shell_exec turned off, and will not turn it back on for security reasons, and it has been turned off for a number of years.
So I had a look at my previous version of Project send (v1295) and, as far as I can tell, v1295 has shell_exec command on line 1009 and others.
Therefore it was never called in previous versions, but is in this version.
Why?

**Comment by ignacionelson** [comment]
I've just pushed a commit to check if shell_exec is enabled before trying to use it to get the file size. Since this and other issues like this one has been appearing over the last few days, I'll try to fix as many as I can this week and get a new version out.

**Comment by ignacionelson** [comment]
If anyone can test by replacing includes/functions.php with the one here I'd really appreciate it!

https://github.com/projectsend/projectsend/blob/develop/includes/functions.php

or raw

https://raw.githubusercontent.com/projectsend/projectsend/develop/includes/functions.php

**Comment by oecruz** [comment]
@ignacionelson I reset the server, and start fresh again. I did the update to 1330 and all went wrong with the files dont being readable after download.

Now that I did a clean install, I got no UI... I did install the PHP that you linked here, but as I have no UI im unable to test if that works.

The log in gives me this thou:

Notice: Undefined index: type in /home/user/site.com/includes/functions.php on line 1320

Notice: Undefined index: type in /home/user/site.com/includes/functions.php on line 1323

Notice: Undefined variable: replace in /home/user/site.com/includes/functions.php on line 1327

**Comment by ignacionelson** [comment]
@oecruz I'm a little lost here. Those notices refer to the branding logo which are definitely not stopping the page from loading. 
Did you manage to finish the web install when you set a site name and a base user?

**Comment by oecruz** [comment]
HI @ignacionelson I used the modification of sys.config.php to link the previous DB, and the software did ended the installation process, but, as I told you... one screen showed me those notices, but I had no UI... like, no style, so I cant use it like that.

I did erased all and went for the last old version (1295) which is working. I saw that the newer version is 1335 (not 1330) so I might try that one once I had the 1295 working again and keeping post here if something goes bad... also, when its working I´ll let you know for sure.

**Comment by skipper0922** [comment]
Same issue here, files not readable. Error, undefined characters.

**Comment by oecruz** [comment]
@ignacionelson I just tested v1335 and it works great. I lose all the files relations to the data base (i guess because of the update mixed with something that I did wrong), but that isnt important. What matters, is that Im able to upload and download files again, and the user in the DB were not lost. 

So far, I tested with 1GB files. Now im testing with 3GB files. So far, everything is good compared to v1330.

**Comment by kkplein** [comment]
Lost all relations between users and their files? That would have been an absolute disaster in our case...! Luckily not for you!

**Comment by oecruz** [comment]
> Lost all relations between users and their files? That would have been an absolute disaster in our case...! Luckily not for you!

@kkplein the relations from the files to the data base, also between the clients and files. Its not that much of a problem, because we deliver the files just once, they download and done. Im mostly sure that I did not do something proper. As long as its working again, that really good.

**Comment by ignacionelson** [comment]
@oecruz While I'm really glad that the files are downloading fine, I'm not really sure what might have broken the files relations. Have you checked the database directly? Is the relations table empty?

**Comment by oecruz** [comment]
> @oecruz While I'm really glad that the files are downloading fine, I'm not really sure what might have broken the files relations. Have you checked the database directly? Is the relations table empty?

It was a mistake from our behalf. I just check it.

There are two folders with "file" name in it. "My_Files", in the root, and "Files" in Upload folder. What happened, was that we used "My_Files" for saving that info, not the other one, that was the correct one. But again, zero problem with that, because we didnt need those files anymore. Now I have another good question... but I guess is better to open a new issue for that, its related to the lenght of the files (in case of videos).

UPDATE: We were able to recover all the files from a backup, of the files and the DB.

**Comment by sjgarth** [comment]
Hi,
Original poster here.
Sorry for the late response, I have been a little unwell.
I have just updated using R1335 and it went so smoothly it was like a dream.
Tested all functions I could think of and all worked as expected.
Excellent product, easy update, thank you for your work.

**Comment by ignacionelson** [comment]
Thank you for your comments and I hope you are feeling better!
