### ISSUE TITLE
Fatal error with PHP 8

### ISSUE THREAD

**Issue by cseoneohs** [projectsend/projectsend#1038]
Hi,
I have a problem with PHP 8 only, sometimes a fatal error :
Fatal error: Declaration of PDOEx::query($query, $options = []) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) in /./././projectSend/includes/database.php on line 18

More informations :

Version  r1330 
Default upload max. size  2048 mb.

Server Apache 

Memory limit    -1
Max execution time   14400
Post max size   64M

 mysql Version  5.5.60-0+deb7u1-log

**Comment by ignacionelson** [comment]
Fixed on r1335, thanks!
