### ISSUE TITLE
Auto expiring on account implemented - any interrest?

### ISSUE THREAD

**Issue by ghost** [projectsend/projectsend#104]
Hi folks,

We have added an "expiring date" to the account-settings. Together with some extra information-fields only for admin to edit. Next step is to 'uncheck' the account-can-login-field after this date while account attempts to log-in.

Any interest from you all for this info?

**Comment by lenamtl** [comment]
+1

**Comment by FloorOut** [comment]
Hi, we use this feature as an option in a membership environment: default is blank; if not set endless entry; if set "di". This is a more general option only shown when level 7,8,9 add/edit userspecs. Fields don't show on users-edit. It is very transparent and can be an useful enhancement.

**Comment by FloorOut** [comment]
@lenamtl or @ignacionelson 
I am new to GitHub and need directions to shareupload edited code for you to migrate in the official code. Please contact off-topic, thx!

**Comment by lenamtl** [comment]
Make sure you add and test your custom code on the latest version r583.
https://help.github.com/articles/creating-a-pull-request/
Thanks

**Comment by FloorOut** [comment]
Sorry,  a newbee question, can I find version 583 in the "master repository"?

**Comment by lenamtl** [comment]
Just click on zip download button

**Comment by FloorOut** [comment]
Ths, find out already, Putting code right now and start testing. When i am ready testing i wil contact you again!

**Comment by ignacionelson** [comment]
Closed due to inactivity
