### ISSUE TITLE
Title TAG instead file name

### ISSUE THREAD

**Issue by deklica** [projectsend/projectsend#1052]
In old versions of ProjectSend, %FILES% tag write in the email the text we put for the file (Title), but now that tag writes real names of files in email... Is this a bug or feature, I think that is a bad change...
Is it possible that tag to use Title instead of original filename, or somehow to add an option to use another tag, for example, %TITLES% to use instead of or mix with them?

This is an example from the mail, how is displayed now, original filename:
Milo Juric doc5255423.rar
But need like this, as in the title:
dr Milo Juric document for the exam, part 1

**Comment by deklica** [comment]
To answer to myself:
If you need this fix, edit "upload-send-notifications.php" file in "includes" folder...
Just edit this line:
`'filename'		=> $file->filename_original,`
to
`'filename'		=> $file->title,`

or you can use both, just to add line:
`'title'			=> $file->title,`

add later in certain places, wherever you search "file_name":
`'title' => $file_data[$use_id]['title'],` 2 times
and, for example change line to
`$files_list.= '<p style="font-weight:bold; margin:0 0 5px 0; font-size:14px;">'.$mail_file['title'].'&nbsp;&nbsp;('.$mail_file['file_name'].')</p>';` 2 times

That's it, unless the developer leaves the option easier to enter ...

**Comment by ignacionelson** [comment]
I've pushed a commit with your solution applied and of course credited you for it. Thank you!

**Comment by deklica** [comment]
> I've pushed a commit with your solution applied and of course credited you for it. Thank you!

Thanks Ignacio...
You made a small mistake, so correct it if it's not a problem, I commented in the commit ...
