### ISSUE TITLE
Feature request: timestamps (not just dates) in the activities log

### ISSUE THREAD

**Issue by xzenor** [projectsend/projectsend#1053]
Maybe it's just me but I think it's really annoying that the actions log only shows dates and no times.  
If I want to remove a file but it's downloaded today, can I? If it's hours ago, then yes. if it's 2 minutes ago then the download is probably still busy so I shouldn't remove it but i don't know that because all i see is a date.
Just my frustration.. If I'm the only one experiencing this, don't bother ;)

**Comment by ignacionelson** [comment]
Hi!
The timestamp uses the global setting for dates and time. I should force the time there, it's a good idea. But if you go to the options page you can change the date format to show the time everywhere, including the log.

**Comment by ignacionelson** [comment]
On the general options add to the Time format box `h:i:s` (with a space before)

**Comment by xzenor** [comment]
aaaw man.. you have got to be kidding me..
Please tell me this was added in the latest version?

**Comment by ignacionelson** [comment]
If it makes you feel better, yes, it's new! Don't read the following sentence.




It's been there since the beginning :)

**Comment by ignacionelson** [comment]
I guess it's another example of why documentation is really important. Sadly I haven't been able to make a site for that yet.

Please let me know if you need help with the settings

**Comment by xzenor** [comment]
Nah, I'm good otherwise.. I'm gonna close this issue as it's not an issue.... Not on the program's end anyway.. My reading however could use some patching
