### ISSUE TITLE
Unable to upload files

### ISSUE THREAD

**Issue by rexdivakar** [projectsend/projectsend#1055]
Warning: The following directories do not exist or have write permissions errors.

File uploading or other important functions might not work.

/app/projectsend/upload/admin

/app/projectsend/upload/files

/app/projectsend/upload/thumbnails

/app/projectsend/upload/temp

![image](https://user-images.githubusercontent.com/15235122/147561098-3f5e3b3a-d90c-4935-a40b-1e33a2c15b16.png)

**Comment by ignacionelson** [comment]
Hi! Try creating those directories and give them 775 permissions. Your server configuration does not allow PS the do that for you.

**Comment by rexdivakar** [comment]
thanks got it working after changing my PUID
