### ISSUE TITLE
Column Sort Not Working

### ISSUE THREAD

**Issue by sjgarth** [projectsend/projectsend#1059]
Hi,
Using;
PHP 7.4
MYSQL 5.7.36
Projectsend v r1335

Column Sort in Manage Clients, Manage Files, Manage Client Groups and Manage System Users fails. All columns with a sort ability give same error.
All give error;
```
Not Found
The requested URL was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by ignacionelson** [comment]
Is there any difference in your url vs this one?

https://www.yoursite.com/clients.php?orderby=email&order=desc

I cannot reproduce this error

**Comment by sjgarth** [comment]
https://www.mywebsite.com/cftp/cftp/clients.php?orderby=name&order=desc

I have just noticed the extra cftp, it is not in two folders and should be https://www.mywebsite.com/cftp/clients.php?orderby=name&order=desc

**Comment by sjgarth** [comment]
system uri in option is set to https://www.mywebsite.com/cftp/

**Comment by sjgarth** [comment]
If I remove the extra cftp the command works.
So where is that being added?

**Comment by ignacionelson** [comment]
Thanks! The problem could be on 
includes/Classes/TableGenerate.php
line 66 uses the data from line 33 ($_SERVER['REQUEST_URI']), which in this case also returns the directory in which PS resides.
Maybe replacing
`$build_url = BASE_URI . substr( $url_parse['path'], 1 ) . '?' . $query;`
will solve the issue. Let me run a test and comment again.

**Comment by ignacionelson** [comment]
Here's the fix

https://github.com/projectsend/projectsend/commit/56fb0bd3e774854051f92524b1831d1d04ee936c

Hope that helps!

**Comment by sjgarth** [comment]
That seems to have done the job, thanks.
Excellent response as usual, I wish I had your skills.
Its 0030 here, so good night.
