### ISSUE TITLE
Suggestion: create a new role: "client manager"

### ISSUE THREAD

**Issue by andrei-caba** [projectsend/projectsend#1069]
Hi

I am a software&hardware architect. I also helped translating a version of this software into Romanian (planning to help future versions too :) 👍 ).
I believe the following suggestion might be of great use to this project.

  Usually - non-profit or any other Company/Government organisation - clients have a single contact and their communication (including sending and receiving of documents/files) goes through that specific person.
So... if there can be a way to assign a "Client Manager" clients to manage ("manager access" to the user's files, password, email and a possibility to notify only the specific manager of each client of "new documents" or just updates) - it would be just great.
Sometime you might have 2 people managing the same client (like a "technical" manager of that specific client, managing from a technical perspective and a financial manager, managing from a financial perspective that specific client).
And, of course, the high "managers" - the departament chiefs and so on, who will have access to the larger group of clients (all the clients that are managed by their very subordinates).
This could add such a great value to this application!... :)
So... what do you people think of this?... :)

Have a wonderful time and thanks for this open project! 👍 
A. Caba

**Comment by iincitr** [comment]
Hi
This idea is very good and easy to use for large number of clients and
users.

Thank you for your suggestion.

24 Şub 2022 Per, saat 20:12 tarihinde andrei-caba ***@***.***>
şunu yazdı:

**Comment by andrei-caba** [comment]
of course, each client manager has to have access only to his own clients - not to all the other clients. So... each "group of clients" that is managed by one or more client manager(s) is separated in it's permissions by other group of clients - meaning that other "client managers" that were not assigned to this group (or this "group of groups"/"labels of groups")  would not have access to it.

**Comment by ignacionelson** [comment]
Sorry, still haven't had time to look deeply into this. Hope at least the feature to limit users to certain clients come in handy!
51e0d74

**Comment by andrei-caba** [comment]
maybe a first step towards this would be implementing „groups” of ”groups”
- where the many to many relation would easily then solve the problem of
assigning permissions by those „groups of groups” later :) ...

**Comment by ignacionelson** [comment]
Uploaders can now be assigned to specific clients. I believe this somehow covers the request. Hope it helps!
