### ISSUE TITLE
Future Request :EXPIRATION DATE bulk edit

### ISSUE THREAD

**Issue by iincitr** [projectsend/projectsend#1072]
While uploading or assigning the files ( 30+ files on the single process) there are options about  "Add All" "Remove All"  " Copy sections to other files "  on ASSIGNATIONS, CATEGORIES AND Groups.

_We need also EXPIRATION DATE :   "Add All" "Remove All"  " Copy sections to other files "_

Today we have 13 000 ( 13 thousand ) files and need auto expiration with date.

Thank you.

**Comment by iincitr** [comment]
> While uploading or assigning the files ( 30+ files on the single process) there are options about  "Add All" "Remove All"  " Copy sections to other files "  on ASSIGNATIONS, CATEGORIES AND Groups.
> 
> 
> 
> _We need also EXPIRATION DATE :   "Add All" "Remove All"  " Copy sections to other files "_
> 
> 
> 
> Today we have 13 000 ( 13 thousand ) files and need auto expiration with date.
> 
> 
> 
> Thank you.

**Comment by ignacionelson** [comment]
Hi! I'll try adding this soon. But in your case, for 13000 files, I believe your best bet is to update them with a custom script, either php or directly in the database. Manually editing that amount of files seems like a huge task!

**Comment by iincitr** [comment]
Thank you for your work and response.
If you add this future I will use from that date which is updated the code
by you.

So nowadays we are deleting files by choosing date sorting and selecting by
hand.
If we can set  Expiration Date as bulk like other properties ( customer
assignment for example) will be much better and Autodelete then works for
us.

[image: image.png]

Best regards

**Comment by ignacionelson** [comment]
Done on 629b2a6970e07792a21bb12bba2478ee39594ee1
If you want to use it right away, you need to compile the assets with gulp. Or I can email you a ready-to-use version if you want.

**Comment by iincitr** [comment]
Thank you
Pls send e-mail
31 May 2022 Sal, saat 01:24 tarihinde Ignacio Nelson <
***@***.***> şunu yazdı:

**Comment by ignacionelson** [comment]
Done, download from here
https://projectsend.org/direct-download/projectsend-r1424.zip

**Comment by iincitr** [comment]
Hi,
Please check the image 

Apply to other files not working  

[img]https://live.staticflickr.com/65535/52219764891_2bd56eec00_o.png[/img]
