### ISSUE TITLE
Request for Apache 2.0 License

### ISSUE THREAD

**Issue by brad061746** [projectsend/projectsend#1074]
Hi all, 

My name is Dongen Bradley Zhou, and I'm the CEO of Insulator Bio, a newly formed Start-Up in the Bio-Semiconductor industry. As you may have noticed, my team and I have been contributing to the Chinese Language versions, and we at Insulator Bio have loved this project. 

Upon consideration, we want to keep developing on this project and add additional blockchain audition and various security features, and most importantly, we want to promote, advertise, and commercialize our version of the project as corporate SaaS to our existing customers (100% Mainland China Market). Since my legal and R&D noticed that Project Send is currently on a  GNU GPL-2.0 license, I'd like to formally request an Apache 2.0 License issued for Insulator Bio. In exchange, we will pick up your patronage tab and donate accordingly based on our sales performance audited quarterly. Additionally, we are willing to open-source our code based on a peer-request basis (from the project-send team, no problem; but not to our competitors).

Please let us know if this is even possible.  I can be reached by simply replying to this post, or by email: ceo@insulatorbio.com

Sincerely, 

D.B.ZHOU 

*Insulator's Official Site has changed to https://insulatorbio.com.cn

**Comment by ignacionelson** [comment]
Hello Mr. Zhou. First of all, a huge thank you for your words and contributions to the translations.

I'm really glad ProjectSend is helping your startup in their path.

I would love to grant you the license you need, just please tell me what you need from me for this (an email, a comment here, or something elase?)

About code contributions, any security fixes or additions that you feel might help the general public of PS will be appreciated.

Regarding donations, I do have a Patreon set up for recurring amounts, and a PayPal account for one time or special, sporadic donations.

Thank you again!

**Comment by brad061746** [comment]
> Hello Mr. Zhou. First of all, a huge thank you for your words and contributions to the translations.
> 
> I'm really glad ProjectSend is helping your startup in their path.
> 
> I would love to grant you the license you need, just please tell me what you need from me for this (an email, a comment here, or something elase?)
> 
> About code contributions, any security fixes or additions that you feel might help the general public of PS will be appreciated.
> 
> Regarding donations, I do have a Patreon set up for recurring amounts, and a PayPal account for one time or special, sporadic donations.
> 
> Thank you again!

Hi Mr. Nelson, 

Thank you for your quick reply! I apologize for my delayed response due to the current Covid restrictions implemented in Shanghai.  After consulting with our legal team, here's the do list:

1. Please Email me (ceo[at]insulatorbio[dot]com, from a projectsend email address) AND comment on this post, that the Team Project Send has agreed to permit the team at Insulator Bio to use the entire project under Apache 2.0 license.
 
2. Acknowledge and allow the team at Insulator Bio to further develop and may obtain any Intellectual Property that includes partial or in-whole of Project Send's work, by BOTH email AND comment on this post. (You can simply say "agreed")

3. Regarding the above-mentioned security fixes, my Chief Infrastructure Officer (cio[at]insulatorbio[dot]com) will contact and post any general issues that we have found under Github's "ISSUES" tab. For any significant findings and critical issues, we'll contact and send our findings first to your provided emails(and other collaborators too) instead of posting them publically. 

4. Since we are currently a startup with limited resources, we'd like to choose mainly the sporadic route. Our fiscals start the same as a calendar year and end 12/31. We publish our 3-rd party audited financial reports quarterly on a per request basis. For Project Send, we currently plan on a Q3 2022 release and we'll send you any info at the beginning of Q4 2022. We'll contribute our first donations accordingly near the date around October 10th, 2022.  


Sincerely, 

D.B. Zhou

**Comment by ignacionelson** [comment]
I'm sorry but the mentioned conditions exceed what the license entitles. Thank you for understanding.
