### ISSUE TITLE
Database installation was successful, but errors were encountered

### ISSUE THREAD

**Issue by exequielbazan03** [projectsend/projectsend#1075]
Hi guys,
I'm trying to install project send on a subdomain and I get the error "Database installation was successful, but errors were encountered"

I really don't know what is happening.

Could you help me?

**Comment by michaelkrieger** [comment]
This is a bug.

install.php has
```
  $other_errors[] = update_chmod_emails();
  $other_errors[] = chmod_main_files();
```
and each of those functions returns null to indicate success (or no errors encountered).  So other_errors, even without errors, is an array with two null values and thus triggers that message. Tested on PHP 8.1 and PHP 7.4.

Test case:
```
<?php
$other_errors = array();
$other_errors[] = NULL;
$other_errors[] = NULL;
if (false || false || $other_errors) {
        var_dump($other_errors);
        echo "There was an error\n";
}
```

Running that results in 
```
$ php ./testcase.php 
array(2) {
  [0]=>
  NULL
  [1]=>
  NULL
}
There was an error
```

This should (1) be testing for a non-null value, or (2) should not be packing null values onto the array, or (3) should be removing null values from the array.

The error can be ignored, but it shouldn't be there in the first place.  Will make a PR to fix it.

**Comment by GanimanSwift** [comment]
I get this error after installing, and then the login page seems to crash before loading the login box. I don't see anything in error logs. All required php modules are installed and enabled.
