### ISSUE TITLE
where Projectsend store the settings? 

### ISSUE THREAD

**Issue by wiebereu** [projectsend/projectsend#1076]
I want to know where Projectsend store the settings so that i can replace those files in case i lost all my settings? 
I don't know what is the cause of this but sometimes i lost all my settings and have to start all over again, for first login user. 
I now made some changes in projectsend and configure email. I don't want to all of this all over again. 
Can someone tell me which files i need to backup in order to safe my settings?

**Comment by rob4226** [comment]
I was wondering this also. Besides the few settings in `includes/sys.config.php` I believe the rest of the settings are stored in the database, in the `tbl_options` table.  To back up all databases for you MySQL/MariaDB server:
```sh
# Backup all databases to file
mysqldump -u root -p --all-databases > all-databases.sql
# Restore All Databases
mysql -u root -p < all-databases.sql
```

**Comment by wiebereu** [comment]
> 

I still haven't find any solution to this and in the meantime i have to regularly apply the same settings over and over again cause for unknown reasons i am losing my settings  at least every two weeks. To prevent this i want to make a copy of the settings so that i can restore it if i lose it.

**Comment by ignacionelson** [comment]
@wiebereu This sounds like a specific issue with your server. Are you using a shared hosting account?
Settings are indeed in the options table
