### ISSUE TITLE
Public Download / Popup to copy link to clipboard is missing

### ISSUE THREAD

**Issue by protego-it** [projectsend/projectsend#1085]
Hi Ignacio,
after the latest upgrade a core function is gone for me.
What happened to Public Downloads for system users?
I'm only working with system users, no guests or other groups.

The users uploaded their files and there was a checkbox for public download.
This checkbox is missing now. When you've clicked on the button "Public", a small popup appeared and copied the file link to the clipboard.
![projectsendmissing](https://user-images.githubusercontent.com/59828196/161960323-e507794c-a0ea-42f0-a162-f14194267c32.png)

I don't need a checkbox for public downloads, but I need the popup for users to get the link copied to clipboard.
How can I bring this function back? When I click on a uploaded file, it starts downloading immediately. There is no option to copy the link.
Thank you. 

\includes\forms\file-editor.php has set public downloads to 0. I changed this to 7 and the checkbox reappeared, but the popup to copy the link is still missing.

**Comment by ignacionelson** [comment]
I'll check and write back

**Comment by ignacionelson** [comment]
I'm not having luck reproducing this issue. I've tried changing all possible related options and the Uploader user I have is still seeing the button.
Are you missing this entire column or just the button?

![public](https://user-images.githubusercontent.com/6926562/161994476-98815556-3c69-4f43-b28f-9af642a8cdd2.png)

**Comment by protego-it** [comment]
Hi Ignacio,
thanks for the fast reply.
This is how it looks when I upload as a system user. On my admin account everything is fine.
![projectsendmissing2](https://user-images.githubusercontent.com/59828196/161997812-23e20281-a5b5-4f7f-8675-bd6a796a0f44.png)
.

**Comment by ignacionelson** [comment]
Please check r1605, I believe this is fixed
