### ISSUE TITLE
Sort By not working after upgrade 1335

### ISSUE THREAD

**Issue by thameerakn** [projectsend/projectsend#1092]
After upgrade to R1335 sort by function not work for every menu, Seems URL adds additional directory path. 

example : 

URL : www.urlto.com/share
Sort URL : www.urlto.com/share/share/clients.php?orderby=name&order=desc

**Comment by thameerakn** [comment]
Hi,

I think it's the issue in "TableGenerate.php", Line 66-67. Since BASE_URL include folder name, " substr($url_parse['path'],1) " will add extra folder. 

$build_url = BASE_URI . substr($url_parse['path'],1) . '?' . $query;

Thanks

**Comment by ignacionelson** [comment]
Fixed in r1415
Thanks
