### ISSUE TITLE
ProjectSend r1415 Installation issue

### ISSUE THREAD

**Issue by prbt2016** [projectsend/projectsend#1094]
Hello @ignacionelson ,

I was in the process of manual installation of ProjectSend r1415 downloaded from here : https://www.projectsend.org/download/432/ 
on CentOS Linux release 7.9.2009 (Core) with PHP 7.1.33, MYSQL 5.5, Apache 2.2.34.

However I encountered with an issue i.e : 

After entering database details , URL details and admin details and clicking on 'Submit' throws the following : 

`Warning: Cannot modify header information - headers already sent by (output started at /{{PATH}}/{{TO}}/{{PROJECTSEND}}/header-unlogged.php:67) in /{{PATH}}/{{TO}}/{{PROJECTSEND}}/install/index.php on line 180
`

Following is the screenshot of the same : 

![test](https://user-images.githubusercontent.com/17871448/170651794-e82797d7-b213-42a2-9a86-1af4b53c7991.png)

Could you please replicate the issue at your end and fix this ?.

**Comment by ignacionelson** [comment]
Sorry, i wasn't able to reproduce the error.
Line 180 is a redirect after a successful install. What happens if you navigate to your root url again? Are you redirected to the installer still?

**Comment by prbt2016** [comment]
Hello @ignacionelson ,

> Line 180 is a redirect after a successful install. What happens if you navigate to your root url again?

Login page is shown correctly.

Was able to successfully install r1420 without the above issue.
You can close the issue.

**Comment by ignacionelson** [comment]
Glad it worked! Thanks for letting me know
