### ISSUE TITLE
unable upload large files 1MB files 

### ISSUE THREAD

**Issue by karthikeyan951213** [projectsend/projectsend#1095]
Dear Team

i tried uploading a zip/rar archive, the size is around 300mb.
When i click in upload the file the upload stops before the process is finished (stops around 1%).
When the upload failed i get this screen

![image](https://user-images.githubusercontent.com/104340226/170672741-472bd2c0-b460-473f-bc75-ddd000255970.png)
![image](https://user-images.githubusercontent.com/104340226/170673151-137b6747-4f4b-4c83-bcf1-ef3fce3e2973.png)

and i am using php 7.4 , apache 2.7 ,project send r1295

Note : If you need any other details i will share you , please share to solution.

**Comment by ignacionelson** [comment]
Hi!
Try adding

`@ini_set( 'upload_max_size' , '256M' );
@ini_set( 'post_max_size', '256M');
@ini_set( 'max_execution_time', '300' );`

to includes/sys.config.php to see if that helps.
Is this a shared hosting account? You might not have permission to edit php settings like this, or at all depending on your service.

**Comment by markknit** [comment]
I spent a lot of time debugging the same issue before I found this fix. It worked. Why isn't it in the base shipment?

**Comment by ignacionelson** [comment]
I don't believe it's good practice to force php settings as default for every installation.
Added to README file for other users with the same issue!
