### ISSUE TITLE
Delete file not working

### ISSUE THREAD

**Issue by 4allprograms** [projectsend/projectsend#1096]
Hello, I cannot be able to process delete file! how to fix this issue?

**Comment by ignacionelson** [comment]
Sorry, fixed on 6aa70ddb4c5686b3a7443982a97be2be489b11af
Will upload a new version today

**Comment by 4allprograms** [comment]
Thank you! It's working right now

**Comment by ignacionelson** [comment]
Great! Just uploaded r1420 with the fix!
