### ISSUE TITLE
Latest tag

### ISSUE THREAD

**Issue by aptalca** [projectsend/projectsend#1097]
Hi, the latest tag for the release is `Stable` instead of the version number: https://github.com/projectsend/projectsend/tags

Can that be fixed? It breaks all ci operations downstream.

Thanks

**Comment by ignacionelson** [comment]
Done, hope that helps!

**Comment by aptalca** [comment]
Thanks so much

**Comment by aptalca** [comment]
@ignacionelson sorry to bother again, but the latest release is also missing the release artifact, the zip file.

**Comment by ignacionelson** [comment]
Done, sorry!

**Comment by aptalca** [comment]
All good now. Thanks so much.
