### ISSUE TITLE
Possibility to assign customer groups to a file category

### ISSUE THREAD

**Issue by boexler** [projectsend/projectsend#1099]
I have two software packages. A `client` and a `server` variant.

**CompanyA:**
- Max Mustermann
- John Doe

**CompanyB:**
- Ronald Foo

**CompanyA** has bought the `server` variant and is to receive access for it. **CompanyB** not.

My current solution looks like this:

`server application` is in the customer group `ServerApp`
`client application` is in the customer group `ClientApp`

The following members belong to the customer group `ServerApp`:
- Max Mustermann
- John Doe

The following members belong to the customer group `ClientApp`:
- Max Mustermann
- John Doe
- Ronald Foo

If **CompanyA** now gets a new employee, I have to remember to assign them to both groups as well.

---

I think it would make more sense if I could create a file category `ServerAppCategory` and `ClientAppCategory` and assign the customer groups `CompanyA` and `CompanyB` to them. Each new employee would thus automatically have access to the relevant files. Another benefit would be adding a new company. **CompanyC** with 3 employees would now have to be created first and then all 3 employees of the `client application` and optional `server application` must be added manually. It would be much easier if I could just add the customer group `CompanyC` to the two file categories.

**Comment by ignacionelson** [comment]
I believe that shareable folders would be a best way to solve this without modifying the existing workflow. Currently working on that feature!
