### ISSUE TITLE
Not showing /manage-files.php tables

### ISSUE THREAD

**Issue by Audrius444** [projectsend/projectsend#1101]
Hi,
suddenly stop showing /manage-files.php tables.

How fix it?

![file](https://user-images.githubusercontent.com/47668093/171380764-42a5b8ba-ddb7-40f9-8045-4b8e6ae5fd54.PNG)

**Comment by ignacionelson** [comment]
Please enable debug mode by editing includes/app.php, changing
define('DEBUG', false);
to
define('DEBUG', true);

You should see the error messages instead of an empty screen

**Comment by Audrius444** [comment]
![paveikslas](https://user-images.githubusercontent.com/47668093/171570485-cb9a115e-bc73-4528-bff1-26f7fc0f48ef.png)


> Please enable debug mode by editing includes/app.php, changing define('DEBUG', false); to define('DEBUG', true);
> 
> You should see the error messages instead of an empty screen

**Comment by ignacionelson** [comment]
Looks like you are running out of RAM. How to increase it (if possible at all) will depend on your hosting provider. Which service are you using?

**Comment by ignacionelson** [comment]
I see that you are on Windows. Is this a local instance? 
Try the accepted answer here
https://stackoverflow.com/questions/37936399/increase-memory-limit-on-wamp

**Comment by Audrius444** [comment]
Yes, windows. I try change memory_limit = 128M to memory_limit = 1028M
Buw not working. Memory size in error change.

![paveikslas](https://user-images.githubusercontent.com/47668093/171797241-801e7232-b2b8-4afc-b1f8-458d529eec00.png)

**Comment by Wiblishauser** [comment]
I'm having the same issue but with a different error message. Though I see that there is common ground with the sanitizer.php.

Thanks in advance

![image](https://user-images.githubusercontent.com/77394457/186760479-d9a45130-a3f6-459b-8166-6404805c75a2.png)

**Comment by ignacionelson** [comment]
Looks like the sanitizer is using too much RAM.
Have you found the specific svg file causing this issue?
