### ISSUE TITLE
Version r1420 Statistics graph and ProjectSend news won't load

### ISSUE THREAD

**Issue by JustBru00** [projectsend/projectsend#1103]
![image](https://user-images.githubusercontent.com/11063799/171959195-d8dad77d-7cbe-408c-b5d7-cbaf6ee30485.png)

The browser console appears to have an error message.
![image](https://user-images.githubusercontent.com/11063799/171958365-1f0341f4-6c17-43e5-86b3-91769b6173f6.png)

![image](https://user-images.githubusercontent.com/11063799/171958504-9ba42507-6c33-4150-923c-aa7c40120062.png)

**Comment by xzenor** [comment]
Just upgraded? I had the same thing and in my case it was just a caching problem. shift+refresh (Firefox) solved it for me. It depends on your browser how you do a hard refresh so it reloads all elements..

**Comment by JustBru00** [comment]
Appears to be fixed after clearing browser cache. Thanks for the tip @xzenor.
