### ISSUE TITLE
File Upload Error

### ISSUE THREAD

**Issue by dr-waterstorm** [projectsend/projectsend#1107]
We've been using ProjectSend a very long time and it served us very well. 
However lately (I do not know exactly when this started) larger files cannot be uploaded via the webinterface anymore. It starts out just fine, but then suddenly stops working. The "Network" tab of my Vivaldi (Chromium) does show this:

![image](https://user-images.githubusercontent.com/11409264/172610469-f7800163-1b0c-4b89-8fe9-179273c216c7.png)

It seems to work a few chunks but then suddenly stops returning a 403. The most interesting part is, that the webserver shows a different error when this happens:

```
[08/Jun/2022:13:52:40 +0200] "POST /includes/upload.process.php HTTP/2.0" 404 436 "https://data.computomics.com/upload.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.72 Safari/537.36"
```

So it's a 403 in my browser, while it shows a 404 on the server.

My current PHP server settings (Apache) are:

```
memory_limit = 2048M
upload_max_size = 1024M
post_max_size = 1024M
max_execution_time = 300
```

I had this issue on the r1415 but I've just upgraded to r1420 and still have the same problem. 

This only seems to happen on "bigger" files. A smaller sample with ~9 MB worked just fine.

Does anyone have any insight and may be able to help here? If any more information is needed let me know and I'll gladly share.

**Comment by Dargazo** [comment]
I recently encountered this on our site.  In our case, this turned out to be an issue with WordFence (a WordPress plugin) that was also installed.

We added the following code to the .htaccess located in our ProjectSend root folder to fix our issue:

```
<IfModule mod_php5.c>  
	php_value auto_prepend_file none  
</IfModule>  
<IfModule mod_php7.c>  
	php_value auto_prepend_file none  
</IfModule>  
<IfModule mod_php.c>  
	php_value auto_prepend_file none  
</IfModule>  
<IfModule mod_rewrite.c>  
    RewriteEngine Off  
</IfModule>  
```

**Comment by dr-waterstorm** [comment]
Thank you for the hint. I've added the settings to the .htaccess. Sadly this did not fix the issue.
It is a separate vhost so projectsend is the only thing running in that particular space. There is nothing else installed in that webspace.

Do you have any other tips that may help out here :) ?

**Comment by dr-waterstorm** [comment]
It actually turned out to be a ModSecurity/firewall issue. Thank you for the help :)

If someone stumbles across this issue and has the same problem, I needed to add

```
SecRuleRemoveById {myid}
```

to the Apache config to fix this issue.
