### ISSUE TITLE
Captcha Error after Updating from r1335 to r1420

### ISSUE THREAD

**Issue by n3roGit** [projectsend/projectsend#1108]
![image](https://user-images.githubusercontent.com/8565847/172615275-261f0143-2800-4aa0-ac8d-dfb264baee1a.png)

**Comment by ignacionelson** [comment]
You need to fix it in the database directly.
In your options table (probably tbl_options) find the row with the name recaptcha_enabled and change the value to 0
Or edit the recaptcha_site_key and recaptcha_secret_key also there with your new credentials.

**Comment by n3roGit** [comment]
I do not have this row in my database. It is also not updated after uploading the files.

Where I can find the config file to disable caotcha?

Reference #1102
