### ISSUE TITLE
$_POST unchecked

### ISSUE THREAD

**Issue by Philippe-M** [projectsend/projectsend#1115]
Hello,

I've been following the project for many years and randomly come across this code in the index.php file: https://github.com/projectsend/projectsend/blob/99ab2c4ac7bb16ba040a7e035677d7ea0a6c36f3/index.php#L48

It redirects to the function that allows authentication and I am worried to discover that there is no control carried out on the content of the variables $_POST['username'] and $_POST['password']. They are reused directly in the sql query. Except that I missed a few things. Seems to me like this is a way to pass anything and everything in the query.

**Comment by ignacionelson** [comment]
Hi! The query is safely run via a prepared PDO statement. You could add htmlentities or any other sanitizing filter by it's not really necessary in this case.

**Comment by Philippe-M** [comment]
Ok thank's.
