### ISSUE TITLE
Private methods cannot be final on PHP 8.0

### ISSUE THREAD

**Issue by Trapulo** [projectsend/projectsend#1117]
r1420: if running on PHP 8.0 after a file upload it fails:

Got error 'PHP message: PHP Warning: Private methods cannot be final as they are never overridden by other classes in vendor/tamtamchik/simple-flash/src/Flash.php on line 31

**Comment by ignacionelson** [comment]
Seems like Flash should not be instantiated, which is what I did... I'll replace the calls with a static one

**Comment by ignacionelson** [comment]
Fixed on 5d0e9cdf507c251fdf5e4d89d068d521e0f3b03d

**Comment by ignacionelson** [comment]
Oh, my bad.  This was not the issue, but the changes where needed anyway
