### ISSUE TITLE
Email notification stopped after r1424

### ISSUE THREAD

**Issue by iincitr** [projectsend/projectsend#1118]
Mail notification stopped. Neither option to send mail Test not working.

**Comment by DreR7** [comment]
We are on r754 - and i think there is an issue with the Modern / Basic authentication depreciation with that version. 

Emails just fail

**Comment by ignacionelson** [comment]
> Mail notification stopped. Neither option to send mail Test not working.

Do you get any debug message after trying to send a test?

**Comment by iincitr** [comment]
No nothing In postfix log even no mail que

9 Ağu 2022 Sal, saat 21:22 tarihinde Ignacio Nelson <
***@***.***> şunu yazdı:

**Comment by iincitr** [comment]
Yes
email-test.php:1          POST https://sertifika.xxx.xom/email-test.php 500
(Internal Server Error)

**Comment by iincitr** [comment]
1. Request URL:
      https://sertifika.umskalite.com.tr/email-test.php
      2. Request Method:
      POST
      3. Status Code:
      500 Internal Server Error
      4. Remote Address:
      185.149.103.33:443
      5. Referrer Policy:
      strict-origin-when-cross-origin
      1. Response HeadersView source
   1. Cache-Control:
      no-store, no-cache, must-revalidate, max-age=0
      2. Connection:
      close
      3. Content-Type:
      text/html; charset=UTF-8
      4. Date:
      Fri, 12 Aug 2022 20:16:05 GMT
      5. Expires:
      Sat, 26 Jul 1997 05:00:00 GMT
      6. Pragma:
      no-cache
      7. Server:
      Apache/2.4.53 (Unix) OpenSSL/1.0.2k-fips
      8. Transfer-Encoding:
      chunked
      9. Vary:
      User-Agent
      10. X-Powered-By:
      PHP/7.3.0
      2. Request HeadersView source
   1. Accept:

      text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
      2. Accept-Encoding:
      gzip, deflate, br
      3. Accept-Language:
      en-US,en;q=0.9
      4. Cache-Control:
      max-age=0
      5. Connection:
      keep-alive
      6. Content-Length:
      596
      7. Content-Type:
      multipart/form-data; boundary=----WebKitFormBoundarybshg8zG9lBQFWvkN
      8. Cookie:
      XDEBUG_SESSION=PHPSTORM; menu_contracted=false;
      PHPSESSID=2mdrr7l6o5f6t8snqro8jsoqdh
      9. DNT:
      1
      10. Host:
      sertifika.xxxx.xxx.tr
      11. Origin:
      https://sertifika.xxx.com.tr
      12. Referer:
      https://sertifika.xxxxx.com.tr/email-test.php
      13. sec-ch-ua:
      "Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"
      14.
      sec-ch-ua-mobile:
      ?0
      15. sec-ch-ua-platform:
      "Windows"
      16. Sec-Fetch-Dest:
      document
      17. Sec-Fetch-Mode:
      navigate
      18. Sec-Fetch-Site:
      same-origin
      19. Sec-Fetch-User:
      ?1
      20. Upgrade-Insecure-Requests:
      1
      21. User-Agent:
      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
      like Gecko) Chrome/104.0.0.0 Safari/537.36

**Comment by iincitr** [comment]
So
I just copied projectsend *root folder files* from r1420 to r1424 then it
worked again. :)

**Comment by vince844** [comment]
Hi @ignacionelson is there any changelog available for the new version r1424?

**Comment by iincitr** [comment]
And

max_execution_time 300

**Comment by ignacionelson** [comment]
@vince844 Change logs are always available at https://www.projectsend.org/change-log/
