### ISSUE TITLE
Help with updating the platform

### ISSUE THREAD

**Issue by DreR7** [projectsend/projectsend#1119]
Hi All, 

I have inheritted this Project Send FTP Server at a company I work for, currently running version R754 (quite out of date I know) There is no internal change history of Who / When / How it was set up and I am wondering if there is an update pathway to the latest version... 

If so, how do I go about updating the software? 

Many thanks 
Andre

**Comment by ignacionelson** [comment]
Hi! Just by unpacking the new version over the existing installation and then logging in, everything should be updated. If any of the system folders are not writable, PS should let you know when you try to upload a file. Make a backup of the database just in case the changes are too many to handle at once but that shouldn't happen.

**Comment by DreR7** [comment]
It’s on Linux 😭😭

Kind regards,
André

________________________________

André Richardson
IT Infrastructure Engineer
t. 01925 918379
m. 07710 172019
e.
***@***.***
Notice of Confidentiality
This transmission contains information that may be confidential. It is intended for the exclusive use of the recipient to whom it is addressed. If you are not the intended recipient of the message, or authorised to receive it for the intended recipient, you should notify us immediately and you should delete it from your system and may not disclose its contents to anyone else.  Unauthorised use, copying, forwarding or disclosure of any of it may be unlawful.
​
Registered Office: Involve Visual Collaboration Limited, Martin Dawes House, Europa Boulevard, Westbrook, Warrington, WA5 7WH.  Company Number: 2383157
 
From: Ignacio Nelson ***@***.***>
Sent: Tuesday, August 9, 2022 7:16:12 PM
To: projectsend/projectsend ***@***.***>
Cc: André Richardson ***@***.***>; Author ***@***.***>
Subject: EXTERNAL: Re: [projectsend/projectsend] Help with updating the platform (Issue #1119)


CAUTION: This email originated from outside the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.

Hi! Just by unzipping the new version and then logging in, everything should be updated. If any of the system folders are not writable, PS should let you know when you try to upload a file. Make a backup of the database just in case the changes are too many to handle at once but that shouldn't happen.

**Comment by ignacionelson** [comment]
PS works best on a Linux server :)
Also make sure to have at least php 7.4 available when updating.
