### ISSUE TITLE
Language does not get changed with php7.4

### ISSUE THREAD

**Issue by suppqt** [projectsend/projectsend#1121]
Strange issue here.
Downloaded german language here: https://www.projectsend.org/translations/index.php
Put in in root folder.
Lang folder contains now de_DE.po/mo

changed sys.config to define('SITE_LANG','de_DE');

just partly german, most of it is not. just 2 strings, not related to caching, changed browser and private session.

![image](https://user-images.githubusercontent.com/3234897/185870303-b326801c-e02e-4ed7-9684-dccf88cd731f.png)

**Comment by suppqt** [comment]
Also r1420 seems not to be compatible with php 7.4.
widgets are not getting loaded.

updated to php8.1 and r1420, same issue. widgets are not getting loaded, see screenshot and language is broken

**Comment by ignacionelson** [comment]
Hi! Please download this translation instead
https://www.projectsend.org/translations/get.php?lang=de
(German, instead of German (Germany)) which seems to be complete. I got a message a few days ago about a user that discovered this.
Regarding widgets, please check the browser's console and let me know which errors you find.

**Comment by suppqt** [comment]
> Hi! Please download this translation instead https://www.projectsend.org/translations/get.php?lang=de (German, instead of German (Germany)) which seems to be complete. I got a message a few days ago about a user that discovered this. Regarding widgets, please check the browser's console and let me know which errors you find.

language works fine ! cheers for that

----

errors here:

```
ncaught SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (widget_news.js:39:1)
    at c (jquery.min.js:2:28294)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:29039)
    at l (jquery.min.js:2:79817)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82271)
dashboard.php:1 Uncaught SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (widget_action_log.js:77:1)
    at c (jquery.min.js:2:28294)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:29039)
    at l (jquery.min.js:2:79817)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82271)
```

**Comment by ignacionelson** [comment]
Great, that's one less issue already!
Regarding the error, seems like you'll also need to check the Network tab and see the response from the ajax call to get the full details.

**Comment by suppqt** [comment]
> Great, that's one less issue already! Regarding the error, seems like you'll also need to check the Network tab and see the response from the ajax call to get the full details.

works fine
"$baseurl/includes/widgets/ajax/statistics.php?days=15&_=1661178374137" gets fetched immidiatly.
also displays fully json in browser by calling directly.
seems something within object fetching in code.

r1335 works fine when i overwrite this release to root directory.

**Comment by ignacionelson** [comment]
Looks like a header issue in the response. I'll check this.

**Comment by ignacionelson** [comment]
Fixed on r1584
