### ISSUE TITLE
Index.php only shows top banner

### ISSUE THREAD

**Issue by UncleWod** [projectsend/projectsend#1122]
I've installed projectsend about 6 times now. Five through an install module my ISP has to install software for their clients and once using the latest version manually. Every time I install projectsend, the index.php file only shows the top banner and nothing else on the page. From the README.md, I should receive and login prompt. I only see the head banner.

Thanks,
UncleWod

**Comment by thewriteway** [comment]
what are your nginx config settings?

**Comment by UncleWod** [comment]
I'm looking through all the projectsend files for nginx but am coming up empty. What file is the information located?

Thanks,
Uncle Wod

------- Original Message -------

**Comment by ignacionelson** [comment]
Seems like you are having an issue that prevents the page from rendering.
You need to enable debug mode (by editing your personal includes/config.php file and changing define('DEBUG', false);
to
define('DEBUG', true);

Any server error might appear then

**Comment by ignacionelson** [comment]
It could be anything from a missing php dependency, or a version conflict, etc. So enabling debug would be the best way to check it.
If nothing comes up, then you need to look for a php error log file, but its location depends on your hosting provider

**Comment by UncleWod** [comment]
I did that and here is what was returned:

Notice: Undefined index: cron_key in/home/imyourgu/public_html/wominvgrp/includes/Classes/Options.phpon line131

Warning: Cannot modify header information - headers already sent by (output started at /home/imyourgu/public_html/wominvgrp/includes/Classes/Options.php:130) in/home/imyourgu/public_html/wominvgrp/includes/active.session.phpon line10

Warning: Cannot modify header information - headers already sent by (output started at /home/imyourgu/public_html/wominvgrp/includes/Classes/Options.php:130) in/home/imyourgu/public_html/wominvgrp/includes/active.session.phpon line11

Thoughts?

Uncle Wod
Womack Investment Group Files

Fatal error: Uncaught Error: Call to undefined function mime_content_type() in /home/imyourgu/public_html/wominvgrp/includes/functions.php:1203 Stack trace: #0 /home/imyourgu/public_html/wominvgrp/includes/functions.php(1210): getFileTypeByMime('/home/imyourgu/...') #1 /home/imyourgu/public_html/wominvgrp/includes/functions.php(1240): isImage('/home/imyourgu/...') #2 /home/imyourgu/public_html/wominvgrp/includes/functions.php(1354): file_is_image('/home/imyourgu/...') #3 /home/imyourgu/public_html/wominvgrp/includes/functions.php(1383): generate_logo_url() #4 /home/imyourgu/public_html/wominvgrp/index.php(98): get_branding_layout(true) #5 {main} thrown in/home/imyourgu/public_html/wominvgrp/includes/functions.phpon line1203

------- Original Message -------

**Comment by ignacionelson** [comment]
Seems like you are missing a php extension 
Check the selected answer here:
https://stackoverflow.com/questions/45831079/call-to-undefined-function-mime-content-type

"You need to install fileinfo extension in order to use mime_content_type. In debian based system you can install it via apt: apt-get install php-mime-type

More info: http://php.net/manual/en/book.fileinfo.php"

Hope that helps!

**Comment by UncleWod** [comment]
Initially my ISP stated that the PHP fileinfo was installed on the server, then a tech came back and let me know that the version was not installed properly and she had fixed the issue. I can now at least see the login for the Projectsend software, but I am still receiving these errors above the login:

Notice: Undefined index: cron_key in/home/imyourgu/public_html/wominvgrp/includes/Classes/Options.phpon line131

Warning: Cannot modify header information - headers already sent by (output started at /home/imyourgu/public_html/wominvgrp/includes/Classes/Options.php:130) in/home/imyourgu/public_html/wominvgrp/includes/active.session.phpon line10

Warning: Cannot modify header information - headers already sent by (output started at /home/imyourgu/public_html/wominvgrp/includes/Classes/Options.php:130) in/home/imyourgu/public_html/wominvgrp/includes/active.session.phpon line11

Is this another instance where the ISP might not have generated the keys properly?

Uncle Wod

------- Original Message -------

**Comment by ignacionelson** [comment]
That seems like an error on my part, the key is part of the options and might not have been generated during install.
It's just a matter of adding a random string in the cron options page.
Other notices and warnings will most likely happen sometime so if you disable debug, you can now probably test and use the system fully

**Comment by UncleWod** [comment]
It's all good. I was thinking of turning off debug and seeing what happened.

Once I did, the login screen came up nice and clean.

Thank you for your assistance.

Sincerely,
Uncle Wod

------- Original Message -------

**Comment by UncleWod** [comment]
I hope so too. I do not have access to the command line of this server nor root. It is my ISP and I have asked them for assistance. The ironic thing is that they are the ones who allow the automated install of Projectsend in their client dashboard. I'll let you know either way they decide. Do you know if I can comment this section out and still use the software? I reall only need it for documents at this point.

Uncle Wod

------- Original Message -------

**Comment by ignacionelson** [comment]
Were you able to fix your instance?

**Comment by UncleWod** [comment]
Many apologies. I thought I had shared my results.

After some tactful talking to my ISP they realized they had not set up the server side PHP. Once they did, the program worked correctly.

Thank you for the follow up.

Sincerely,
Uncle Wod

------- Original Message -------

**Comment by ignacionelson** [comment]
Great, glad it's working now!
