### ISSUE TITLE
Systemuser "Uploader" does not see files in r1420

### ISSUE THREAD

**Issue by terrar** [projectsend/projectsend#1133]
I just found out that System User " Uploader" will not see the files which are uploaded from System User "Account Manager" and "System Administrator" in r1420. Only own uploaded files are visible.
Is this a bug?

**Comment by terrar** [comment]
Software:
Version: r1420 
Default upload max. size : 2048 mb
Template :Default

System:
Server: Apache/2.4.41 (Ubuntu) 
PHP version: 8.0.22
Memory limit: 512M
Max execution time: 14400
Post max size: 8M
 
Database:
Driver: mysql
Version: 8.0.30-0ubuntu0.20.04.2

**Comment by ignacionelson** [comment]
Check r1584, this should be fixed now

**Comment by terrar** [comment]
Unfortunately still the same under r1605.
