### ISSUE TITLE
Question about user vs client permissions

### ISSUE THREAD

**Issue by tshives26** [projectsend/projectsend#1136]
On the file edit page, I've added a drop down box that allows clients to edit the category of their files. When I test from a client account I don't get any failures or bad errors back. Everything looks clean and clear but the category of that edited file is not being changed on the client or user side (I assume not in the DB as well). Is there somewhere specific that allows certain permissions based on if an account is a client vs a user/admin?

I found this is categories.php (line 63) but not sure if its the right spot. If so, am I able to copy a line and just change it to "categories" for clients to be able to edit category? 

>     /**
>      * Set the properties when editing
>      */
>     public function set($arguments = [])
>     {
>         $this->id = (!empty($arguments['id'])) ? encode_html($arguments['id']) : null;
>         $this->name = (!empty($arguments['name'])) ? encode_html($arguments['name']) : null;
>         $this->parent = (!empty($arguments['parent'])) ? (int)$arguments['parent'] : null;
>         $this->description = (!empty($arguments['description'])) ? encode_html($arguments['description']) : null;
>     }

If this is not the proper location, where specifically can I edit the permissions of different groups to allow such a thing?

Perhaps editing this on line 13 will solve the problem?

>     class Categories
>     {
>     private $dbh;
>     private $logger;
> 
>     private $id;
>     private $name;
>     private $parent;
>     private $description;
>     private $created_date;
> 
>     private $validation_passed;
>     private $validation_errors;
> 
>     // Permissions
>     private $allowed_actions_roles;

**Comment by ignacionelson** [comment]
Hi!
You need to change includes/Classes/Files.php
method saveCategories() (line 1139)

Remove the check

        $allowed = array(9,8,7);
        if (!current_role_in($allowed)) {
            return false;
        }

Hope that helps!

**Comment by tshives26** [comment]
This was exactly it, thanks so much!
