### ISSUE TITLE
To find and choose the orphan files  takes a longer time.

### ISSUE THREAD

**Issue by iincitr** [projectsend/projectsend#1137]
Hi,

To find and choose the orphan files new screen takes a longer time.
And notice that for the first show the screen can not be chosen any files. 
image.png
Then we have to click Allowed() gray text again waiting for a long time 

![manage files orphan](https://user-images.githubusercontent.com/58163198/191735189-47bceac6-32f2-45ab-9f90-162d6a84d96f.png)

after that selection box appears.

![manage files orphan2](https://user-images.githubusercontent.com/58163198/191735230-45b894c8-869c-4543-a044-5c68933c6c68.png)

Could you fix it to get rid of time-consuming?[](url)

**Comment by ignacionelson** [comment]
How many files do you have? Trying to see if this is a problem with the db comparison

**Comment by iincitr** [comment]
17000+  Files

**Comment by ignacionelson** [comment]
Oh wow. That must be it. I need check this. If I send you a file to replace, can you give it a shot?

**Comment by iincitr** [comment]
Sure, thank you

22 Eyl 2022 Per, saat 21:54 tarihinde Ignacio Nelson <
***@***.***> şunu yazdı:

**Comment by ignacionelson** [comment]
I wonder if the slow part is the query, or reading the directory

**Comment by iincitr** [comment]
May  reading the directory

**Comment by iincitr** [comment]
I just replaced  import-orphans.php take  a longer time again but no file listed this time 

![image](https://user-images.githubusercontent.com/58163198/191846403-583e3c87-4a6a-4f35-9aa4-5e15deb31dfd.png)

even though click the allowed ()

**Comment by ignacionelson** [comment]
Would it be possible for you to send me an admin user and ftp credentials so I can run tests? If you can, send them at contact@projectsend.org please.

**Comment by ignacionelson** [comment]
Thank you for sending the credentials.
I've managed to reduce the loading time from > 20 seconds to around 6. Still needs improvement but it's a start. In the future, I believe uploaded files might need to be sorted into folders by date to avoid this kind of issue.
Also, I've applied a small change so allowed files are selectable by default.
Hope it helps.

**Comment by iincitr** [comment]
Great, thank you for your help.

**Comment by iincitr** [comment]
May be reading directory

22 Eyl 2022 Per, saat 23:01 tarihinde Ignacio Nelson <
***@***.***> şunu yazdı:
