### ISSUE TITLE
Unable to remove last/all categories from file

### ISSUE THREAD

**Issue by Verzijl** [projectsend/projectsend#1139]
Great work on ProjectSend! It is a great piece of software.

I was testing out a fresh install of projectsend and I found a little bug concerning the removal of categories from a file.

After creating categories I can add them to files without an issue. The issue is with deleting the last category or deleting them all from a file at the same time. It will fail. When saving, instead of seeing 'Files saved correctly' and the list of edited files, it just shows the header 'Edit files'. When at the same time removing e.g. groups from the file, it will remove the groups, but not the category. 

So just to be clear, when trying to remove 1 or more categories from a file such that there are no more categories attached to that file, it will not update correctly. The categories will remain attached.

Deleting the actual category from the categories administration page works and this will remove the category from all the files, but this if obviously not the preferred route.

**Comment by ignacionelson** [comment]
Hi! I'm aware of this issue and it's fixed in the development version.
Hopefully a new release will be out before the end of the month.
Thanks for the report!

**Comment by Verzijl** [comment]
That is great! Thank you for the quick response!

**Comment by ignacionelson** [comment]
Fixed on r1584
