### ISSUE TITLE
News : PDO updates

### ISSUE THREAD

**Issue by lenamtl** [projectsend/projectsend#114]
Great News!

Ignacio have updated the repository, so the code now is using PDO (prepare statement).
Before updating your production environment to the latest version you should prior test it.
We also need some testers that use latin characters.

PDO required the PDO driver for MySQL so you may have to enabled it.

To enabled PDO extension from php.ini

extension=php_pdo.dll
extension=php_pdo_mysql.dll
and restart the service if your are local.

Thanks

**Comment by lenamtl** [comment]
Make sure you have enabled PDO extension from php.ini

extension=php_pdo.dll
extension=php_pdo_mysql.dll
and restart the service if your are local.

**Comment by lenamtl** [comment]
Hi, there is issue with session on the r608 r609 so please don't use it in production enviromnent.

**Comment by mschop** [comment]
@lenamtl I would suggest closing this issue. I cannot imagine, that it is needed any more.
