### ISSUE TITLE
Layout Issue on Installation Version r1584

### ISSUE THREAD

**Issue by mariushosting** [projectsend/projectsend#1144]
@ignacionelson 
Layout is bugged on the latest version r1584 when you have to add your personal info.

![Screenshot 2022-10-17 20 30 06](https://user-images.githubusercontent.com/37554361/196286161-1ee2f80f-f3aa-4fde-8085-fb0804fe40c8.png)

**Comment by ignacionelson** [comment]
Thanks for reporting. What URL are you getting for the css assets in the generated code?

**Comment by ignacionelson** [comment]
This is due to the assets files being cached by the browser. The solution is to add a version number when loading them. Will implement this method in the next release.
