### ISSUE TITLE
Preview iframe too small

### ISSUE THREAD

**Issue by ch1138** [projectsend/projectsend#1146]
The preview functionality in v1584 works, but the iframe shown in the modal does not really allow to see PDFs in a useful way.

I have used the new Custom CSS feature to resolve the issue:

- the iframe should fill 100% of the modal's width
- I have defined a min-height of 48em to be able so see some stuff

The code:

`div.embed-responsive iframe {
	width: 100%;
	min-height: 48em;
}`

I do not think that my code is the way to go, I just wanted to chime in with the issue that the preview does not provide much "preview".

Thank you so much for the 1584 update. It is a huge progress. :)

**Comment by serg499** [comment]
@ch1138 Thank you very much for your solution! I also have the same issue.
In my case this code looks better (for 1920x1080):
`div.embed-responsive iframe { width: 100%; min-height: 39em; }`

**Comment by ignacionelson** [comment]
Thank you both for your comments and solution!
Applied here b66852f
