### ISSUE TITLE
z-index issue with main_side_menu in the dashboard

### ISSUE THREAD

**Issue by ch1138** [projectsend/projectsend#1147]
![z-index-issue](https://user-images.githubusercontent.com/26325122/196631642-f4b1dff9-b83d-4495-adb8-2a5261331ee1.jpg)

Dropdown items in the main_side_menu are being shown **behind** the boxes of the div.widget_counters, resulting not to be legible.

My quick and dirty fix:

`.main_side_menu {z-index: 1000;}`

**Comment by ignacionelson** [comment]
Thank you!! Applied here 5d3a872
