### ISSUE TITLE
 Problem with inserting user into groups (r1584)

### ISSUE THREAD

**Issue by Farneyaurelio** [projectsend/projectsend#1148]
Greetings colleagues, after updating to version r1584, I came across a problem. I can't add users to the user group. The same problem happens when I'm on the user edit page, I can't insert the groups. Before there was a box to type, but in this new version this has disappeared. 

See the images below.

![2022-10-19_11h38_02](https://user-images.githubusercontent.com/116181924/196722669-e4636bb2-8ef0-48ec-9570-f80d48ccd27b.png)
![2022-10-19_11h38_03](https://user-images.githubusercontent.com/116181924/196722870-37cc188e-ff65-47b5-9913-309053a63342.png)

Thank you in advance.

**Comment by ignacionelson** [comment]
Thanks for reporting, will fix ASAP

**Comment by ignacionelson** [comment]
I've tested locally and it looks like a local cache issue on your side. Please do a full reload (ctrl+shift+f5) or try a private window and see if it works then

**Comment by Farneyaurelio** [comment]
> Eu testei localmente e parece um problema de cache local do seu lado. Por favor, faça uma recarga completa (ctrl + shift + f5) ou tente uma janela privada e veja se funciona

Hi ignacionelson, you are correct. I updated the location and it fixed it.

Thank you very much.

**Comment by ignacionelson** [comment]
Glad it worked!
