### ISSUE TITLE
Manage Files not showing files (r1584)

### ISSUE THREAD

**Issue by rdw75** [projectsend/projectsend#1150]
System Users can't view any files in Manage Files (r1584)
I'm used Nginx and Nginx-Accel activated

**Comment by ignacionelson** [comment]
Is the full page rendering? Anything in the error log if you enable debug mode in the config file?

**Comment by rdw75** [comment]
oh i was uploaded big size BMP file (400M)
delete the file fixed and files are showing

**Comment by ignacionelson** [comment]
Thanks for the update
