### ISSUE TITLE
Upload Button in "View my Files" of default template Faulty?

### ISSUE THREAD

**Issue by SnappyBird** [projectsend/projectsend#1151]
I have been testing a bit around and it seems to me like the Upload Button in the "View my Files" Tab for the default template of a Client is faulty. It redirects to /my_files/upload.php instead to /upload.php .
I solved this Issue by Altering line 46 in /templates/default/template.php to:

`'url' => BASE_URI.'upload.php',`

This may only affect me, but I thought I would share it here.

As far as I can see, the other two templates that are give are not affected by this behaviour.

**Comment by ignacionelson** [comment]
Thank you! Applied your solution here 7685200
