### ISSUE TITLE
Full description in new file available email notification 

### ISSUE THREAD

**Issue by JohnOSween** [projectsend/projectsend#1153]
Is there anyway to include the full file description in a notification email a user receives so they are better informed of what the file contains?

**Comment by iincitr** [comment]
This will be good improvement:)
21 Eki 2022 Cum, saat 15:59 tarihinde JohnOSween ***@***.***>
şunu yazdı:

**Comment by ignacionelson** [comment]
Wondering why you are not seeing the description. It is indeed part of the markup

EmailNotifications.php, lines 286-289

`            if (!empty($file_data['description'])) {
                $html .= '<p>'.$file_data['description'].'</p>';
            }
`

**Comment by ignacionelson** [comment]
Maybe this can help

7f140ad
