### ISSUE TITLE
Turn Autocomplete off in 2FA

### ISSUE THREAD

**Issue by SnappyBird** [projectsend/projectsend#1154]
I don't think, that autocomplete (previous entries to this field) are needed for 2FA and can be quite disturbing.
I solved this "problem" by altering line 20 in /includes/forms/2fa_verify.php to:

`<input class="text-center form-control" type="text" name="n<?php echo $i; ?>" id="n<?php echo $i; ?>" maxlength="1" autocomplete="off" required />`

Maybe this will also improve the experience for other users.

**Comment by ignacionelson** [comment]
Thank you! Applied here cedaf9a
