### ISSUE TITLE
Password generate button not working in r1584

### ISSUE THREAD

**Issue by skipper0922** [projectsend/projectsend#1156]
Hello, I have a problem with password generate button. The password generation button does not work. When I click on it, nothing happens in the password field.
And also I have a lot of format problems, as you can see in picture.
![Screenshot_1](https://user-images.githubusercontent.com/95620163/197345796-fe0851df-864b-45ba-ba7b-2a479f9fda83.png)
![Screenshot_3](https://user-images.githubusercontent.com/95620163/197345846-b96b20c8-ac8c-4cf6-945d-ecca04f6296a.png)
![Screenshot_2](https://user-images.githubusercontent.com/95620163/197345847-d208254a-6766-47b7-a168-d213594041ce.png)

**Comment by ignacionelson** [comment]
Try reloading with ctrl + shift + r, this is a browser cache issue and will be resolved in the next release

**Comment by skipper0922** [comment]
Thank you for your promptness. What about broken alignment? Should it be like this in the new version?

**Comment by skipper0922** [comment]
Thank you very much. Everything is ok. We appreciate everything you do for this project, the Projectsend. ❤️
