### ISSUE TITLE
Accentuated words on "Recent activity" widget.

### ISSUE THREAD

**Issue by marcoslaurito** [projectsend/projectsend#116]
Accent's are not displaying ok. They're replaced by strange characters. Screenshot as example. I've marked in yellow where should say "abrió sesión", ó character replaced by odd things.
![captura](https://cloud.githubusercontent.com/assets/17474493/15831054/f1e47482-2bf1-11e6-8eb4-4da0eb389084.PNG)
In other parts of the system (actions-log.php for example) accents display OK.
I'm using ProjectSend r609.

**Comment by marcoslaurito** [comment]
Fixed it removing the html_output function from home-log.php line 52.
Now the accents on the Recent Activities widget displays ok.

**Comment by lenamtl** [comment]
I'm working on a fork that will handle the accents correctly, stay tuned.

**Comment by mschop** [comment]
@marcoslaurito Removing html_output is not recommended as this can create security vulnarbilities. Please checkout the latest version of ProjectSend. If the problem there still exists, please reopen the issue.
