### ISSUE TITLE
Issue with sorting

### ISSUE THREAD

**Issue by skipper0922** [projectsend/projectsend#1161]
Hello, when trying to sort files, by any criteria, it is redirecting me to 404.

**Comment by ignacionelson** [comment]
Which version are you using? This should be fixed in the latest release, r1605

**Comment by skipper0922** [comment]
Yes, with r1605. After update, we get 404 for sorting.

vin., 28 oct. 2022, 21:19 Ignacio Nelson ***@***.***> a scris:

**Comment by ignacionelson** [comment]
What are the URLs before and after sorting?

**Comment by skipper0922** [comment]
This is URL after sorting
https://domain.ro/e-gdpr/e-gdpr/manage-files.php?orderby=timestamp&order=desc

sâm., 29 oct. 2022, 16:24 Ignacio Nelson ***@***.***> a scris:

**Comment by skipper0922** [comment]
sâm., 29 oct. 2022, 17:44 Alexandru Buruga ***@***.***> a
scris:

**Comment by ignacionelson** [comment]
Fixed on 3ad14f9
