### ISSUE TITLE
Blank page after login (after update from version r609 to latest r1605)

### ISSUE THREAD

**Issue by marcoslaurito** [projectsend/projectsend#1164]
Hello, i'm having problems after trying to update from versoin r609 (very old) to the latest available r1605.
After pressing the login button, the system redirects to a blank dashboard.
If i enable debug mode, i can see multiple php errors instead of the blank page.
It is possible to make an update from such an old version an getting all working ok??

**Comment by ignacionelson** [comment]
Hi! Direct upgrade should be possible but I really haven't tested that much of a jump.
Please make sure to have at least php 7.1 available.
Also, paste here the php errors if you can (you can mask the full paths for privacy and security)

**Comment by marcoslaurito** [comment]
> Hi! Direct upgrade should be possible but I really haven't tested that much of a jump. Please make sure to have at least php 7.1 available. Also, paste here the php errors if you can (you can mask the full paths for privacy and security)

Thanks man! 
I'm using PHP version 8.1.7.
Here is a screenshot of the php errors when opening the homepage:


<img width="951" alt="Captura" src="https://user-images.githubusercontent.com/17474493/199334731-dc43f05e-fd7f-4102-8d28-87936f026b8f.PNG">

**Comment by tshives26** [comment]
I believe it's an issue of your PHP version being too high. I had to downgrade back to 7 to get everything to work. I could be wrong though, just some of the same issues I encountered.

**Comment by ignacionelson** [comment]
I have tested up to 8.0.25 without issues. Let me try your version.

**Comment by ignacionelson** [comment]
I've just tested with 8.1 and had no issues apart from a few warnings that I've already pushed a commit for.
Is the file includes/Classes/Options.php missing from your installation?

**Comment by ignacionelson** [comment]
Also the update might have been too much of a leap. It would be a good idea to make a backup of the directory and database, then delete the files (except the upload folder and the includes/sys.config.php file) and uncompress r1605 again. If the database finished upgrading it should be ok. Otherwhise you could make a new install and then manually import some of the old tables data into the new ones.

**Comment by ignacionelson** [comment]
Closing due to no reply. Hope you fixed it!
