### ISSUE TITLE
White label header logo

### ISSUE THREAD

**Issue by gagaym** [projectsend/projectsend#1166]
Without undermining the project is it possible to change the header logo near company name?

I am not technical but i guess it is doable. If the user changed the header logo, footer edit should be disabled and changed to:
Powered by SendFile.

Thoughts?

**Comment by ignacionelson** [comment]
Hi!
You could add a new css asset (Tools -> Assets -> Add css) with the following

```
header .navbar-brand svg {
display: none;
}
```

Hope that helps!

**Comment by gagaym** [comment]
Hi Again

Asset created and code entered being part of the header. However, still the header logo appears.

Any other ideas?

Thanks for your support

**Comment by gravelfreeman** [comment]
> Hi Again
> 
> Asset created and code entered being part of the header. However, still the header logo appears.
> 
> Any other ideas?
> 
> Thanks for your support

I know it's late but add `!important`

```css
header .navbar-brand svg {
display: none !important;
}
```

You can also remove `svg` if you don't want the text to appear too.
