### ISSUE TITLE
login verification code is back in date and time

### ISSUE THREAD

**Issue by gagaym** [projectsend/projectsend#1167]
After enabling login verification on V.1.8.31, code is received by email. However, it is coming outdated and when user tries to renter credentials message reads "You have pending codes to verify. Please wait until 2022-11-04 19:28:38 to request a new one."

Take a note that login attempt was 2022-11-05 @ 03:30:40

Now I am stuck with below screen:
https://snipboard.io/j0tk98.jpg

**Comment by gagaym** [comment]
A quick update, was able to get a new code [for a non technical person like me, it seems that date and time source is not matching with my local geographical date and time], however when entering I am getting "Code Expired"

Is there a way to disable the 2FA from the backend so I can login normally? Keep in view that I am not a technical person :) so need step by step guidance if that is possible.

https://snipboard.io/5F0P1z.jpg

Note: ReCAPTCHA is enabled as well

**Comment by ignacionelson** [comment]
Sorry about this issue. It's an interesting one that I haven't had in any of my test servers but I doubt it's exclusive to yours.
Would you mind giving me an admin user and FTP access so I can test it? All of this could be sent at contact@projectsend.org

**Comment by ignacionelson** [comment]
Or I could send you a test file to replace, I think I might have a solution for this

**Comment by gagaym** [comment]
Thanks for your reply. I just played around in the database after I requested a code, after that changed the time stamp of the generated code and used it to login. After that i disables 2FA.

What is really interesting as per below screenshot, the timestamp generated is 5th of Nov, and the usage of the code is 4th of Nov.

Should I assume that date and time of the database is different from data and time in ProjectSend, hence the issue surfaced?

https://snipboard.io/h86Fjd.jpg

**Comment by ignacionelson** [comment]
Indeed, the date is probably different due to the Timezone setting (Options -> General -> Timezone).
Maybe your server is not running at your local time, but your PS setting (which modifies php's time) is, so there's the difference.
One way to quickly solve it would probably be to set the request date in php also.
It requires 2 lines to be changed
https://github.com/projectsend/projectsend/commit/7d1af94f615c6fe1f0b32ac2c664289586df7a21
If you get the raw file from there or make those changes yourself, I believe your future codes should work OK!

**Comment by gagaym** [comment]
Following the suggested code edits in php, I can confirm it worked. However, database stamps are still not in order :)

Generation stamp is today, usage stamp is yesterday https://snipboard.io/D9WNZJ.jpg

PS timezone is correct.

However as per hostagtor, change server Time Zone with PHP Script is possible, however they do "not offer support to code for this method, nor do [they] promise to make [it] work. ref: https://www.hostgator.com/help/article/can-i-change-the-server-clock-or-time-zone

With your edits, system is now able to recognize request date. Please do let me know that I will not lose those edits with the next upgrade :(

**Comment by ignacionelson** [comment]
Glad it worked! No, I've applied the change to the code base so the next version will include this fix :)
While the time in the DB might not be correct, if the comparison will be made by php, the it's best that the original date is also set by php.
