### ISSUE TITLE
Can't create new folder?

### ISSUE THREAD

**Issue by denizkaraduman** [projectsend/projectsend#1170]
I have logged in as admin. But when i click on new folder, nothing happens.
* I just downloaded last zip from github.

**Comment by ignacionelson** [comment]
Hi! This is still under development and will be available in the next version

**Comment by ignacionelson** [comment]
Closing as this is not (yet) and issue since the feature is not released.

**Comment by iincitr** [comment]
Good to see the "folder" implementation.  
What will be the approach for this feature ?
Thank you for your effort.
