### ISSUE TITLE
Feature Request:Workflow

### ISSUE THREAD

**Issue by denizkaraduman** [projectsend/projectsend#1173]
Hello,
I need workflow feature.
I tried category feature but it's not exactly same thing, i guess.
For example, when any user upload a file, workflow auto start with first stage ( in my case "will be booked" ).
Then admin or any user with have permission can change its current stage to "booked, will be checked" then last stage will be "all done."

**Comment by ignacionelson** [comment]
Hi! This is really interesting but way too complicated to be implemented right now.
Sorry!
