### ISSUE TITLE
Problem on first login of the day

### ISSUE THREAD

**Issue by marcoslaurito** [projectsend/projectsend#119]
When i first login in the day, the system logs in and then the widgets on dashboard page (Satistics and Recent Activities grapsh) keeps loading and never finish. If in that moment I try to acces Files --> Manage files, a red label shows telling me that i've no access to that page (i'm logged in as admin). If try to go to My Profile page, instead to go to Manage Files, the system logs me out and shows me the login page again.
Then if I log out and log back in, everything works normal.
The problem repeats when I log out from ProjectSend and not use it for a while.
Another thing that i've noticed is that when I delete a file on Manage Files the actual file deletes from the server (verified that it is actually dissapeared from /upload/files folder through FTP) but it keeps appearing on the Manage Files page until I refresh the browser a couple of times, then it dissapears from Manage Files as well.

I'm using version r609.
Sorry for my english.

**Comment by lenamtl** [comment]
Hi, 
Make sure you have enabled PDO extension from php.ini
extension=php_pdo.dll
extension=php_pdo_mysql.dll
and restart the service if your are local.

**Comment by marcoslaurito** [comment]
lenamtl, thanks for your constant help.
I'm on a shared hosting account, i think cant enable that directly because i can't touch php.ini
Is there another way to enable that?

**Comment by lenamtl** [comment]
This is probably enabled.

You can check phpinfo by creating a phpinfo.php file and add the following code
and let me know which php version you are using,
for security reason remove the  phpinfo.php file after verification.
```
<?php

phpinfo();

?>
```
Some hosting company allow to have a custom php.ini you can ask them.

**Comment by marcoslaurito** [comment]
PHP version 5.3.29
In phpinfo i'm seeing this, so i think PDO is enabled:

`Configure Command 	'./configure' '--prefix=/opt/php5-3' '--enable-bcmath' '--enable-calendar' '--enable-exif' '--enable-ftp' '--enable-soap' '--enable-intl' '--enable-zip' '--enable-gd-native-ttf' '--enable-magic-quotes' '--enable-sockets' '--enable-fd-setsize=5120' '--enable-mbstring' '--with-curl=/usr' '--with-freetype-dir=/usr' '--with-gettext' '--with-gd' '--with-xmlrpc' '--with-imap=/opt/include/imap' '--with-jpeg-dir=/usr' '--with-mcrypt=/usr' '--with-mhash=/usr' '--with-openssl' '--with-mysql=mysqlnd' '--with-mysql-sock=/var/lib/mysql/mysql.sock' '--with-mysqli=mysqlnd' **'--enable-pdo' '--with-pdo-sqlite' '--with-sqlite' '--with-pdo-mysql=mysqlnd'** '--with-pdo-pgsql' '--with-pgsql' '--with-pear' '--with-png-dir=/usr' '--with-t1lib=/usr' '--with-libxml-dir=/opt' '--with-zlib' '--with-iconv' '--with-xsl=/opt' `

`PDO
PDO support	enabled
PDO drivers 	mysql, pgsql, sqlite, sqlite2

pdo_mysql
PDO Driver for MySQL	enabled
Client API version 	mysqlnd 5.0.8-dev - 20102224 - $Id: 731e5b87ba42146a687c29995d2dfd8b4e40b325 $

Directive	Local Value	Master Value
pdo_mysql.default_socket	/var/lib/mysql/mysql.sock	/var/lib/mysql/mysql.sock`

**Comment by lenamtl** [comment]
Ok thanks for the info.

That is a very strange problem you are having.

Do you have only one or several projectsend installation on your account.
If you have more than one, are you switching from one to another let say you are logged in both installation  at the same time?

**Comment by marcoslaurito** [comment]
I have multiple installations but not on the same server. In the server with the problem i have only this install.
The problem appears even if I use only this installation and this is the only one of my installs with this problem, the rest i'ts working ok.

**Comment by lenamtl** [comment]
Ok, What you can do is cleared all your browser temporary files. 
Login into the installation you have problem to see if you still have the problem.

I got some problem in the past by switching to different installation without clearing the browser temporary files.

**Comment by marcoslaurito** [comment]
I've tried with differente browsers, cleared all temps files, even tried accesing from different pc's, but the problem still exists.
Specially the one with Manage Files page that i'ts not updating correctly after deleting files.

**Comment by lenamtl** [comment]
Ok I'm out of idea, it's look like a refresh problem, I will try to reproduce the problem...
Is there a lot of uploaded file?

**Comment by marcoslaurito** [comment]
Nope. I'm working with 1 or 2 files at the time.

**Comment by marcoslaurito** [comment]
Doing a few more tests i think its a problem with the session at the moment of changing the page, like going from Home to Manage-files. When loading Manage-files page, the System seems not finding the session created before on log in. This happens the first time you log in, if you log out and log in again, session works ok, it exists until you logout.

**Comment by lenamtl** [comment]
yes it is a session problem.

**Comment by marcoslaurito** [comment]
The odd part is that it is working after 1 login-logout. 
Any solution?

**Comment by lenamtl** [comment]
Hi,
I'm in a middle to create a new branch so we can have the old version available and the new PDO version.
I will then compare both package to try to find out where the problem come from.
I'm not the author so for now the new package is still new to me too ;)

**Comment by marcoslaurito** [comment]
Ok, made some progress. There is two different problems on this issue.
First is the session problem, which i have solved by changing permissions on the php session save path, then the server seems to restore these permissions to the defaults and the session problem no longer appears, so this part i'ts solved.
Second is the problem on deleting files from manage-files.php, they delete ok but keep showing in the files list of that page until it is reload a couple of times (seems like a problem with cache or something). Should I open a new issue for this last one?

**Comment by lenamtl** [comment]
Could you tried with latest package to see if this is fixed?
