### ISSUE TITLE
Category list problem

### ISSUE THREAD

**Issue by chezmohamed** [projectsend/projectsend#1195]
I have a problem on the list of categories displayed by the client:
I have category dice which are created in tree structure; on the client interface he sees the complete list without tree structure
how to solve the problem
interface client
![image](https://user-images.githubusercontent.com/26858857/211156222-912d86ba-2700-43aa-857e-0daea7d268cb.png)

Interface Admin
![image](https://user-images.githubusercontent.com/26858857/211156242-e9d1d11a-b6aa-4a3c-a6ce-ae97f068e8b3.png)

Logiciel

Version
    r1605 
Taille maximale du fichier de téléchargement par défaut
    6144 mb.
Modèle
    Default 

Système

Serveur
    Apache 
Version PHP
    8.0.26
Limite de mémoire
    32M
Temps d'exécution maximum
    14400
Post Taille maximale
    8M

Base de données

Driver
    mysql
Version
    10.5.18-MariaDB

**Comment by chezmohamed** [comment]
does anyone have an explanation for this problem ?

**Comment by chezmohamed** [comment]
@ignacionelson please do you have a solution to this problem?

**Comment by ignacionelson** [comment]
Hi! Sorry for the delay, I'm looking into this

**Comment by chezmohamed** [comment]
a solution ?  @ignacionelson

**Comment by ignacionelson** [comment]
Still working on this one. The arranged categories are available on the array (by arranged I mean hierarchically) but the loop is not compatible so I need to remake it

**Comment by chezmohamed** [comment]
we have a serious problem with customers is there no workaround offered?

**Comment by ignacionelson** [comment]
Not yet. This is an open source project that I can only develop on my free time, which has been extremely hard to find this past week.
I have the solution laid out but a new release will take time.
When this fix is uploaded, I'll update here so you can copy the changes into your own installation, which should be easy as it's only 2 files.

**Comment by chezmohamed** [comment]
great i will be waiting impatiently for the fix

**Comment by ehawman** [comment]
@chezmohamed Well that's certainly one response to a dev saying "I do this for free".

If your comment was intended to convey a sense of urgency, I can assure you it did exactly the opposite.

**Comment by ignacionelson** [comment]
@chezmohamed try this, I'm not sure it will work 100%
5ab1b45
Let me know

**Comment by ignacionelson** [comment]
@ehawman Indeed, the previous message was a bit rough, but that "impatiently" on the last one was really funny!

**Comment by chezmohamed** [comment]
Hello
I tested and the problem is solved
![image](https://user-images.githubusercontent.com/26858857/213666892-554c1e78-a994-42d4-acd5-d389816daba8.png)

I apologize if I expressed badly on my last message, but it brought more participants :)
a big thank-you @ignacionelson and once again I apologize
