### ISSUE TITLE
make upload chunk_size configurable

### ISSUE THREAD

**Issue by Dargazo** [projectsend/projectsend#1203]
We recently had an issue on our hosted webserver, leaving us unable to upload large files (anything over 100mb just got stuck. Turns out our hosting provider used a POST rate limiter. This cause the xhr upload POST message to get a server response wit status code 429 (Too many connections). Over this we had no control, and was put in place to prevent DDOS attacks

Our 'fix' was to change the code in the upload.php file, and increase the chunk_size from 1mb to 10mb. This made each xhr message take longer, thus not triggering the rate limiter.

A more elegant solution would be to be able to configure the chunk size through the options menu

**Comment by VollWombat** [comment]
+1 For this.
The change in the upload.php also solved our slow upload speed.
With chunk_size set to 1mb (the default value), a 4,8GB file would upload at ~2,87 MB / sec.
Setting it to 100mb didn't work for us (Error: null: invalid extension showed up), but we tested it with 50mb and it worked well, now with an upload speed of ~24,36 MB /sec.

**Comment by ignacionelson** [comment]
Fixed in https://github.com/projectsend/projectsend/commit/2a4038d2451db80d9dd623abea9da9c48eb4c84e
