### ISSUE TITLE
Public link, where is? (r609 and r754 public link disappears when you change the language)

### ISSUE THREAD

**Issue by log4en** [projectsend/projectsend#121]
Maybe it's another BUG in the version r609 but I can't find the URL for public link.

**Comment by lenamtl** [comment]
The new version will need to be tested thoroughly.
Can you explain a little bit the problem.

**Comment by log4en** [comment]
Doesn't work the Javascript Popup with the public URL

[schermata-2016-06-14-alle-09 46 28](https://cloud.githubusercontent.com/assets/19669305/16034998/0e264c82-3215-11e6-965e-11f46f4151f6.gif)

**Comment by lenamtl** [comment]
Hi,
I'm not the author so I don't know what exactly the changes are between the 2 packages.
I have created a new branch called PDO which will have the new code
and today I will try revert to previous version for the main branch.

**Comment by ignacionelson** [comment]
On which browser are you having this problem?
I have tested on Firefox, Chrome and Edge without issues :/

**Comment by log4en** [comment]
I've tested with two different computers and 3 browser. :(

**Comment by log4en** [comment]
No solution? I really need it. It's possible to downgrade?

**Comment by lenamtl** [comment]
Hi, could you set the config to English and check if this is working.
Once I have similar problem because of language file (french version)

**Comment by log4en** [comment]
Thanx lenamtl! The problem seems fixed. When someone change the language pubic files URL gone.

**Comment by lenamtl** [comment]
The system should prevent that for non english system.
I'll keep this open because switching language is not a real fix ...

**Comment by log4en** [comment]
Yep. It's only a workaround.

**Comment by log4en** [comment]
Problem is always here with r754.
If you choose another language (not english) at log-in screen all public links disappear

**Comment by lenamtl** [comment]
have you tried to upload a new file and test it with the new version?
are you using latin language?
are filename have accent?

I do have an issue sometimes even in english
I have to click twice to open the popup

**Comment by log4en** [comment]
1 - Yes
2 - Sure, italian it's latin ;-)
3 - My god! Nope! :-) No accent e no "space".

**Comment by lenamtl** [comment]
Does Italian language have apostrophe?
If so try edit PO language file do a search and replace to replace them by 
 replace ' by ’ 
when done save th po then Files/Compile to MO
and do a test

You can also check these posts I have found working solution to solve latin issues
#182 #188 

Let me know if you need help and if this is fixing the case...
