### ISSUE TITLE
install/index.php prepended to all URIs Redirected to already-installed.php

### ISSUE THREAD

**Issue by ex3t3r** [projectsend/projectsend#1226]
Hi.

New installation (Build r1605) on Ubuntu server 22.04 LTS (php8.1) following the [Install ProjectSend on Ubuntu 20.04 with Nginx (LEMP Stack)](https://www.linuxbabe.com/ubuntu/install-projectsend-ubuntu-20-04-nginx-lemp-stack) article.

After installation is completed I went to install/index.php.   The page appeared but not showing any of the proper formatting.

On completion of the installation, trying to go to dashboard.php I find that install/index.php prepended to all urls:

> `Refused to apply style from 'http://192.168.1.249/install/index.php/dashboard.php' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled. dashboard.php:1 
> 
> Refused to apply style from 'http://192.168.1.249/install/index.php/dashboard.php' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled. loading.svg:1    
>       
> Failed to load resource: the server responded with a status of 500 (Internal Server Error) install/index.php/assets/img/favicon/favicon-32x32.png:1          
> 
> Failed to load resource: the server responded with a status of 500 (Internal Server Error) install/index.php/assets/img/favicon/favicon-16x16.png:1          
> 
> Failed to load resource: the server responded with a status of 500 (Internal Server Error) dashboard.php:1 
> 
> Refused to apply style from 'http://192.168.1.249/install/index.php/dashboard.php' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.dashboard.php:1 
> 
> Refused to apply style from 'http://192.168.1.249/install/index.php/dashboard.php' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

Attempting to log out and back in redirect me to already-installed.php.
http://<ip>/dashbaord.php  --> Result in 303 redirect to index.php
index.php --> Result in 303 redirect to <ip>/install/index.php/install/already-installed.php
already-installed.php --> Result in recursive 303 redirect to <ip>/install/index.php/install/already-installed.php

I suspect I have an NGINX config issue.
NGINX config file attached.
[nginx_projectsend.txt](https://github.com/projectsend/projectsend/files/10914193/nginx_projectsend.txt)

PS:
 Needed to mod include/main-menu.php  Line 359  (Passing null as first parameter to parse_str issue)  
 Needed to mod include/functions.php Line 966 (Parssing null as first parameter to htmlentities issue) 
 Both these was resolved by adding  ``` ?? ''``` notation.

**Comment by ignacionelson** [comment]
Hi!

`  location ~* \.(?:svg|gif|png|html|ttf|woff|ico|jpg|jpeg)$ {
    try_files $uri /index.php$uri$is_args$args;
    # Optional: Don't log access to other assets
    access_log off;
  }`

Any reason to have the try_files directive there? I assume, based on the extensions, that you wanted to cache those assets, which probably was closer to 

expires 7d;
add_header Cache-Control "public, no-transform";

instead of try files

**Comment by ex3t3r** [comment]
Hi @ignacionelson ,

Yes, that was the intention.  I updated to config.

The issue of the "install/index.php" being prepended to all URI's and the recursive redirection to install/already-installed.php is still the biggest breaking issue.

**Comment by ex3t3r** [comment]
The issue was resolved.  After cleaning up and re-installing.
Problem was that the site route as configured during the install for some reason was filled in as <ip>/install/index.php/  iso just the IP.
