### ISSUE TITLE
Issue Creating Users after upgrade

### ISSUE THREAD

**Issue by kfoxton** [projectsend/projectsend#1258]
After upgrading to the latest version (r1605), we are no longer able to create new users or clients. After enabling debug mode, this is the error that we are getting:

Fatal error: Uncaught Error: Call to undefined function ProjectSend\Classes\mb_strlen() in /var/www/html/sharedfiles/includes/Classes/Validation.php:59 Stack trace: #0 /var/www/html/sharedfiles/includes/Classes/Validation.php(40): ProjectSend\Classes\Validation->required() #1 /var/www/html/sharedfiles/includes/Classes/Users.php(377): ProjectSend\Classes\Validation->validate_items() #2 /var/www/html/sharedfiles/includes/Classes/Users.php(417): ProjectSend\Classes\Users->validate() #3 /var/www/html/sharedfiles/clients-add.php(51): ProjectSend\Classes\Users->create() #4 {main} thrown in /var/www/html/sharedfiles/includes/Classes/Validation.php on line 59.

We attempted to to do a fresh upgrade, by extracting the full zip again, and copying over our sys.config.php file, but that results in the same issue.

Any ideas on how to resolve this?

**Comment by ignacionelson** [comment]
Hi!
Please make sure to enable the mbstring extension on php on your server
https://www.php.net/manual/en/mbstring.installation.php

**Comment by kfoxton** [comment]
That was it! Thank you very much!
