### ISSUE TITLE
Issue when upload, browser console say "JSON.parse"

### ISSUE THREAD

**Issue by https505** [projectsend/projectsend#1262]
Hi everyone,
i have a strange issues when i upload files. Don't care if it is huge or small, i receive the same problem.
I'm on Debian 11, with PHP 8 (from sury repo) and Apache/2.4.56.
The version of Projectsend is the latest.
When i upload files, after some times (can be soon or not) the upload stuck and if i open a web dev on Firefox i can see this error on console:

<details><summary>Error details</summary>
<p>
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    uploadForm upload_form.js:54
    dispatchEvent plupload.full.min.js:29
    trigger plupload.full.min.js:13
    r plupload.full.min.js:29
    dispatchEvent plupload.full.min.js:13
    n plupload.full.min.js:13
    d plupload.full.min.js:13
    dispatchEvent plupload.full.min.js:13
    trigger plupload.full.min.js:13
    failed plupload.full.min.js:29
    upload plupload.full.min.js:29
    dispatchEvent plupload.full.min.js:13
    n plupload.full.min.js:13
    d plupload.full.min.js:13
    dispatchEvent plupload.full.min.js:13
    trigger plupload.full.min.js:13
    failed plupload.full.min.js:29
    uploadChunk plupload.full.min.js:29
    dispatchEvent plupload.full.min.js:13
    n plupload.full.min.js:13
    d plupload.full.min.js:13
    dispatchEvent plupload.full.min.js:13
    trigger plupload.full.min.js:13
    failed plupload.full.min.js:29
    onerror plupload.full.min.js:29
    handleEventProps plupload.full.min.js:13
    dispatchEvent plupload.full.min.js:13
    n plupload.full.min.js:13
    d plupload.full.min.js:13
    dispatchEvent plupload.full.min.js:13
    r plupload.full.min.js:14
    dispatchEvent plupload.full.min.js:13
    n plupload.full.min.js:13
    d plupload.full.min.js:13
    dispatchEvent plupload.full.min.js:13
    trigger plupload.full.min.js:13
    send plupload.full.min.js:15
    send plupload.full.min.js:15
    exec plupload.full.min.js:13
    shimExec plupload.full.min.js:13
    exec plupload.full.min.js:13
    r plupload.full.min.js:14
    u plupload.full.min.js:14
    send plupload.full.min.js:14
    start plupload.full.min.js:29
    a plupload.full.min.js:29
    addItem plupload.full.min.js:29
    y plupload.full.min.js:13
    setTimeout handler*y plupload.full.min.js:13
    addItem plupload.full.min.js:29
    dispatchEvent plupload.full.min.js:13
    n plupload.full.min.js:13
    d plupload.full.min.js:13
    dispatchEvent plupload.full.min.js:13
    trigger plupload.full.min.js:13
    stop plupload.full.min.js:29
    stop plupload.full.min.js:29
    destroy plupload.full.min.js:29
    uploadChunk plupload.full.min.js:29
    dispatchEvent plupload.full.min.js:13
    n plupload.full.min.js:13
    d plupload.full.min.js:13
    dispatchEvent plupload.full.min.js:13
    trigger plupload.full.min.js:13
    done plupload.full.min.js:29
    onload plupload.full.min.js:29
    handleEventProps plupload.full.min.js:13
    dispatchEvent plupload.full.min.js:13
    n plupload.full.min.js:13
    d plupload.full.min.js:13
    dispatchEvent plupload.full.min.js:13
    r plupload.full.min.js:14
    dispatchEvent plupload.full.min.js:13
    n plupload.full.min.js:13
    d plupload.full.min.js:13
    dispatchEvent plupload.full.min.js:13
    trigger plupload.full.min.js:13
    send plupload.full.min.js:15
upload_form.js:54
</p>
</details> 

This is my system information from Projectsend
<details><summary>Details</summary>
<p>
Server
    Apache 
Versione PHP
    8.0.28
Memory limit
    256M
Max execution time
    14400
Post max size
    200M 
</p>
</details> 

I have try to play with chuck dimension on upload.php, but unlucky try.
If you need i can try to retrieve more debug information, if you say me how to do it.
I attach also logs file from Apache2, i have try also Nginx but without success.
[projectsend.test-lab.lnet_access-https.log](https://github.com/projectsend/projectsend/files/11680160/projectsend.test-lab.lnet_access-https.log)
[projectsend.test-lab.lnet_error-https.log](https://github.com/projectsend/projectsend/files/11680161/projectsend.test-lab.lnet_error-https.log)

I can't understand where problem is, with other sites i don't have problems with upload.
Sorry for bad english, i'm Italian and it's very trouble explain problems.

**Comment by ignacionelson** [comment]
Hi! Please check if this fixes it for you
https://github.com/projectsend/projectsend/commit/a3c8e66b0ba6e57ebe59e6202f7e9b8e18d6feb2

Another option would be to set php for PS to version 7.4 until the next release, which will fully support php 8+
Sorry for the inconvenience!

**Comment by ignacionelson** [comment]
Also try setting display_errors to 0 in the php config, since this is just a warning and not a fatal error but it's being set as part of the ajax response which makes the json invalid

**Comment by https505** [comment]
Hi, thanks to reply.
My "i18n.php" is fixed, i don't have that lines in my code.
I have change my PHP version from 8.0 to 7.4.
PHP "display_errors" is Off, from my "www.conf".

This is my config:
<details><summary>Details www.conf PHP-FPM</summary>
<p>
php_admin_value[memory_limit] = 256M</br>
php_admin_value[post_max_size] = 200M</br>
php_admin_value[upload_max_filesize] = 128M</br>
php_admin_value[date.timezone] = Europe/Rome</br>
php_admin_value[session.save_path] = /var/www/.internal/php_sessions</br>
php_admin_value[session.serialize_handler] = igbinary</br>
php_admin_value[session.save_handler] = files</br>
php_admin_value[session.cookie_samesite] = "Strict"</br>
php_admin_flag[display_errors] = off</br>
php_admin_flag[log_errors] = on</br>
php_admin_value[error_log] = /var/log/php7.4-fpm.log</br>
php_admin_value[opcache.error_log] = /var/log/php7.4-opcache.log</br>
</p>
</details> 
The problem persist after this change.

![ProjectSend_JSON-Errors](https://github.com/projectsend/projectsend/assets/135862762/2e0fa505-209a-4167-a6c4-a46abd986369)

I have another site, very simple for upload, with FileGator and don't have problems, the config of the server is the same so in my opinion can't be a wrong config of web server.

**Comment by https505** [comment]
Hi everyone,
i have good news (for me).

Can be a issue with Debian 11 configuration or other, i don't know.
I have try Rocky 8 and Rocky 9, and the upload process goes fine!

I don't know if the problemi is on the config file of php/apache, but with a production-ready distro like Rocky (or Alma) seem to work.

Thanks for help and have a nice day and weekend!
Cheers from Italy ;)

**Comment by https505** [comment]
After further testing and research, I found that the problem occurs when HTTP/2 is enabled in Apache2.
Inserting in the vhost file "Protocols http/1.1" instead of the default "Protocols h2 h2c http/1.1" the problem does not seem to occur.
Probably a problem with HTTP/2's "push" functionality or other protocol mechanisms.
I hope that the information is welcome to those who will encounter a similar problem.
