### ISSUE TITLE
remove loading recaptcha when recaptcha is not used

### ISSUE THREAD

**Issue by jseutens** [projectsend/projectsend#1275]
The following is included even when google recaptcha is not activated.
We don't need the google tracing ;-)

<script name="recaptcha2" src="[https://www.google.com/recaptcha/api.js?v=](view-source:https://www.google.com/recaptcha/api.js?v=)" type="text/javascript"></script>

**Comment by ignacionelson** [comment]
Applied fix here
d40be9e

Thanks for the suggestion!
