### ISSUE TITLE
Buttons in E-mail templates not working

### ISSUE THREAD

**Issue by Maineit** [projectsend/projectsend#1293]
Version: r1605
Server: Apache/2.4.41 (Ubuntu)
PHP version: 7.4.3-4ubuntu2.19

When customizing the E-mail templates, the tags, "replace with default" and "preview this template" button are not working. There is no error, nor action in the developer log. The buttons simply do nothing.

**Comment by ignacionelson** [comment]
Missed this one, sorry. But I wasn't able to reproduce in any browser I've tried.
