### ISSUE TITLE
Error 500 on manage-files.php

### ISSUE THREAD

**Issue by protego-it** [projectsend/projectsend#1299]
Dear Ignacio,
unfortunately I have a problem with manage-files.php.
Out of nothing I get HTTP Error 500. 
I merged the file with the original and they are identical. I still deleted the file on the server and uploaded it from a fresh download.
Same problem.

The permissions are correct (664) and it's only this single file. Everything else is working as intended.
I tested with several browser, deleted cookies and cache, but the error remains on this file.
I have a test installation on the same server, which is working fine but with a different database.

What could cause this? Maybe a corrupt upload? I checked the database, but everything looks ok.
I have no clue where I can start to troubleshoot.

Maybe you have an idea, what causes this. 

I would welcome your response.

**Comment by ignacionelson** [comment]
Hi! Sorry that you are having this issue.
Please enable debug mode to see if php shows the error/s that result in the 500 response.
https://docs.projectsend.org/about/troubleshooting/debug-mode

**Comment by protego-it** [comment]
Thank you for your fast reply.
I get a lot of deprecated messages. I'm on PHP 8.2.14
` Creation of dynamic property ProjectSend\Classes\Users::$statement is deprecated in
/var/www/vhosts/download.mywebsite.com/httpdocs/includes/Classes/Users.php
on line
176


Deprecated
: Creation of dynamic property ProjectSend\Classes\Users::$row is deprecated in
/var/www/vhosts/download.mywebsite.com/httpdocs/includes/Classes/Users.php
on line
187


Deprecated
: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in
/var/www/vhosts/download.mywebsite.com/httpdocs/includes/functions.php
on line
966


Deprecated
: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in
/var/www/vhosts/download.mywebsite.com/httpdocs/includes/functions.php
on line
966


Deprecated
: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in
/var/www/vhosts/download.mywebsite.com/httpdocs/includes/functions.php
on line
966


Deprecated
: Creation of dynamic property ProjectSend\Classes\Users::$contact is deprecated in
/var/www/vhosts/download.mywebsite.com/httpdocs/includes/Classes/Users.php
on line
211


Deprecated
: Creation of dynamic property ProjectSend\Classes\Users::$file is deprecated in
/var/www/vhosts/download.mywebsite.com/httpdocs/includes/Classes/Users.php
on line
222`

**Comment by protego-it** [comment]
Ok, this was the error messages for the dashboard.
When I directly go to manage-files.php I get a better error message.

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 102400 bytes) in /var/www/vhosts/download.mysite.com/httpdocs/vendor/claviska/simpleimage/src/claviska/SimpleImage.php on line 159

So I guess SimpleImage.php can't handle the memory. Weird part is that I did not update the memory settings and a few days ago everything was working fine.
What is the recommended Memory size for the PHP settings?

![image](https://github.com/projectsend/projectsend/assets/59828196/60056f74-3743-4cdd-a608-25c408e70884)

Edit: My Server is running on 2GB RAM.

**Comment by protego-it** [comment]
Ok, I could solve the problem now.
A user uploaded several images over 50MB. This should work, because we're far ahead of my 1GB limit, but anyhow, SimpleImage.php couldn't handle it and ran into error 500.
I removed the Images from the upload folder and afterwards from the now working manage-files.php list.

Thanks again, for pointing out the Debug function.
