### ISSUE TITLE
Development Lifecycle / Release Schedule

### ISSUE THREAD

**Issue by StarkZarn** [projectsend/projectsend#1304]
Do you have a published project development lifecycle and/or release schedule anywhere? I like this project, but it looks like the last official release was over a year ago and there are lots of open issues. With some of these things being dependency updates to address security vulnerabilities, it's important for me to understand expected dev pace and product lifecycle before adopting a new stack like this project. Thanks!

**Comment by sephentos** [comment]
No update for 1.5 years. The project is pretty much dead unfortunately.

**Comment by ignacionelson** [comment]
Sorry it might seem that way. Most of my time dedicated to PS went to support for the last year, and personal issues made that available time less than before. I still work on the app, sorry for not updating often!

**Comment by StarkZarn** [comment]
It's free and open source, and not your main thing, I get it. Happy to just have a response here. Keep doing your thing, we appreciate the work you do have time for here!

**Comment by iincitr** [comment]
Again thank you for making and continuing  ProjectSend application.
