### ISSUE TITLE
Status of the Project

### ISSUE THREAD

**Issue by fdefilippo** [projectsend/projectsend#1305]
Hello everyone, I'm reaching out to inquire about the current status of the project. Is it still active and under development, or has it been discontinued? Any updates or information would be greatly appreciated. Thank you.

**Comment by ignacionelson** [comment]
Hi! I'm always working on it. Lately it has been hard to find the time to code due to personal issues and the general economic circumstances of where I live which required me to get more work as freelance. Most of the time I dedicate to the project goes into support. but I hope that can be reverted soon. Thank you for your interest in PS!

**Comment by fdefilippo** [comment]
I have a list of security vulnerabilities, how can I contact you?

**Comment by rob4226** [comment]
> Hi! I'm always working on it. Lately it has been hard to find the time to code due to personal issues and the general economic circumstances of where I live which required me to get more work as freelance. Most of the time I dedicate to the project goes into support. but I hope that can be reverted soon. Thank you for your interest in PS!

> Hi! I'm always working on it. Lately it has been hard to find the time to code due to personal issues and the general economic circumstances of where I live which required me to get more work as freelance. Most of the time I dedicate to the project goes into support. but I hope that can be reverted soon. Thank you for your interest in PS!

@ignacionelson Just want to say thank you for keeping this awesome project alive!  It works really well, has great features, and looks really nice. Keep up the great work!!

**Comment by gravelfreeman** [comment]
Yeah this project is awesome, hope it'll keep being dev.

**Comment by ignacionelson** [comment]
Just released a new version. Thank you everyone for your support!
