### ISSUE TITLE
"View my files" page for Clients uses HTTP, fails when site uses HTTPS

### ISSUE THREAD

**Issue by vjp23** [projectsend/projectsend#1316]
Hi all, I've setup Projectsend using Docker and Caddy as a reverse proxy.

I set the site location to use HTTPS (SSL) in the System Location under General Options, and that fixed issues related to cross-site loading of CSS.

However, I noticed that when I setup new Clients, they log in and are then directed to a mostly blank page (see screenshot). The hamburger button to open the navigation bar does not function, and the console suggests that loading from Google Fonts and the jQuery library are blocked by Caddy because they use HTTP. This then causes the jQuery used to load the menu to fail.

How might I address this?

Thanks!!
<img width="880" alt="Screenshot 2024-05-13 at 5 17 21 PM" src="https://github.com/projectsend/projectsend/assets/20172859/e489f393-9f6e-4d05-b8b0-c2ac4785c17a">

**Comment by ignacionelson** [comment]
Should be fixed on be88e49 by including jquery locally
