### ISSUE TITLE
ProjectSend appears to be displaying php code instead of executing so we are seeing php code instead of the login page.

### ISSUE THREAD

**Issue by jjmacneil** [projectsend/projectsend#1323]
It appears PHP was updated to 8.1.2 and users can no longer login as the PHP code is being displayed instead of the login page.

I'm not sure how to revert back to a previous version of PHP as the Ubuntu server shows 7.4 and 8.1 as being installed.

**Comment by ignacionelson** [comment]
Hi. I've tested 8.1 and there are a few bugs but PS still works. It seems that your server is serving php files as plain html, not running them through php. I would contact customer support in this case. Hope that helps!

**Comment by serg499** [comment]
I'm using PHP 8.2.20 - working fine, so 8.1.2 shouldn't be an issue.

**Comment by jjmacneil** [comment]
Thank you for responding! Are you running on Ubuntu and using MySQL for database?On Jun 24, 2024, at 1:43 AM, serg499 ***@***.***> wrote:﻿
I'm using PHP 8.2.20 - working fine, so 8.1.2 shouldn't be an issue.

**Comment by ignacionelson** [comment]
Any update? Closing for now as this seems to be a server side error, not specific to PS
