### ISSUE TITLE
Column 'expires' cannot be null but MySQL does have already default value set

### ISSUE THREAD

**Issue by leleobhz** [projectsend/projectsend#1338]
Hello!

While a user edit comments for a file, this error happens:

```
Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'expires' cannot be null in /var/www/html/includes/Classes/Files.php:955 Stack trace: #0 /var/www/html/includes/Classes/Files.php(955): PDOStatement->execute() #1 /var/www/html/files-edit.php(72): ProjectSend\Classes\Files->save(Array) #2 {main} thrown in /var/www/html/includes/Classes/Files.php on line 955
```

When we look at https://github.com/projectsend/projectsend/blob/r1720/install/database.php#L49, default value is handled by database, but even https://github.com/projectsend/projectsend/blob/r1720/includes/Classes/Files.php#L917 defaulting to 0, https://github.com/projectsend/projectsend/blob/r1720/includes/Classes/Files.php#L950 is checking if its not null and triggering the error at https://github.com/projectsend/projectsend/blob/r1720/includes/Classes/Files.php#L955

What needs to be fixed to handle this properly?

**Comment by leleobhz** [comment]
Note: This only happens if client is not able to edit expiration date. If I enable it, even if client does not check expire box, it works. 

Projectsend must set expire as the default expire explictly when user does not have permission to change expiration.

**Comment by toxygen** [comment]
I can confirm that I experience the same issue.

**Comment by toxygen** [comment]
I created pull request to fix this bug.
