### ISSUE TITLE
HTTP Error 500 when logon as client 

### ISSUE THREAD

**Issue by Diktiorwalle** [projectsend/projectsend#1356]
Hi,
 
I have just upgraded to version 1720 from 1335.

I have an issue when after logon as a client.

he error I get wright after logon is:

/my_files/index.php

HTTP ERROR 500

I am running:

System information
Software
Version
r1720
Default upload max. size
2048 mb.

System
Server
nginx/1.24.0

PHP version
8.3.6

Memory limit
128M
Max execution time
14400

Post max size
8M

Database
Driver
mysql
Version
10.11.8-MariaDB-0ubuntu0.24.04.1

Help is greatly appreciated. 

Kind Regards,

Rob

**Comment by Diktiorwalle** [comment]
just turned on debug:

**Before in logon as a client:**

Warning: Undefined array key "type" in includes/functions.php on line 1433

Warning: Undefined array key "type" in includes/functions.php on line 1435

**After I logon as a client:**

Warning: preg_replace(): Unknown modifier '\' in includes/Classes/i18n.php on line 308

Fatal error: Uncaught Error: Call to undefined function ProjectSend\Classes\create_function() in /

includes/Classes/i18n.php:353 Stack trace: #0 

/includes/Classes/i18n.php(270): ProjectSend\Classes\I18n::GetPluralFunc() #1 /includes/Classes/i18n.php(172): 

ProjectSend\Classes\I18n::ParseFile() #2 /includes/Classes/i18n.php(94): ProjectSend\Classes\I18n::LoadFile() #3 /includes/

functions.templates.php(171): ProjectSend\Classes\I18n::LoadDomain() #4 /templates/common.php(23): template_load_translation() #5 /

templates/default/template.php(20): include_once('...') #6 /my_files/index.php(12): require('...') #7 {main} thrown in includes/Classes/

i18n.php on line 353

**Comment by Diktiorwalle** [comment]
Just went back to version 1335. Here I don't have an issue. It is working again. 

Where does it goes wrong?

**Comment by Diktiorwalle** [comment]
Hi, 
Reinstalled version 1720 with a new database. I don't have this issue anymore. 

Kind Regards,
Rob

**Comment by pietervanuhm** [comment]
Installing with a new database (empty?) doesn't look like the right solution if you have a lot of data?
