### ISSUE TITLE
import user table to new installation?

### ISSUE THREAD

**Issue by rcs27** [projectsend/projectsend#1365]
Hi Ignacio,

We started a fresh installation, the only data we will like to transfer over from the old installation is the users, if we import the user table, do you know if it works? or do we need to transfers another table beside the user table?
we have over 500 clients, and create one by one is a long process.

**Comment by ignacionelson** [comment]
Hi! It should work just fine if you import that table only :)

**Comment by rcs27** [comment]
Thank you. It worked just fine.
