### ISSUE TITLE
Large Files > 2 GB?

### ISSUE THREAD

**Issue by Ideawmx** [projectsend/projectsend#137]
Hola!

I have ProjectSend (r608) installed in a shared web hosting server and I'm currently facing Issues with download times, taking hours to download a 2-3 GB file.   Project send was suggested to manage large files (Audo / Video) for non technical users.  I'm using it to send / receive files between cities between different people and organizations (Just to clarify that users and clients aren't on same network LAN / VPN, MAN, WAN)   ProjectSend is installed on a Linux Server.

I've revised some server stats and it's resources has been spiking trough the roof because download processes take lot's of server's I/O Usage, memory usage.. 

Attached some Usage graphs

![image](https://cloud.githubusercontent.com/assets/7599804/17127023/fbadac70-52c7-11e6-889b-c0a70239a53c.png)

Please advise on a posible fix / is this a bug? or I'm completely mistaken of what ProjectSend was meant for?

Thanks.

**Comment by ignacionelson** [comment]
Hola! Gracias por el reporte. Sigo en inglés :)

To be honest, this is the first time that I see this kind of problem with PS.
Can you please post what your server's resources are? Thanks!

**Comment by Sitmex** [comment]
Gracias...
Most recent stats (Jul 25th)
Time	Percent Usage	Heaviest Process
0:00 - 03:00	1.52	php-cgi
3:00 - 06:00	None	None
6:00 - 09:00	1.52	php-cgi
9:00 - 12:00	50.00	php-cgi
12:00 - 15:00	4.55	php-cgi
15:00 - 18:00	4.55	php-cgi
18:00 - 21:00	21.21	php-cgi
Recent	16.67	
-------------------------------
Memory Usage	 0 / 2048 MB
Physical Memory Usage	 0 / 1024 MB
Entry Processes	0 / 40
Number of Processes	0 / 100
I/O Usage	0 / 1024 KB/s
IOPS         	0 / 1024
Disk Space Usage 57.42 GB / ∞
Monthly Bandwidth Transfer	 106.23 GB / ∞

Hope those made sense...

**Comment by crashff00** [comment]
What is the web server software in use? Some web server software experiences a memory leak when using FastCGI for sending out large files

**Comment by Sitmex** [comment]
Shared Server ; CloudLinux Server release 6.8

PHP 5.6.24  Libraries
bcmath, bz2, calendar, Core, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, htscanner, iconv, imap, intl, ionCube Loader, json, libxml, mbstring, mcrypt, mhash, mysql, mysqli, mysqlnd, openssl, pcre, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, Reflection, session, SimpleXML, soap, sockets, SPL, sqlite3, standard, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib,

**Comment by Sitmex** [comment]
Any news or discoveries?

**Comment by crashff00** [comment]
I have noticed that every file over 2GB now shows a ? for file size.

**Comment by ignacionelson** [comment]
This should be fixed with the latest commits.

**Comment by ignacionelson** [comment]
r1265 has support for XSendFile, which bypasses php for file downloading. Requires a module on the server, but fixes the issue and adds resumable downloading too.
