### ISSUE TITLE
2-factor authentication

### ISSUE THREAD

**Issue by Diktiorwalle** [projectsend/projectsend#1373]
Hi,

I would like to know how I can reset 2-factor authentication when the email system doesn't work and cannot send verification codes. In this case I would not be able to logon as a system user and deselect disable 2-factor authentication. Is there a file which a can edit manually and disable 2-factor authentication and logon again. 

Kind Regards,

Rob

**Comment by raducode** [comment]
Hi! In the database, the table where the 2FA is enabled is under `tbl_options` name of the param is `authentication_require_email_code `and set it to `0 to disable `2FA, and `1 to enable 2FA.`

**Comment by Diktiorwalle** [comment]
Hi thanks a lot,

Just tested it and it works.

Great thanks

Kind Regards,

**Comment by ahmed-raza-siddqui** [comment]
For Anyone wondering, you can use the following SQL query to update the param

`UPDATE tbl_options SET value=0 WHERE id=128;`

You should see the following message if the query was successfully executed 

```
Query OK, 1 row affected (0.003 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```

You can also use the query to verify if it was updated successfully ! 

` SELECT * FROM tbl_options WHERE name='authentication_require_email_code';`

Sorry I know these are basic SQL queries, but I don't work with SQL queries, so I had to look it up. Might as well help someone else ! :) 

Thanks once again guys !
