### ISSUE TITLE
Changed the table with the defined constant

### ISSUE THREAD

**Issue by raducode** [projectsend/projectsend#1377]
https://github.com/projectsend/projectsend/blob/bcd7e0809565dd386681d3647a9acb844f5f3483/includes/Classes/Folders.php#L218

Should be 
`        $query = "SELECT level FROM " . TABLE_USERS . " WHERE id = :user_id";
`

**Comment by ignacionelson** [comment]
Fixed on 311098be5a06ec3a4cbb733d1ef790f885795cc2
Thank you!
