### ISSUE TITLE
R1605 - Upload file button missing

### ISSUE THREAD

**Issue by qtmgit** [projectsend/projectsend#1381]
Hi, I have projectsend version r1605 which has been working well for some time, however I now have a problem where users cannot upload files as there is no UPLOAD button.  This has disappeared for all clients/logins and as far as I can tell there have been no changes to the server which is running Ubuntu 20.04.6.
Downloads work fine.
Any help greatly appreciated

**Comment by qtmgit** [comment]
I think someone has gained access to my system and changed the setting that allows uploading of files.
Not sure how a user can self register if the option to self register is disabled

**Comment by tomvanveen** [comment]
Because of https://www.synacktiv.com/sites/default/files/2024-07/synacktiv-projectsend-multiple-vulnerabilities.pdf
