### ISSUE TITLE
Feature request: generate random/unique share link for public download

### ISSUE THREAD

**Issue by kt1024** [projectsend/projectsend#142]
like: http://server/cw1xa2
1. links can be generate for specific file or folder.
2. for public access. (no login required)
3. links can be protected by simple password, like 4 digit length. (option, generate with the unique links)
4. share links can be removed (manually and scheduled period, or after specific download counters reached)

BR.

**Comment by Gerasch** [comment]
+1 - could you add this feature? This would be very nice and PS will go a big step forward to be a very cool and convenient application! :)
