### ISSUE TITLE
New file uploaded by clients email

### ISSUE THREAD

**Issue by rodsco** [projectsend/projectsend#147]
609
When a client is created and authorized using the self 'Register new account' method notificiation of uploads by the user work as they should.

If the client is manually created no new upload emails for that client are send.

Tried on 611 with the same problem

**Comment by lenamtl** [comment]
What do you mean manually created : direct in DB or using the backend form?

**Comment by rodsco** [comment]
From the backend form - logged in as a system user.

**Comment by rodsco** [comment]
Actually Ive just read my post.  Its actually the other way round....

Emails are ok with manually created accounts, but not with self registered.

Sorry ... its been a long day :)

**Comment by lenamtl** [comment]
When creating the user is it a part of a group or not?
Does the file is for single user or a group?
Do you see any error?
Does the email address is saved correctly in DB, have you check if email spam folder...

I know that there is a function that will try to send the message even if it's failed the first time (there is an option for this in Options page)

**Comment by rodsco** [comment]
The user not part of any group.
File is not for any user - it is just uploaded by the user. (idea being that a sys admin can then access the file)
There are no errors and the green 'email has been sent bar appears'
Email address correct in the db and the 'Welcome to Project Send' email gets to the user after the account has been authorized.

I should clarify that it is the notification to the System Administrator that is not being sent.

**Comment by crashff00** [comment]
I think this may be tied to the same problem with account creation. The user is getting their email, but the admin and any additional copies specified in the configuration are not.

**Comment by lenamtl** [comment]
Could you set a case step by step so we can try to reproduce
