### ISSUE TITLE
Feature Request - Ability to allow Specific clients to upload

### ISSUE THREAD

**Issue by tsumaru720** [projectsend/projectsend#16]
This is a feature request. 

By default I have client uploading disabled but I have a need where one or two are required to upload. Current options mean its either globally enabled, or globally disabled.

Would be nice if you had the option to enable it on a per-user basis

**Comment by lenamtl** [comment]
+1

**Comment by imc-zk** [comment]
+1 

We have the same feature request.

For us, it would be enough on a per user base.

**Comment by madman2021** [comment]
+1

**Comment by virtualized-human** [comment]
+1

its very usefull.

**Comment by ignacionelson** [comment]
Well.... took me long enough :D
Here it is!
51e0d74
