### ISSUE TITLE
Suggestion: Force users/clients set their own password on first login

### ISSUE THREAD

**Issue by Joohansson** [projectsend/projectsend#161]
An admin should never really have to set a password for a new user. Sending a password via email is not just insecure, it's lowering the trust level for new clients who's not familiar with the system. Projectsend hashes all password which is good but client don't know that. NEVER trust a service that re-send your password in clear text (not hashed in database!). I also think the password min length should be an admin site option but forced by code to be at least 5 characters even for admin (8 if I was to decide).
## Suggestion fix:

**A - Best option, most common, but heaviest for devs:**
1. Do not set a password, do not activate account
2. Send account activation link (expires after 24h) with welcome email
3. User set the password from unique one time link.
4. Account activates. User can log in
5. If not done in 24h, give user option to re-send activation link

**B - Easier but less secure option:**
1. System automatically sets a long random password
2. Send password along with welcome email
3. User is forced to change password on first login

**C - Utilize existing features (Good enough I think but not perfectly user friendly):**
1. Admin choose a password (very long for high security)
2. Password is NOT sent with welcome email but instead a password reset link (or separate reset email)
3. User has 24h to reset its password, or go to login page and make another reset request. User cannot login until this is done.

**Comment by lenamtl** [comment]
What you can do with actual system admin create an account, user request for a PW reset.

Or user on first login enter a temporary pw  then he need to change the password during the first login to complete the process.

**Comment by Joohansson** [comment]
This is my current simplified workflow for creating new clients/users (with implemented code):

1. Create client: Only name and email needed. System generates password and request token
2. Client gets welcome email with username and password request link
3. Client choose a password, go back to login page and login
![ps1](https://cloud.githubusercontent.com/assets/2406720/18081286/b3d3e444-6e99-11e6-96ed-3c746fc36012.JPG)
![ps2](https://cloud.githubusercontent.com/assets/2406720/18081285/b3cfc7ba-6e99-11e6-96e5-a091f4f1f772.JPG)
![ps3](https://cloud.githubusercontent.com/assets/2406720/18081288/b3d75408-6e99-11e6-9afd-8dae50e4bdb7.JPG)
![ps4](https://cloud.githubusercontent.com/assets/2406720/18081287/b3d4349e-6e99-11e6-8ce5-34bcf8dd34fd.JPG)

**Comment by lenamtl** [comment]
Hi, do you have a batch tool script to set dummy pw for new user?

**Comment by manoocher** [comment]
> This is my current simplified workflow for creating new clients/users (with implemented code):
> 
> 1. Create client: Only name and email needed. System generates password and request token
> 2. Client gets welcome email with username and password request link
> 3. Client choose a password (or generate one), go back to login page and login
> 
> 1
> ![ps1](https://cloud.githubusercontent.com/assets/2406720/18081286/b3d3e444-6e99-11e6-96ed-3c746fc36012.JPG)
> 
> 2
> ![ps2](https://cloud.githubusercontent.com/assets/2406720/18081730/e04087e2-6e9b-11e6-8283-f8a9df53c8a5.JPG)
> 
> 3
> ![ps3](https://cloud.githubusercontent.com/assets/2406720/18082832/db3e913a-6ea0-11e6-90f8-9e2efe465016.JPG)
> 
> 4
> ![ps4](https://cloud.githubusercontent.com/assets/2406720/18081287/b3d4349e-6e99-11e6-8ce5-34bcf8dd34fd.JPG)

This is actually good solution, can you tell me what you have changed in code? how it comes that the %URI% tag is the same for new user and reset password email templates, but they will have different values? 
Thank you,

**Comment by ignacionelson** [comment]
Added on r1265
