### ISSUE TITLE
Have translations use sprintf instead of separating the sentence on every variable

### ISSUE THREAD

**Issue by ignacionelson** [projectsend/projectsend#180]
This would make some of the already translated strings on Transifex obsolete, but it was a mistake to separate phrases into different smaller ones. Out of context some of them don't make sense, and syntax in languages other than English certainly prove that this was bad practice.

**Comment by lenamtl** [comment]
Yes that's right specially for french 
also I do prefer to use plain string maybe you could reconsider using another method
I hate using PO file as it's not easy to add new strings we have to scan to add new string and this is also complated with latin as ' will cause crash we have to use ’ and sometimes because using special characters and accent see

**Comment by ignacionelson** [comment]
I get your point. Before using gettext, each string was on the includes/vars.php file.
I decided to change it to the gettext .po/.mo method as to make it easier for everyone to collaborate, and to attend to the standards.

Also, the first scans were made with the online tool by icanlocalize.
But a few days ago I re-created the .pot by scanning the files with poedit. It made it VERY easy to add new strings now, as you only need to open the file and re-scan the directory.
The only step needed after that is re-saving as en.po/.mo and uploading the new file to transifex.

The ' problem is only on PS or have you ever faced the problem with other software too?
It doesn't seem like it would be hard to fix, if it is happening on PS only.

**Comment by lenamtl** [comment]
I never use PO except with PS

**Comment by lenamtl** [comment]
Also when using complete sentence this prevent problem with plural word.
