### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by RM4G00** [projectsend/projectsend#187]
Centos7 - latest version of Projectsend - email notifications dont work - could someone please give a newbie a guide for this as I've found nothing so far.. all methods fail - successfully sent - but no delivery to  anything.

**Comment by ignacionelson** [comment]
Oh :(
Have you tried using SMTP to send the emails?

**Comment by RM4G00** [comment]
Hi, 

I have tried all- had some colleagues have a look - tried even GMAIL 

Can you confirm any steps I could use to setup a basic SMTP to anything - I really want our business to try this. 

Regards, 

Ross Mulgrew 

Systems Administrator | Allied Vehicles Ltd |230 Balmore Road | Glasgow, Scotland 
Ext:1028 - DDI 0141-336-1028

**Comment by RM4G00** [comment]
?

**Comment by StevieTrance** [comment]
I have the same issue, none of the email configs yield a response via email

**Comment by RM4G00** [comment]
Can anyone with working mail config post a how to? or offer advice,

Thanks

**Comment by lenamtl** [comment]
Are you using other web application that send mail on this server?
Just to make sure that this working ok on your server.
If no email sent from any web application  on your server check on Centos forum

**Comment by RM4G00** [comment]
Hi, I've configured a test php mail from the root - it works fine- from Projectsend nothing, Can you tell me what file I need to edit to get this working?

**Comment by RM4G00** [comment]
Any help at all? slowly loosing interest in this now.

**Comment by lenamtl** [comment]
You tried a mail script in the root did you tried it at at the same level of PS to see if it's still work ?
Which PHP version are you using?

It is more a server configuration issue, something prevent notification to be sent ..
It's hard to say what cause this exactly. Maybe check the php and apache logs, ask help on Centos forum...

**Comment by JWT007** [comment]
I am a new user and am also having a email problem.

I have a hosted server with an outgoing SMTP relay on Port 25.  There is no username or password required for this SMTP server... which may be the problem if the PHP script is expecting them.
