### ISSUE TITLE
Adding a file that existed before doesn't save as new entry on DB

### ISSUE THREAD

**Issue by ignacionelson** [projectsend/projectsend#195]
Strange issue.
If a file exists on the database (TABLE_FILES) but NOT on the disk, and you upload a file with the same filename, when saving a new entry is not created. Instead, the old one is kind of overwritten (no info is saved)

**Comment by lenamtl** [comment]
In which case this can happen using the system ?

**Comment by crashff00** [comment]
My users tend to do this often because they ignore instructions:
Upload file via ftp,
add to database,
discover file was wrong version and delete through ftp
upload new file with same name, but different file size/dates.

**Comment by lenamtl** [comment]
Ok that's what I thought it happens only if files are added or deleted manually with FTP.
This cannot happens if they are uploading using the system!?
