### ISSUE TITLE
Add all selected files to categories

### ISSUE THREAD

**Issue by SpudR** [projectsend/projectsend#197]
I'm liking the new categories feature - but it's a pain to add existing files to new categories.
Can you please add a function to the drop down box in the mange files section (where it currently says 'delete'), to read 'Add all selected to category' [or something like'.

This would greatly help!

**Comment by lenamtl** [comment]
+1
I agree

**Comment by SpudR** [comment]
Any movement on this??

**Comment by zackrspv** [comment]
+1 - I agree as well - managing files (as users cannot manage their own categories yet) is tedious if you have multiple files. We should be able to select multiple as admin, and choose if it's public, or belongs to a category.

**Comment by ignacionelson** [comment]
While it cannot be done from the manage files page, you can now edit multiple files at once (since r1265)
