### ISSUE TITLE
Select number of files to show on list

### ISSUE THREAD

**Issue by SpudR** [projectsend/projectsend#198]
It would be great to be able to select the number of files in a list instead of the current 10.

**Comment by lenamtl** [comment]
+1

**Comment by SpudR** [comment]
Understood, but adding a dropbox with options would be useful :)

**Comment by ignacionelson** [comment]
Oh, right now the number is just for aesthetics and usability motives. Performance is bad since everything is loaded on the page, not just the results that are shown.
This is on the TODO list for the next version.

**Comment by SpudR** [comment]
Thanks :)

**Comment by lenamtl** [comment]
wow I just test my installation have 2K file and it's load forever....
I have to check my very old PS version hack, because it was not that bad.

I can use it on production because of that

**Comment by SpudR** [comment]
lol
I'd suggest just adding a dropbox with multiples of 10, or a spinbox for a finite number :)

**Comment by SpudR** [comment]
Any idea when this might be added?

**Comment by ignacionelson** [comment]
This is defined on a constant and used system-wide. I will add an option to override that value in the options panel.
