### ISSUE TITLE
I need filter files by group on manage-file.php for clients

### ISSUE THREAD

**Issue by lenamtl** [projectsend/projectsend#210]
I'm using group as company name
so a client can be a part of one or several group (company)
and there is no way to filter by group on manage-file for client, even for system user....

I need it urgently, anyone have done that?

Have a column in the table for group and for category maybe also useful

**Comment by ignacionelson** [comment]
Do you need this on the admin page? Not on a client's template?

**Comment by lenamtl** [comment]
I mostly need filter by group on Client template 
but also need filter by category and group on admin 
This will be great

**Comment by ignacionelson** [comment]
Files can be filtered by client now
