### ISSUE TITLE
When uploading the system don't warn that file already exists

### ISSUE THREAD

**Issue by lenamtl** [projectsend/projectsend#218]
When uploading the system don't warn that file already exists
It's will rename the file silently _1 _2 so on.

Maybe this could be a good to warn the uploader that this file name already exist  in the upload page so uploader can decide yes upload and renamed or cancel the upload for this file.

Having duplicate can be confusing, plus it will take more space on disk for nothing.

**Comment by ignacionelson** [comment]
Files are now renamed with a random token to ensure that they don't get overwritten.
