### ISSUE TITLE
Notice and fatal error on edit file when adding category

### ISSUE THREAD

**Issue by lenamtl** [projectsend/projectsend#229]
On edit file when adding category

`( ! ) Fatal error: in ...projectsend\includes\classes\actions-log.php on line 129
( ! ) PDOException: in ...projectsend\includes\classes\actions-log.php on line 129
Call Stack
    Time    Memory  Function    Location
1   0.0020  361792  {main}( )   ...\edit-file.php:0
2   0.2150  3763120 LogActions->log_action_save( )  ...\edit-file.php:306
3   0.2190  3772144 execute ( ) ...\actions-log.php:129`

**Comment by ignacionelson** [comment]
No longer see this issue in the latest release. Marking as solved
