### ISSUE TITLE
Suggestion: Version verification should be a configuration option

### ISSUE THREAD

**Issue by lenamtl** [projectsend/projectsend#23]
Version verification should be a configuration option = yes or no
So it will prevent to check version and display the message.

**Comment by ignacionelson** [comment]
Do you think the message is too agressive?
Each new version usually fixes security bugs, so I believe updating is always important and the users should be reminded of it.

**Comment by lenamtl** [comment]
No and I agree that it is important to know it.

I have two reasons for this.
1- It's take some bandwidth when it's checking the version, and errors may occurred if a connexion to the site fails. 
2- I don't want the enduser make an update himself (I have a lot of custom code).
    I don't want the enduser to be in panic mode because of this message.
   (as it is a customized version, it will took me some time to update the code) and in any case I always   
   test the application again before putting the new version online.
   
I will removed this feature from the code, so I was thinking that we can make ON/OFF to keep the code in place if needed.

**Comment by mschop** [comment]
1 - The bandwidth is negliable. This is no reason.

This is a feature, the broad amount of ProjectSend users do not need. Therefore I close this issue. I would suggest waiting for the planned plugin system and then create a custom plugin.

**Comment by lenamtl** [comment]
1- if error occurs when checking this can make a loop...

2- I still think that user should not see it, so at least this should be displayed depending of role, let say display it only to super admin.

I have removed it from the code so it's not checking, but that can be useful just to have an option for it.
So this way less  core modification.
