### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by sheldonau** [projectsend/projectsend#230]
We only get email notifications when a new user is created, both the Admin user and Client gets the email fine. 

However, when we upload new files, neither gets the email even though we selected to send the email. 

Tried Sendmail, PHPMail, SMTP, all didn't work. 

Thanks in advance!

**Comment by lenamtl** [comment]
What have you set in options about how many time the system will try to send?

**Comment by rcs27** [comment]
Try this, https://github.com/ignacionelson/ProjectSend/issues/527

**Comment by ignacionelson** [comment]
Solved in r1265
