### ISSUE TITLE
Can't Edit Multiple Files at one time

### ISSUE THREAD

**Issue by savagela** [projectsend/projectsend#231]
When I want to edit 10 files, I have to click Edit for each one.  

But when I upload 10 new files,  I'm given a page with all 10 files on it, and I  can edit them all at the same time. 

I would like to be able to click on 10 files, choose Edit in the selected files actions and click on proceed.  This is very important because I may want to give someone access to 50 files, or create a new category or Group with 100 files in it. It's impractical to have to do it one by one.

**Comment by ignacionelson** [comment]
Yes, it's far from being usable in that aspect.
I'll soon be rewriting the upload and editor so they are the same thing, and files can be batch edited.

**Comment by savagela** [comment]
I am wondering if there has been any progress on this enhancement?  I would be very grateful if you make the change.  
I use the program almost every day at work and this is one of 3 issues that spoil the fun.

**Comment by blitzking** [comment]
Please consider this as a critical enhancement. I use the system basically 5 days a week and find that a lot of my time is spent editing files individually and then hitting the back button after each one. 

Has there been any progress on batch file editing? Perhaps in the interim, can there be an automatic redirect to the file list after editing a file and clicking"Continue"? That would a tremendous time-saver! Thanks for all your hard work!

**Comment by ilackskills** [comment]
@blitzking Why would this be considered a critical enhancement because you are in need of it?  As far as your redirect goes...read here

http://stackoverflow.com/questions/2548566/go-back-to-previous-page

**Comment by savagela** [comment]
Hello @ignacionelson - Has there been any progress on this enhancement?  

Monday a client uploaded 87 files, which mixed with the 18 files he already had,  and the client was mad he couldn't find anything. 

My co-worker & I  decided to create a separate Upload account, but I don't relish transferring all 87 files,  one by one, before deleting them from the main account.  I would like to click on all 87 and put in their destination once. 

If we had folders, we could put all uploads in a folder and the main account would be usable again. 

@ilackskills if you have any suggestions, please let me know. 

Thank you for this program. We really find it useful.

**Comment by ignacionelson** [comment]
Hello @savagela 
This is on the works but sadly not close to done yet. I wish I could dedicate more time to PS but I tend to go into/off it often as I juggle it with my job.
I'm hoping to get a break next month to advance on the project. This change is one of the priorities :D

**Comment by savagela** [comment]
@ignacionelson 
I'm grateful for what you have done. And I'm always impressed how responsive and positive you are. Thank you.

**Comment by knutmeyn** [comment]
Hi there

Great app and service! 

any news on batch update function? 

Rgds

**Comment by NaughtyGoose** [comment]
Hmm, just installed ProjectSend and regretfully uploaded 600pics .... they ended up with the status "orphaned" ... and it seems I will have to edit EACH of them manually ... any progress on the "bulk action" for files? Elsewise deinstalling the program will be easier and quicker than adding status of each file ...

**Comment by ignacionelson** [comment]
@NaughtyGoose Sorry about that :( I've been having issues implementing the bulk edit function on the current branch. Is there anything in common that you need to apply to all files?

**Comment by NaughtyGoose** [comment]
Hi Ignacio, thanks for your answer! Actually I just needed to get them out of the "orphaned child" state ... But deinstalling the app with all data solved the problem ;-). But I guess adding a bulk editing feature would be an important step forward.
Cheers, Timo

**Comment by ignacionelson** [comment]
Solved in r1265. Multiple files can now be edited at once
