### ISSUE TITLE
New string are not found in the default.pot

### ISSUE THREAD

**Issue by lenamtl** [projectsend/projectsend#249]
I'm trying to update the french file using the default.pot but new sting are not found.
I'm looking for the word **Found** that appear when searching on the list since the new pagination.

These need to be update in PS package and Transiflex too.

As a temporary solution we can scan the project with Poedit https://poedit.net/
Open the .pot file with Poedit / Catalog / Update from source
Save
Open your language file then Poedit / Catalog / Update from POT file
Save
Then translate the empty strings (View order by translation) 
Save
File / Compile to MO

Don't forget to update template language file too.

**Comment by ignacionelson** [comment]
r1265 includes all available texts in the pot file
