### ISSUE TITLE
Role suggestion for uploader account with lesser rights or (vice versa) clients with more rights

### ISSUE THREAD

**Issue by MHerrERC** [projectsend/projectsend#254]
Hello,

first I´ve to thank you for your great work with ProjectSend. After running into some issues (solved by not taking the newest php-version), we´re using your great tool, to exchange files with a lot of customers.

This is our typical use case:
We´re a small company with many different projects and different customers.
A customer uploads files. Because the uploader account can see all client accounts and categories, when managing his files, customers only got normal client accounts.
After uploading his files, a system administrator assigns all uploaded files to project team members of our company (which is not quite a lot of fun, if there are many files).

In progression of issues 75, 161 and 231, we´re thinking about some enhancements for your great tool to make things much easier.
We´d love to use the uploader account for our customers, but for our needs (as described above), this account has to much rights. We´ve to ensure, that a customer can´t see the all the other customers. The new categories have the identical problem, when we´d use them, to categorize the uploaded files by different projects.
This could be solved by creating a kind of uploader account, who can only assign and categorize files to users, groups and categories, we´ve assigned to him. Supplemental to this, it could be possible tio generally redesign the client accounts, allowing them to assign and categorize their files to predefined groups and categories.
As our project team members mostly work in more then one project at a time, it also would be helpful, when user accounts can see the categories, files are assigned to.

We also would appreciate, if there can be an option, that clients can get an email notification too, when they have uploaded files. It would be used as additional confirmation for successful uploading his files.

From point of view of security, we also would appreciate the possibility to force our customers, to choose a new password at their next login. Normally we create an user account (no self registration allowed right now) and the clients get the automatic email with username, password and the request for changing their passwords. As we all know, most of them didn´t change the password ever.

Best regards
Markus Herrmann

**Comment by ignacionelson** [comment]
Password change required can be selected now. New roles are ATM too complicated to apply. Closing
