### ISSUE TITLE
Delete all orphan files

### ISSUE THREAD

**Issue by uussaammaahh** [projectsend/projectsend#279]
Just a button to delete orphaned files which are checked OR delete all orphaned files button.

**Comment by lenamtl** [comment]
+1

**Comment by dannyulman** [comment]
+1
because as of now the only way to delete an orphaned file is to assign it first before it can be deleted

**Comment by jcgmed** [comment]
Orphan files are stored in upload/files, get there and delete what you need.

**Comment by rose-a** [comment]
👍

**Comment by SnowCreative** [comment]
Any progress on this? It's a pain to have to import all the orphaned files and then go delete them from the main file list.

**Comment by ignacionelson** [comment]
This is now available since r1584
