### ISSUE TITLE
Problem downloading files

### ISSUE THREAD

**Issue by davidsan14** [projectsend/projectsend#291]
Hello,
I have a problem that has come from one day to another. I have tried various things but it doesn't work anyway.
When I try to download a file, it begins to charge the webpage but it remains there and the file doesn't download.
This url doesn't work: 
http://website/clientesxxx/process.php?do=download&client=user&id=1&n=1

I don't know why this fails now, I didn't touch nothing from the server. I tried to solve it installing a newer ProjectSend version but it still doesn't work...

Any help would be gratefully received.

Thanks.

**Comment by lenamtl** [comment]
This is mean that something have change on your server PHP version may have changed or BD.
Checked with your hosting company and ask them what they have changed since the day you started having problem.
