### ISSUE TITLE
Categories and Filter

### ISSUE THREAD

**Issue by tmaster100** [projectsend/projectsend#292]
Hi,

Is there a way to create categories on the main page and then upload respective files under each category? 

Right now you create categories but when you upload files they are all together unless you use the filters etc.

Example : 

Category 1 
  ---> test file
  ---> test file 2

Category 2
 ---> test file 3
---> test file 4

Cheers.

**Comment by asba79** [comment]
I second this. Having the categories behave as folders, or have support for folders, would be really nice.

Thanks for a great software!

**Comment by xoroz** [comment]
Yes support for folders is important so anything in folderA is auto configured as CategoryA or ClientA.

Right now we need a simple way to upload files (by FTP) and have it autoconfigured for a client. Is there anyway we can do this?

**Comment by lenamtl** [comment]
For folder support see this post 
https://github.com/ignacionelson/ProjectSend/issues/129

**Comment by ignacionelson** [comment]
Working on folders right now.  There are other issues about this same topic so I'll close this.
