### ISSUE TITLE
First logon after installation

### ISSUE THREAD

**Issue by nickchalker** [projectsend/projectsend#293]
Hi,
Environment:
CentOS 7
mysql 56-5.6.32
php 5.4.16-36.3
Apache 2.4.6-40
ProjectSend Latest Version from //github.com/ignacionelson/ProjectSend/archive/master.zip

I have followed a number of installation guides for debian, centos6 and centos7, the installation is fine and returns successfull.

When I try to logon it appears the logon is successful as Fiddler shows a redirect to home.php but then I get redirected back to index.php

If I use the wrong password I get credentials are invalid.

I have tried Firefox, Chrome and IE, they all exhibit the same

Cheers
Nick

**Comment by dlarson1957** [comment]
I have the same problem , did you get this resolved

**Comment by ignacionelson** [comment]
Does not seem to happen anymore. Reopen if it does please.
