### ISSUE TITLE
Cloud Service: Php session last 45 seconds

### ISSUE THREAD

**Issue by juancsb** [projectsend/projectsend#294]
In my Installation, the php session last only 45 seconds, I tried to make it longer across HTACCESS but had no success...

**Comment by juancsb** [comment]
Apache/2.4
PHP 5.6
MySQL 5.6
Installed on [http://apps.creacion.com.co/cloud](http://apps.creacion.com.co/cloud)

**Comment by lenamtl** [comment]
Have you check the paths in config files?
