### ISSUE TITLE
Update r609 to r754 trough Softaculous, stuck at 95%

### ISSUE THREAD

**Issue by Ideawmx** [projectsend/projectsend#302]
Hello, 
I have a r609 installation on my shared hosting and I received a notice that an update was available. I ran the script and it get stuck at 95%. sending an error message that states "oops connection lost"

My guess is there are some cleaning / finalizing activities that may failed due to file permissions perhaps?

Is there a log created during the process?
IDK if softaculous even saves an update log? -sure it depends on the hosting provider-
any ideas?  Thanks.

**Comment by lenamtl** [comment]
I'm not sure if the latest version is on Softaculous.
Does the update notice came from Softaculous or from Projectsend banner?

You can try to increase some values like
PHP.ini
```
max_execution_time
max_input_time
memory_limit
```

Mysql my.ini
```
max_allowed_packet
read_buffer_size
```
