### ISSUE TITLE
No outgoing mail if client or admin upload a file

### ISSUE THREAD

**Issue by ardonos** [projectsend/projectsend#306]
Hi, first of all thanks for this nice project!

Here my problem: if a client or admin(myself) upload a file, there is no notification or outgoing email.

but if i(admin) upload a file and assign this file to a client, i get a mail notification.

Is this a known issue?

Nice regards

**Comment by dannyulman** [comment]
I tried asking the same thing but they wouldnt add this feature

**Comment by ilackskills** [comment]
That would require too many smtp relays unless you have a mail server.

**Comment by onlinestatements** [comment]
I do have a mail server on virtual private hosting.
I do have cpanel access and whm control panel and it appears I can change the mail server settings to allow more relays. But I am not 100% sure though

**Comment by ilackskills** [comment]
it is not worth the time of the developers to customize this, while it would be nice option its not one that most people have the ability to use.

**Comment by ardonos** [comment]
i think its a must have.

**Comment by lenamtl** [comment]
Question: Why would the admin received a notification for a file he uploaded ?
