### ISSUE TITLE
Upload progressbar not working anymore

### ISSUE THREAD

**Issue by zwobbl** [projectsend/projectsend#307]
Hi,
since I have upgraded my installation to r754 the progress bar is not working anymore. It is shown but it stays empty. 
The textual display showing the percental progress (per file and overall) is updated while uploading.

**Comment by lenamtl** [comment]
could you check the console in chrome dev tool (rigth click - inspect)
to see if there any error message

**Comment by zwobbl** [comment]
I looked it up with firefox dev tools. No JS errors on the console. Furthermore the inline style for the width is updated correctly for this node

`<div class="plupload_progress_bar bar" style="width: 9%;"></div>`

but it doesn't get visual. maybe just some css broken or even a background image missing?

**Comment by lenamtl** [comment]
Have you tried with different file size ?
Maybe try to compare your files with the original package maybe some files ares missing

**Comment by zwobbl** [comment]
this [patch](https://gist.github.com/zwobbl/22e1595f19deb06210f0028daeba246e) fixes the issue for me

**Comment by lenamtl** [comment]
Thanks
