### ISSUE TITLE
Upload/Download/Create folders?

### ISSUE THREAD

**Issue by DylanMarcotte** [projectsend/projectsend#318]
I used this amazing project as a plateform to share files to our customers, and I will probably start helping with the github now. I also might donate to keep this alive... but one thing I noti ed is its kind of hard for our managers to upload multiple files and assign them to clients. 

For instance, uploading 5 files to 30 clients takes 150 associations... it would be nice to be able to deal with folders so you can assign a whole folder to clients and groups instead of only single files all the time, which also makes a chaotic list of files on the administration part.

**Comment by savagela** [comment]
Groups can take care of that. If you make one group with all 5 files, you can subscribe 30 clients to the group and they all have access. That's 35 associations. 
I agree that folders would be useful, but groups are okay for most things. 

Multiple associations can be made while uploading files, but not for files already uploaded. That is a feature I am eagerly waiting for.

**Comment by ignacionelson** [comment]
Working on folders right now.  There are other issues about this same topic so I'll close this.
