### ISSUE TITLE
upload file does not work under xampp 7 (PHP 7)

### ISSUE THREAD

**Issue by asmwarrior** [projectsend/projectsend#327]
Here is the details: www.apachefriends.org
xampp 7.0.13 / PHP 7.0.13 under Windows 7 or CentOS 6.8 + ProjectSend-r756, when I try to upload a file, and I see that there is no message window shown up to let me set the title and messages.

xampp 7.0.13 / PHP 7.0.13 + ProjectSend-git-master-Jan 5, 2017, this also shows the issue above mentioned.

xampp 5.6.28 / PHP 5.6.28 + ProjectSend-r756 when I try to upload a file, it works OK.

**Comment by lenamtl** [comment]
This is a configuration issue, do some search, there are few issue post on it.
https://github.com/ignacionelson/ProjectSend/issues/320

I will close this one as there a already some posts on this issue.

**Comment by asmwarrior** [comment]
I did search on the issues, but I can't find one similar. About the #320 , I think it is not related, because the OP mentioned the error happens in the "install" stage. 

>  I get to the start page, and upon filling out the form and clicking "install" I get the following:

But for my usage, the error happens in the "file upload" usage.

**Comment by lenamtl** [comment]
could you allow php error and paste the errors messages that you have.

**Comment by mschop** [comment]
@asmwarrior I close this issue, because you didn't provide the needed information. If the problem persists, please do not hesitate to reopen the issue.
