### ISSUE TITLE
upload was not working

### ISSUE THREAD

**Issue by syrandel** [projectsend/projectsend#329]
Hi,

I downloaded recently the last release of ProjectSend r756.
I tried it, but the upload of files did not work.
I discovered that in the PSend_Upload_File class defined in includes/classes/file_upload.php,
at line 96, a call is made to a method (basename) which is not defined.
I replaced "return $this->basename(safe_filename);" by "return basename($this->safe_filename);"
and it worked much better.
How is it possible that this version was not corrected until now ? And since it was commited, nobody mentionned it did not work without correcting it ?
Or maybe there are some webservers and php parsers which allow such a syntax ?
Anyway, I hope my post will help some.

My thanks to Ignacio

**Comment by syrandel** [comment]
I am not familiar with Github. I just realized the code in which I found a bug was updated 15 days ago. It is less surprising.

**Comment by lenamtl** [comment]
This was something fixed regarding latest security issue.

**Comment by eyeobticeo** [comment]
A quick solution is to change the line 96 in \includes\classes\file-upload.php
`return $this->basename(safe_filename);`
to
`return $this->safe_filename;`

In my quick test woks the upload but i have not test the full code.

**Comment by OrlandoST** [comment]
The problem is in file /includes/classes/file-upload.php
There is error in function:
	function safe_rename($name)
	{
		$this->name = $name;
		$this->safe_filename = $this->generate_safe_filename( $this->name );
		return **$this->basename(safe_filename);**
	}

Function $this->basename() is not exist, probably we can use php function basename():
	function safe_rename($name)
	{
		$this->name = $name;
		$this->safe_filename = $this->generate_safe_filename( $this->name );
		return basename($this->safe_filename);
	}

**Comment by ameenullah** [comment]
After uploading, I am getting this error "FILES NOT UPLOADED" also unable to edit the filename: it always  shows undefined.
