### ISSUE TITLE
Bug stopping clients from login in.

### ISSUE THREAD

**Issue by drgr33n** [projectsend/projectsend#334]
Hey,

With the latest clone I was getting an SQl error due to a missing space within templates/session_check.php @ line 26.

$sql = $dbh->prepare( "SELECT active FROM". TABLE_USERS . "WHERE user= :current_user_username");

should read

$sql = $dbh->prepare( "SELECT active FROM ". TABLE_USERS . " WHERE user= :current_user_username");

Notice the space trailing FROM and preceding WHERE.

**Comment by ilackskills** [comment]
please check #342
