### ISSUE TITLE
Problems while downloading a secured file

### ISSUE THREAD

**Issue by ericbeaucourt** [projectsend/projectsend#340]
A client tried to download a secured document and received the following error

ICAP Error (icap_error) 
An error occurred while performing an ICAP operation: File is password protected; File: process.php; Sub File: No file name available; Vendor: Kaspersky Labs; Engine error code: 0x000A0000; Engine version: 8.1.8.79; Pattern version: 170131.050900.8942813; Pattern date: 2017.01.31 05:09:00 
There could be a network problem, the ICAP service may be misconfigured, or the ICAP server may have reported an error.

**Comment by lenamtl** [comment]
it's seems a network problem pn user side, does other user having this issue.

**Comment by ericbeaucourt** [comment]
Your are right. Al the persons who tried to download a secured file trough the same server have the same problem. So I think you can close this item.
