### ISSUE TITLE
language setting per customer

### ISSUE THREAD

**Issue by creative-resort** [projectsend/projectsend#348]
When logged in using one certain language,
newly created customers are sent an eMail in that language,
instead of THEIR preferred language, which is not desirable. :)

Please make a language setting per customer available.

**Comment by lenamtl** [comment]
At the moment email template are not related to a specific language.
What you can do is to have the message translated on the template.

**Comment by ignacionelson** [comment]
I believe this would be useful but too big of a task. Can't do it right now.
