### ISSUE TITLE
naming suggestion (unimportant)

### ISSUE THREAD

**Issue by barna119** [projectsend/projectsend#402]
In the "View my files" list:

"Ext." -> "Type"
Unnecessary, ugly abbreviation. Anyway, this is the file type field.

"Expiration date" -> "Expires"
Makes too long field, when all files below expire "Never".

Btw, thre would be nice to have a switch, so expiration date field is not listed. Can't think of such a case, when an expiration date for a file would be useful. If we don't need, just delete. (Okay, keep the feauture, just make it hidden.)

**Comment by lenamtl** [comment]
These are easy to fix directly into the code and/or language file.
Expiration is now an option (depending of the version) .
I agree this should not appear if we don't use it, you can edit the code to hide it, this is what I did.

You can customize PS to your need, you can hire a dev or do it yourself.
You can do a search, some user share their own snippets.

**Comment by ignacionelson** [comment]
Thanks for the suggestions!
This strings belong to the default template, and not the admin.
i've edited them on the en_us translation. If you'd like, you can download the compiled .mo file from the project on transifex or edit your own .po file using the software poedit.

Making the changes on the original string on the php files would cause them to appear in english when using the translation files for another language, so having this new terms by default now doesn't seem like the best idea :/

**Comment by barna119** [comment]
1. include new code with the new string, and make it unfunctionable
2. wait till the change propagates into the translations
3. disable the code with the old sting and make the code with the new string to work

**Comment by ignacionelson** [comment]
Changed column name 
7ba45cf and dd08fe5
