### ISSUE TITLE
r885 - If a  user try to upload a file with same name of another file already present, upload fails.

### ISSUE THREAD

**Issue by remez** [projectsend/projectsend#418]
Hi,

If a user try to upload a file with the same name of a file already present, projectsend locks on "Upload files" page.

How to reproduce:

Log as user 

Upload -> Load a file (pippo.zip) -> Press "Upload files" -> New page where it asked for a name and a description -> Press "Save" -> New page with "File updated correctly" and a brief description -> All OK

Try to load again pippo.zip file:

Upload -> Load a file (pippo.zip) -> Press "Upload files" -> New page where it asked for a name and a description -> Press "Save" -> New page with "Upload files" and projectsend stucks here.

**Comment by remez** [comment]
`[Tue Jun 20 12:02:19.791211 2017] [:error] [pid 2682] [client XX.XX.XX.XX:58900] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'file_id' cannot be null' in /var/lib/nethserver/vhost/projectsendtest/includes/classes/file-upload.php:284\nStack trace:\n#0 /var/lib/nethserver/vhost/projectsendtest/includes/classes/file-upload.php(284): PDOStatement->execute()\n#1 /var/lib/nethserver/vhost/projectsendtest/upload-process-form.php(239): PSend_Upload_File->upload_add_assignment(Array)\n#2 {main}\n  thrown in /var/lib/nethserver/vhost/projectsendtest/includes/classes/file-upload.php on line 284, referer: https://xxx.xxx.xxx/upload-process-form.php
`

**Comment by wsjake** [comment]
Lines 157-168 of file upload-process-form.php seems to have an unnecessary if/test condition. It seems all uploads should be renamed regardless of existence in DB.

If I comment lines 157, 165, 166, 167, and 168 of upload-process-form.php, all works as expected.

The only time this would then fail if the same file was uploaded twice at the exact same time (e.g.; second)  as the upload_move function of file-upload.php uses the time() and hash functions to attempt to create a unique file name to store the uploaded file long term.

https://github.com/ignacionelson/ProjectSend/blob/master/upload-process-form.php#L157

This block (157-168):
```
if (!in_array($file['file'],$urls_db_files)) {
	$move_arguments = array(
							'uploaded_name'		=> $location,
							'filename'			=> $file['file'],
						);
	$upload_move		= $this_upload->upload_move($move_arguments);
	$new_filename		= $upload_move['filename_disk'];
	$original_filename	= $upload_move['filename_original'];
}
else {
	$new_filename = $file['original'];
}
```
Should simply be (remove IF/ELSE lines):
```
$move_arguments = array(
						'uploaded_name'		=> $location,
						'filename'			=> $file['file'],
					);
$upload_move		= $this_upload->upload_move($move_arguments);
$new_filename		= $upload_move['filename_disk'];
$original_filename	= $upload_move['filename_original'];
```

Currently, If you open the /upload/files directory, and try to upload the same file over and over again, you'll observe the pattern of success/fail/success/fail/success...etc. Upload succeeds first attempt, fails second attempt, succeeds third attempt, fails fourth, etc. You will also then observe the gremlin/orphan files which are left behind. The proposition/fix above will remedy this, and rename every file every time it's uploaded, leaving no gremlins or appended incremental suffixes (e.g.; _1, _2) on file names!

**Comment by ignacionelson** [comment]
Thank you!! I will take a look into this and make the modifications. As you say, all files should be renamed.

Even if you upload the same file at the same time, it will only cause problems if the uploader is the same, as the file name includes the timestamp + hash of the username. Maybe a random string should be added to that hash also?

**Comment by wsjake** [comment]
My opinion is either attempt to fully avoid file name collisions, or there must exist test conditions, or both. Then if unique name already exists then you handle, and can just regenerate a new name as required.

You could explore supplementing a file name with uniqid. (e.g.; avoid wheel reinvention)

**Comment by lenamtl** [comment]
see #305
