### ISSUE TITLE
Getting update message on my webserver

### ISSUE THREAD

**Issue by Syedwaheed** [projectsend/projectsend#421]
Why do i keep getting update available message on my web server?. Isn't is there a way to stop getting update from new version? I have uploaded it on my web server and setting up things on local host but still getting update message. Any help would be appreciated. Thanks.

**Comment by ignacionelson** [comment]
Hello!! What version are you using right now?

**Comment by Syedwaheed** [comment]
Thanks for your comment. I m using "r859" version of project send.

**Comment by ignacionelson** [comment]
I see, that is not a real release, so I think that it must be happening due to some bug on unfinished code.
Version numbers are loaded from this xml
http://projectsend.org/updates/versions.xml
The latest one is r754

Also, maybe one of the values on your options table is not correct. Are you comfortable editing the database directly?

**Comment by Syedwaheed** [comment]
I haven't made any changes in the database directly neither i know what to change in it. if you suggest me to change something then i will check it out. What should i do to avoid getting an update? should i move to updated version and then upload it to my server?  will this avoid getting an update version again? bundle of thanks for your answer.

**Comment by ignacionelson** [comment]
Let's try this

1- in the table prefix_options, find the row with name last_update and set it to 859 (or better yet, just the number of the version defined on sys.vars.php)
2- change the value of version_new_found to 0

Hope that helps!

**Comment by Syedwaheed** [comment]
Thanks for your prompt reaction! both of these were already same as you stated, my problem is that i m not getting update version message on my local host but getting the message on web server.  As this can see in picture below.
![screenshot](https://user-images.githubusercontent.com/14071753/27420238-6241e6e2-573e-11e7-90cf-dcc91560d91a.png)

**Comment by ignacionelson** [comment]
Oh I see. And what's the CURRENT_VERSION value on sys.vars.php?

**Comment by ignacionelson** [comment]
Please try clearing also the 7 options rows that start with version_
version_new_found set to 0
set to nothing the others (
version_new_number
version_new_chlog
version_new_security
version_new_features
version_new_important
version_new_url
)

**Comment by Syedwaheed** [comment]
All these values are by default "set to nothing" and i haven't changed any of these.  i have changed the CURRENT VERSION in sys.vars.php to  "." as i don't want to show version on footer. i couldnt make a custom footer for it as well in Option-> General.

**Comment by Syedwaheed** [comment]
I have seen my database on the web server and i can see all those "version" values, but when i change them to empty and go back and login in to system these values are inserted back. Any help please!

**Comment by ignacionelson** [comment]
This info is handled differently in r1265. Marking as solved
