### ISSUE TITLE
Upload timeout

### ISSUE THREAD

**Issue by txnet1** [projectsend/projectsend#422]
Hi, anyone have any ideas why an upload would work fine on one computer, but not on another? The upload just timeouts and nothing happens, but works just fine on another desktop. I have cleared the cookies, cache, etc and made sure the browser settings were the same, but am still the issue.

**Comment by lenamtl** [comment]
That is maybe related to internet service, file size, network permission settings on business network ...
Have you tried other browser ?

You can change php.ini settings if you can, this is just an example, change the value to what you need:
upload_max_filesize = 50M
post_max_size = 20M
max_execution_time = 30

**Comment by mschop** [comment]
@txnet1 I close this issue, because you did not add further details. If the problem still persists, do not hesitate to reopen the issue.
