### ISSUE TITLE
Folders Per Client

### ISSUE THREAD

**Issue by ilakskill** [projectsend/projectsend#424]
I do not know how much everyone else uses this but I use it ALOT, I have 40,000 files stored.  A problem I face is 40,000 files in a folder is hard to deal with.  I dont understand why all the files are stored in one folder VS a folder per client.  Is this possible in future release?

**Comment by ignacionelson** [comment]
That's quite the number of files you have there!!!
Organizing them in folders per client wouldn't be right, as a file is not limited to a single client.
I believe that a better solution would be the WordPress way, having them organized by date.

I'll try to work on this!

**Comment by ilackskills** [comment]
I wish I could share the things I have modified but the issue I have is being able to share what I have done based on a clean install version, I do not know how to use github correctly to do this.

**Comment by ilackskills** [comment]
@ignacionelson I see your point about one user per fold not being correct, in my case it is.  I might just have to write a script that loops the users and files and copies them to folders when I need to do that for backups of user files

**Comment by EarMaster** [comment]
Would it be a solution to rename the files on the server to something unique (e.g. the public token)? This would on one hand obfuscate the contents of the file for someone browsing the directory using FTP, but it would also solve some other problems like the automatic renaming of duplicate named files. This would require renaming the files again for download (but this could be arranged using the right headers).

**Comment by newyenjay** [comment]
Is there any progress on this? Would love to be able to have folders within each client profile

**Comment by newyenjay** [comment]
Is there any updates on folder creation by users? Would love this feature since we albums of pictures from clients

**Comment by ilakskill** [comment]
I have started this but have not finished it

**Comment by ignacionelson** [comment]
Release r1720: added a setting to save new uploads in year/month based folders. This should solve this problem.
