### ISSUE TITLE
Cookie Law in European Community

### ISSUE THREAD

**Issue by remez** [projectsend/projectsend#425]
Hi,

In European Community we have this law:

[http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm](url)

Basically, a user have to accept that your site saves cookies on the pc and there must be a page where it explained why and how the cookies are used by the website.

It's already implemented here?

**Comment by lenamtl** [comment]
You can add it using some JS
https://github.com/insites/cookieconsent

**Comment by mschop** [comment]
I think this should be added to #569 as this is even more relevant since this law is active. I close this issue and add this aspect to the linked issue (#569)
