### ISSUE TITLE
iPhone Photos Are Upside Down after upload.

### ISSUE THREAD

**Issue by ilakskill** [projectsend/projectsend#427]
When uploading a image from a Iphone picture orientation is not correct.

**Comment by lenamtl** [comment]
Could do give more information on how to reproduce

**Comment by ilackskills** [comment]
I do not have an iPhone to test with so I can not describe exactly the steps needed to reproduce.  From my understanding, it is either missing or incorrect info in the iPhone Picture located in the EXIF metadata.  I will see what I can come up with on this.

**Comment by ilackskills** [comment]
@lenamtl I should get some examples today.  But I have noticed Images only display in landscape, not portrait.  I will set up a test account for your review.

**Comment by ilackskills** [comment]
![image](https://user-images.githubusercontent.com/15673241/27912065-1edf8682-6221-11e7-8ea6-068d59dfe726.png)

The finger is pointing to the top of the phone, the red arrows are pointing where the sky should be.

**Comment by ilackskills** [comment]
I am gonna try and work on this when I get time because this is a big PITA for me.

**Comment by corvinb** [comment]
+1

**Comment by ilakskill** [comment]
This is from an old version, can't remember what one, I did fix it but overwrote with current version.  I will see if the problem is still there.

**Comment by mschop** [comment]
This is an iphone and usage problem and not a bug in ProjectSend. ProjectSend does not manipulate the images or use the meta information for displaying the images. Therefore I close this issue.
