### ISSUE TITLE
Which version is official?

### ISSUE THREAD

**Issue by rootolf** [projectsend/projectsend#435]
Hello
Which version is official and stable? 
r754 from projectsend.org
r756 from https://github.com/ignacionelson/ProjectSend/releases

**Comment by VincentSC** [comment]
Those releases are almost one year old. When will there be a new release?

**Comment by VincentSC** [comment]
@ignacionelson How much do you want on Patreon https://www.patreon.com/ignacionelson to make a new release? I personally think you should just ask.

**Comment by ignacionelson** [comment]
Sorry, this was confusing at times!
New version is r1265 and it's the only official one now.
