### ISSUE TITLE
No names for recipeints of notification emails (solution)

### ISSUE THREAD

**Issue by olimax** [projectsend/projectsend#437]
No names are being sent in the 'To;'  fields of notification
Following the scheme of things, these changes seem to work

In **upload-send-notification.php**
After
`$mail_by_user[$row['user']] = $row['email'];`
add this (both occurrences)
`$name_by_user[$row['user']] = $row['name']; `
//////////////////////////////////////////

This change this:
```
			$address = $mail_by_user[$mail_username];
			/** Create the object and send the email */
			$notify_client = new PSend_Email();
			$email_arguments = array(
				'type' => 'new_files_for_client',
				'address' => $address,
				'files_list' => $files_list
			);
```
to this (two occurrences) 
```
			$address = $mail_by_user[$mail_username];
			$name = $name_by_user[$mail_username]; /////////////// NEW ///////////////////////////
			/** Create the object and send the email */
			$notify_client = new PSend_Email();
			$email_arguments = array(
				'type' => 'new_files_for_client',
				'address' => $address,
				'files_list' => $files_list, ////////// add comma ///
				'name'		=> $name ///// NEW /////
			);
```

////////////////////////////////////////////////////////////////////////
In **send-mail.php**
`$this->send_mail->AddAddress($this->addresses );		`
change to	
`$this->send_mail->AddAddress($this->addresses, $this->name);`

Works for me

**Comment by ignacionelson** [comment]
Done on https://github.com/projectsend/projectsend/commit/6c9e7d760e148ca0aebf4e86575711d4fe38e02a

**Comment by ignacionelson** [comment]
Thank you!!
