### ISSUE TITLE
Redirect loop for client account

### ISSUE THREAD

**Issue by PeterHarperBorne** [projectsend/projectsend#439]
Hi,

I have an odd issue - when I sign in as an admin, everything works exactly as it should.

However, I've set up a couple of client accounts, and when I try to log in using any of their credentials, I get into a redirect loop that is only resolved by deleting cookies (which then of course just dumps me back at the login page).

The sequence is: 

1 - login page, enter login details
2 - 302 redirect to "/"
3 - 302 redirect to "/my_files/"
4 - goto 2, repeat

Any advice? I've reinstalled, updated to the latest version etc.

**Comment by Syedwaheed** [comment]
I have recently installed the latest version but i m not having such kind of issues. i have been creating clients and signing in smoothly. May be, you can try on different web browser.

**Comment by Ziolupone** [comment]
Hello, I also have this issue about redirection. I tried with every version available, with multiple browsers but every time I try to login as a user I get redirected to the login page without any error or notification.

**Comment by mschop** [comment]
@PeterHarperBorne @Syedwaheed  @Ziolupone On which version are you currently. Do you still have this issue?

**Comment by mlsuelto** [comment]
Is there a fix for this?  I tried updating to the latest version and this is still happening.

**Comment by BlackBeltBob** [comment]
I think i also experience this issue. The problem for me lies in process.php calling which does require_once('sys.includes.php') which in turn calls require_once(ROOT_DIR.'/includes/active.session.php'), which checks SESSION_TIMEOUT_EXPIRE and checks the last_call with the current time - the expire time. If so, it redirects to BASE_URI . 'process.php?do=logout&timeout=1'. Obviously, this is a loop from which the site can't escape. 
For now, I've deactivated SESSION_TIMEOUT_EXPIRE by setting it as false in sys.vars.php on line 202.

My version is r1070, and i haven't modified these files beyond the original install.

**Comment by ignacionelson** [comment]
Solved in r1265
