### ISSUE TITLE
Admin panel Statistics graph and Recent Activities are http dependent

### ISSUE THREAD

**Issue by wavesource** [projectsend/projectsend#441]
When running ProjectSend under https these two panels fail to load. These need to be agnostic as to whether secure connection is enabled or not.

**Comment by ignacionelson** [comment]
Thank for your report! which version are you using?

**Comment by wavesource** [comment]
Latest - r754

**Comment by ignacionelson** [comment]
I believe that this is fixed already, but an official release is not available yet.

**Comment by ignacionelson** [comment]
Solved in r1265
