### ISSUE TITLE
Empty PHP Sessions

### ISSUE THREAD

**Issue by webguy2004** [projectsend/projectsend#444]
We are noticing lots of empty php sessions on our server and can't figure out how/why they are getting there.

Does ProjectSend create lots of empty session data? We don't have many php applications running on our server so if it's not one of them, we are concerned there may be something malicious running.

**Comment by ignacionelson** [comment]
Hello! No, sessions are setting only 4 values.
I haven't also heard of PS doing this before. Did you have any luck tracing the sessions on your server?

**Comment by webguy2004** [comment]
No luck.  Our sysadmin tried clearing the directory, then logging into PS.  It created the session as expected.  He logged out and it emptied the session but left the file there (0 bytes).  So it's possible they are being created by that, although I doubt the software is getting that much usage to account for all the empty pages.

**Comment by mschop** [comment]
@webguy2004 this is expected behaviour. When a user is logged out the variables in the session are unset. But this does not delete the session. It just empties session. The session should be garbage collected after some time from the php session garbage collector.
