### ISSUE TITLE
absolute path in functions.php

### ISSUE THREAD

**Issue by walokr** [projectsend/projectsend#450]
I'm testing project send but installed in a sub folder (/ps/) and detected in includes/functions.php absolute paths for logo file: 
- line 813 - **$branding['url'] = '/img/custom/logo/'.LOGO_FILENAME;**
I think you could change it to: **$branding['url'] = LOGO_FOLDER.LOGO_FILENAME;**
(LOGO_FOLDER is defined at line 183 of sys.vars.php

**Comment by JackWhite20** [comment]
I think this is already changed in the latest code. It uses the defined BASE_URI constant to generate a URL for the logo.

**Comment by ignacionelson** [comment]
Indeed, this has been fixed :)
