### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by Oblivii** [projectsend/projectsend#451]
Having issues after uploading files, the thumbnails do not work viewing the file/image. Even my branding logo does not show up, except only for login.

**Comment by Oblivii** [comment]
Can someone help me with this issue?

**Comment by Oblivii** [comment]
![untitled](https://user-images.githubusercontent.com/24266829/29246093-138cbe7a-7fb4-11e7-82ac-d198867a6cb7.png)
What is the issue here?

**Comment by ignacionelson** [comment]
Hi! Have you tried setting the "use file's absolute path" checkbox on the thumbnails options page?

**Comment by Oblivii** [comment]
Yes, indeed. That is correctly set.

**Comment by ignacionelson** [comment]
Try directly accesing the url of the image and see if you get an error there (right click->view image)

**Comment by Oblivii** [comment]
Blank page! :(

**Comment by Oblivii** [comment]
This is the link: http://www.dretchstorm.com/share/includes/timthumb/timthumb.php?src=http://www.dretchstorm.com/share/img/custom/logo/logo_red_hover.png&w=300

**Comment by ignacionelson** [comment]
Oh :(
Can you check your server's error log? the answer might be there

**Comment by Oblivii** [comment]
Yes let me have a look right quick

**Comment by Oblivii** [comment]
This is what I got.
```
 [14/Aug/2017:05:43:06 +0000] "GET /share/includes/timthumb/timthumb.php?src=http://www.dretchstorm.com/share/upload/files/1502689381-45c57$
 [14/Aug/2017:05:43:06 +0000] "GET /share/includes/timthumb/timthumb.php?src=http://www.dretchstorm.com/share/img/custom/logo/logo_red_hove$
 [14/Aug/2017:05:43:21 +0000] "GET /share/includes/timthumb/timthumb.php?src=http://www.dretchstorm.com/share/img/custom/logo/logo_red_hove$
 [14/Aug/2017:05:44:10 +0000] "GET /share/my_files/ HTTP/1.1" 200 1604 "http://www.dretchstorm.com/share/upload-process-form.php" "Mozilla/$
$Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
```

**Comment by ignacionelson** [comment]
I believe that is the access log, not the errors log :/ Maybe it's on the same folder as timthumb.php?
Also I'm trying to replace that script for the next version so this error will stop happening.

**Comment by Oblivii** [comment]
It didn't entirely paste, I fixed, and ahh okay, let me have a look!

**Comment by Oblivii** [comment]
Nothing in the folder timthumb, However I found error log of course in apache folder. I have a few errors, but nothing recent. Going to see if it fixes it.

```
PHP:  syntax error, unexpected '=' in /etc/php/7.0/apache2/php.ini on line 1030
PHP:  syntax error, unexpected '=' in /etc/php/7.0/apache2/php.ini on line 1030
PHP:  syntax error, unexpected '=' in /etc/php/7.0/apache2/php.ini on line 1030
PHP:  syntax error, unexpected '=' in /etc/php/7.0/apache2/php.ini on line 1030

```

**Comment by Oblivii** [comment]
Nope, that was just a mail error.

**Comment by Oblivii** [comment]
I get this when restarting apache 
```PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_fileinfo.dll' - /usr/lib/php/20151012/php_fileinfo.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_gd2.dll' - /usr/lib/php/20151012/php_gd2.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_mysqli.dll' - /usr/lib/php/20151012/php_mysqli.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_pdo_mysql.dll' - /usr/lib/php/20151012/php_pdo_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_pdo.dll' - /usr/lib/php/20151012/php_pdo.dll: cannot open shared object file: No such file or directory in Unknown on line 0
```

**Comment by Oblivii** [comment]
Is there an update on why this is not working for me???

**Comment by ignacionelson** [comment]
I believe that the best course of action would be to open a ticket on your hosting provider and show them the error logs you are getting, as this seems like an error specific to your server.
The current thumbnails system is far from perfect but usually works just by tweaking the settings.

**Comment by Oblivii** [comment]
@ignacionelson I am the host.

**Comment by ignacionelson** [comment]
Timthumb has been replaced with simpleimage. This errors should not be present anymore.
