### ISSUE TITLE
Nav Bar doesn't work at Dashboard page

### ISSUE THREAD

**Issue by Zapper666** [projectsend/projectsend#455]
every menu on nav-bar it doesn't work on dashboard page (home.php), and only 2 form shows at this page. It's happen when i upload to my server , but it works on my local.

<img width="1678" alt="screen shot 2017-08-11 at 11 26 01 pm" src="https://user-images.githubusercontent.com/9393922/29222390-7c435e4c-7eec-11e7-88b5-de0d7a267b23.png">
 
Anyone can help me ?

**Comment by Zapper666** [comment]
<img width="1676" alt="screen shot 2017-08-12 at 12 13 23 am" src="https://user-images.githubusercontent.com/9393922/29224106-1ad020ee-7ef3-11e7-98c8-6616c0e698cc.png">

i got this error on firefox console

pleasseee help me...

**Comment by ignacionelson** [comment]
Hello! What version are you using? Also, can you please expand that error on the console to see the details?

**Comment by Zapper666** [comment]
im using r754 ver, 

<img width="1675" alt="screen shot 2017-08-12 at 12 24 10 am" src="https://user-images.githubusercontent.com/9393922/29224461-a85d07dc-7ef4-11e7-9fd5-b10f491f6b7e.png">

like that ?

**Comment by ignacionelson** [comment]
Please try using the github version:
https://github.com/ignacionelson/ProjectSend/archive/master.zip

It's still being developed so make a backup of your current installation before overwriting the files.

It has new features but some are still not finished (existing clients requesting access to public groups mainly)

**Comment by Zapper666** [comment]
it's same , i'll try 3 version of this apps, and it's not work.

any solutions ?

**Comment by ignacionelson** [comment]
It seems that you are getting a 500 error. The problem is on your server. Can you please check the error logs?
Also, make sure you are using php 5.6+

**Comment by Zapper666** [comment]
yes im using php 5.6+

Sat Aug 12 00:37:31.851035 2017] [:error] [pid 20552] [client 125.160.139.69:54115] PHP Warning:  require_once(/var/www/html/includes/phpass/PasswordHash.php): failed to open stream: No such file or directory in /var/www/html/sys.includes.php on line 12
[Sat Aug 12 00:37:31.851516 2017] [:error] [pid 20552] [client 125.160.139.69:54115] PHP Stack trace:
[Sat Aug 12 00:37:31.851539 2017] [:error] [pid 20552] [client 125.160.139.69:54115] PHP   1. {main}() /var/www/html/home.php:0
[Sat Aug 12 00:37:31.851549 2017] [:error] [pid 20552] [client 125.160.139.69:54115] PHP   2. require_once() /var/www/html/home.php:13
[Sat Aug 12 00:37:31.851570 2017] [:error] [pid 20552] [client 125.160.139.69:54115] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/includes/phpass/PasswordHash.php' (include_path='.:/usr/share/php') in /var/www/html/sys.includes.php on line 12
[Sat Aug 12 00:37:31.851591 2017] [:error] [pid 20552] [client 125.160.139.69:54115] PHP Stack trace:
[Sat Aug 12 00:37:31.851600 2017] [:error] [pid 20552] [client 125.160.139.69:54115] PHP   1. {main}() /var/www/html/home.php:0
[Sat Aug 12 00:37:31.851608 2017] [:error] [pid 20552] [client 125.160.139.69:54115] PHP   2. require_once() /var/www/html/home.php:13
[Sat Aug 12 00:37:34.011797 2017] [:error] [pid 16810] [client 125.160.139.69:54117] PHP Warning:  require_once(/var/www/html/includes/phpass/PasswordHash.php): failed to open stream: No such file or directory in /var/www/html/sys.includes.php on line 12
[Sat Aug 12 00:37:34.011853 2017] [:error] [pid 16810] [client 125.160.139.69:54117] PHP Stack trace:
[Sat Aug 12 00:37:34.011866 2017] [:error] [pid 16810] [client 125.160.139.69:54117] PHP   1. {main}() /var/www/html/home.php:0
[Sat Aug 12 00:37:34.011876 2017] [:error] [pid 16810] [client 125.160.139.69:54117] PHP   2. require_once() /var/www/html/home.php:13
[Sat Aug 12 00:37:34.011897 2017] [:error] [pid 16810] [client 125.160.139.69:54117] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/includes/phpass/PasswordHash.php' (include_path='.:/usr/share/php') in /var/www/html/sys.includes.php on line 12
[Sat Aug 12 00:37:34.011908 2017] [:error] [pid 16810] [client 125.160.139.69:54117] PHP Stack trace:
[Sat Aug 12 00:37:34.011915 2017] [:error] [pid 16810] [client 125.160.139.69:54117] PHP   1. {main}() /var/www/html/home.php:0
[Sat Aug 12 00:37:34.011923 2017] [:error] [pid 16810] [client 125.160.139.69:54117] PHP   2. require_once() /var/www/html/home.php:13



that's from my error logs

**Comment by ignacionelson** [comment]
Weird! It's telling that the file is not there. Try setting its permissions to 775 and see if that helps

**Comment by Zapper666** [comment]
still not working .
i know it's weird, i try many times using any version but still not working.

<img width="1674" alt="screen shot 2017-08-12 at 1 26 31 am" src="https://user-images.githubusercontent.com/9393922/29226784-8f27cc08-7efd-11e7-9cae-94e98d0c7bb6.png">

maybe you can see the error cause "js document" , and i guess so.

sorry but i've just customize and setup on my local for a long time, and now i got strange error.

please , don't make me sad hahahaha

**Comment by ignacionelson** [comment]
Please send me an admin user if you can to contact@projectsend.org so I can test it from my side.

**Comment by matto91** [comment]
I have the same issue on my server. Installed a fresh Ubuntu 16.04 with LAMP stack (everything latest version). I am getting also a 500 error on the home.php page. If I go directly to other pages like clients.php everything is working fine and I can navigate to other pages. Running on php7.0, because on 5.6 every page was nog working.

**Comment by hungover-org** [comment]
I was also seeing this problem. 
Running PHP7 on Ubuntu 14, 64 bit.
For me, I tracked it down to this callk in home-news-widget.php:
`$feed = simplexml_load_file(NEWS_FEED_URI);`
For whatever reason, my copy of PHP7 did not have simplexml enabled by default, so I had to run:
`apt-get install php7.0-xml`
(followed by a restart of Apache)
So, give that a try - might be all you need if you're lucky!

**Comment by mikaelmantel** [comment]
Same for me

**Comment by wmmarcus** [comment]
Had same issue until I installed php-xml and restarted webserver. Using CentOS 7 here.

**Comment by ignacionelson** [comment]
Solved in r1265
