### ISSUE TITLE
Email notifications are not working

### ISSUE THREAD

**Issue by NareshAdapala** [projectsend/projectsend#458]
Email notification is not working in production server 
I am using 
Host Name : mail.jvrjam.com
Port Number : 465
Authentication : SSL
Mailer : SMPTP
 Mails are not working 
Could you please help  what is the issue

**Comment by szobi** [comment]
Same problem here. Also using SMTP with SSL authentication. It was working before when using an older revision.

**Comment by hunsheridan** [comment]
I had the same issue. I had to - basically - replace clear the Phpmailer include dir with a newer release from Git, then it started working again - at least for me. 

Not sure if this helps.

**Comment by ignacionelson** [comment]
Thank you! I've just updated phpmailer with their latest release from github.

**Comment by szobi** [comment]
Which release of phpmailer did you use? For me it still does not work. I just tried 5.2.25 and 5.2.24.

Or can you please include the correct one into projectsend?

Many thanks!

**Comment by iamjonasmarlo** [comment]
@szobi Did you found a solution? Got the same problem...

Version r754.

**Comment by szobi** [comment]
@iamjonasmarlo Unfortunately, I did not found a solution yet. I am using version r963 with PHP 7 and still have to call or manually mail my customers when I uploaded a new file for them.

@ignacionelson In between has the new phpmailer which works become part of ProjectSend?

**Comment by iamjonasmarlo** [comment]
@szobi In my case I've found a solution. I've to create an email address with a mailbox in my provider-interface. ProjectSend was installed on a blank webspace. I've no idea why this tricky solution works – Maybe this step is opening ports or anything else. Did you have any mailbox in your webspace / web-interface?

**Comment by szobi** [comment]
@iamjonasmarlo No, I am using an external SMTP host. Thank you for that hint. Maybe I can try to setup postfix on the virtual server and link it to the external SMTP host. So, I can use the local host in the mail settings of ProjectSend. But even if this will work, it sounds too complicated to me. External SMTP hosts should work out of the box.

**Comment by JWT007** [comment]
I sort of fixed a SMTP notification problem in my installation.

We have a hosted server with an outgoing SMTP relay on port 25 which requires no authentication.

To fix the problem I had to disable the SMTPAuth option in the 'send-email.php' function 'psend_send_email': (was true)
$this->send_mail->SMTPAuth = false;

NOTE: first I enabled debugging on the PHPMailer by adding the following in:
$this->send_mail->SMTPDebug = 2;

And the hint was the following in the debug output.
SMTP -> FROM SERVER:503 AUTH command used when not advertised

**Comment by mschop** [comment]
@iamjonasmarlo 
Many hosters block outgoing mails, that have no corresponding mail account in the hosting, to prevent spamming. I think this was the case for you.

@szobi Could you please provide more details? Which hoster (php-server, mail-server etc.) are you using. Which email settings are you using, that does not work?

**Comment by agustinjais** [comment]
Hi, I'm also unable to sen email notifications. I've included the debug by @JWT007 and result is "SMTP ERROR: RCPT TO command failed: 550 5.7.1 ... Relaying denied. Proper authentication required.". What does it mean? I've tried every SMTP configuration already, but i'm quite new to programming. Thanks.

**Comment by szobi** [comment]
@mschop 
I just solved my problem. It was the wrong password in SMTP authentication. The hint of @JWT007 enabling SMTP debugging helped me to figure it out (`$this->send_mail->SMTPDebug = 2;`).
Please consider that there seems to be a problem reporting the problem when sending fails (r963):
`PHP message: PHP Warning:  array_merge(): Argument #1 is not an array in upload-send-notifications.php on line 206`

**Comment by Hein-Bloed222** [comment]
Hi there,

I have a Problem with sending emails by SMTP, no matter if TLS, None or SSL was choosen.
after inserting
$this>send_mail->SMTPAuth = false;
$this>send_mail->SMTPSecure = false;
$this>send_mail->SMTPAutoTLS = false;

in .../classes/send-email.php behind 
case 'smtp':
$this->send_mail->IsSMTP();

all Problems has gone, I could send with SMTP / None on port 25.

Maybe it will help.
(It´s a good Idea, to insert $this>send_mail->SMTPDebug = 2; if you have a Problem at this).

**Comment by ignacionelson** [comment]
r1265 includes a page under the Tools menu to test email configuration. SSL options have also been added so this is solved for most cases. Thanks @Hein-Bloed222
