### ISSUE TITLE
Google social login "Could not generate a random password"

### ISSUE THREAD

**Issue by tux0n** [projectsend/projectsend#461]
Hi
Maby someone can help me 
I enabled google sign-in add Client ID, Client Secret. I can click to sing-in by google choose account but then i get "Could not generate a random password".
When i log-in with existing admin account with google sigin-in it work ok but I can't login with new account. I was enabled all settings: Clients can register themselves and Auto approve new accounts but i still get "Could not generate a random password"
PHP/5.5.38

**Comment by ignacionelson** [comment]
Hi Mario! Creating accounts via Google Sign in is not fully implemented yet. I'll try to see if I can fix that!

**Comment by mario8883** [comment]
Thanks for help :) i will be wait for news

**Comment by ignacionelson** [comment]
Since r1265 social login is handled via hybridauth. This is probably solved. Please reopen if needed.
