### ISSUE TITLE
Google Social Login: Enabled then shows blank login page

### ISSUE THREAD

**Issue by thehouseofho** [projectsend/projectsend#464]
I enabled Google Social Login, but once I logged out, the login page is blank except for the header. Saw someone else with this problem, but they ended up reinstalling from scratch, which I would prefer not to do. I was able to set up the client ID and secret without a problem, but as soon as I enabled Google Social Login in options, the login page comes up blank.

I was able to get it back to the standard login page, but would really appreciate any help in getting Google Social Login working.

**Comment by CampinCarl** [comment]
I have this issue too. Haven't been able to get OAuth working.

**Comment by skluthe** [comment]
How were you able to get back to the standard login page? @thehouseofho

**Comment by skluthe** [comment]
Was able to fix/revert it by modifying the index.php and changing `if ( GOOGLE_SIGNIN_ENABLED == '1'
` to  `if ( GOOGLE_SIGNIN_ENABLED == '2'`

**Comment by markusmaker** [comment]
Same issue, no errors in log. What can I provide  to help?

**Comment by ignacionelson** [comment]
Since r1265 social login is handled via hybridauth. This is probably solved. Please reopen if needed.
