### ISSUE TITLE
blank upload

### ISSUE THREAD

**Issue by txnet1** [projectsend/projectsend#477]
We are having an issue where you upload and when it gets to 100% it does not go to the next page but instead goes to a page that says Upload files.. see attachment. has anyone seen this 

![upload](https://user-images.githubusercontent.com/28803678/31053586-93142042-a666-11e7-81dd-efe7dd4ea539.png)

**Comment by lenamtl** [comment]
check the PHP log for any error
check php ini about file size

**Comment by selcali** [comment]
Hello we have exact the same problem and i cant find a solution yet

**Comment by txnet1** [comment]
My problem was assets.php. I had copied an updated version from this website and when it copied over it moved all of the code over one space. This is what im talking about 

Extra left justified space 
 global $load_css_files;
 global $load_js_files;
 global $load_compat_js_files;

Should be like this. 
global $load_css_files;
global $load_js_files;
global $load_compat_js_files;

See the difference? Put your cursor infront of global and hit backspace. Check any files that have been modified. 

Once fixed it worked like a champ

**Comment by selcali** [comment]
i have extracted R754 and then R1003from git exact the same error
Files not uploaded
File Name
undefined
if i put files direct to the server with ftp the is also no files displayed

**Comment by ignacionelson** [comment]
@txnet1 Sorry, what editor did you use to fix this? I've tried Atom, Sublime, N++ and Brackets and I cannot reproduce the error. Thanks!

**Comment by selcali** [comment]
I thing that was something with the folder permissions  /var/www in CentOS
I changed from centos to OpenSuse 42.3 set Permission to www and it worked
