### ISSUE TITLE
Suggestion : subdir

### ISSUE THREAD

**Issue by Philippe-M** [projectsend/projectsend#48]
Hello,
is he scheduled the ability to create subdirectories for the customers?

Thanks for advance.
Philippe.

**Comment by lenamtl** [comment]
Hi there are several request for subdir, we will take all suugestion and see what can be done.
But we need to fix the actual code first.

**Comment by mschop** [comment]
I cannot imagine, how this could improve ProjectSend? File Categories should be what you are looking for. Or am I missing something?

**Comment by lenamtl** [comment]
I don't know if the actual version still putt all the file in the same folder or not, but if this still the case then this is no good for several reasons mentioned on other post about that topics
