### ISSUE TITLE
Versions/releases # installation failure of r963 on MAMP 4.2.1

### ISSUE THREAD

**Issue by maybor** [projectsend/projectsend#483]
Hello together

this work seems great and awesome, but we have some trouble with versions/releases:

– download from projectsend.org: r754 => sys.vars.php line 17: r754
– download from github.com/ignacionelson/ProjectSend/releases: r765 => sys.vars.php line 17: r754
– download from https://github.com/ignacionelson/ProjectSend (master): sys.vars.php line 17: r963

Unfortunatelly, r963 doesn't install on a standard MAMP machine (blank page at ...//install/make-config.php with FF, ERROR 500 with GC), while 754 and 756 install fine.  Same scenrio with php 7.1.1 and php 5.6.30.

Unfortunatelly, the contact form on proecjetsend.org doesn't work.

Any help or clarification is very much apreciated!

Best regards

EDIT: Installation problem with r963 not only on local machine, but also on servers running ubuntu 16.04 and debian 3.2.93, both with php 5.6.26

**Comment by mschop** [comment]
how about the latest official release? -does the problem still exist there?

**Comment by maybor** [comment]
Thank you very much for the reminder, I didn't follow the project receently but after reading the changelog... the new/current release looks very promising! I will check it out as soon as possible and then tell you my experience. Best regards

**Comment by maybor** [comment]
Hi there, local installation worked perfect, only that after finishing there is no success-message or re-direct, please see attached file. 
![ps_install_finish](https://user-images.githubusercontent.com/32642749/41047749-8b682c7a-69ad-11e8-8b4a-ad2386da9507.png)
best regards

**Comment by ignacionelson** [comment]
Can you please enable debug mode? You need to set it to true on sys.vars.php

define('DEBUG', false);
to
define('DEBUG', true);

The error should be visible then

**Comment by maybor** [comment]
Hola Ignacio
I have just tried it out with debug mode enabled. The result: same screen, same behaviour after installation.. When I reload the the page the message occurs "Allredy installed". The installation seems to be fine.
Cordialmente
maybor

**Comment by greekit** [comment]
I am getting installation failure at version 1053 too.
In particular I am getting an unsuccessfull installation with no result, exacly like the above picture attached.
I am running PHP 5.6.36, Apache 2.4.33 and Mysql 10.1.31.
- Is any of these version making the problem?

In an other hosting with  PHP 5.6.34, Apache 2.4.29 and Mysql 10.0.35 the Project Send 1053 installed completely with no errors.

After the failure installation (that it doesn't indicate that it has been completed installed), I detect a bug at the Membership requests as shown at the photo attached.
![untitledprojectsend](https://user-images.githubusercontent.com/10025897/41237227-b43ae506-6d9b-11e8-9a45-302c960d7d5d.png)
