### ISSUE TITLE
Navigation Bar on Dashboard Won't Work

### ISSUE THREAD

**Issue by ricardornetsurit** [projectsend/projectsend#493]
I am having an issue, when I log on, it goes to the Dashboard, my entire navigation bar does not work, I hover/click and nothing happens. It happens on all browsers, firefox/chrome/ie/Edge and on any computer. The console does not give any errors at all

![settings 945](https://user-images.githubusercontent.com/34086169/33360829-8547f630-d4a3-11e7-8727-d2b89d0865fa.jpg)

However, if I click on the top right "My Account" the navigation bar now works and I can browse thru all the pages. However, once I click on the Dashboard, the issue with the navigation bar occurs again. 

![settings 946](https://user-images.githubusercontent.com/34086169/33360857-a7792274-d4a3-11e7-85a7-bb345f6366d9.jpg)

Anyone have any thoughts on what it could be? Thanks in advance.

**Comment by ilackskills** [comment]
That is an old version, is there a reason you are not using the one pulled from here?

**Comment by trainwreckjvbo** [comment]
I experienced this bug, it's not a big deal, I don't know why it happens. However, this is a really old version, if you can, try to use the Github version.

**Comment by CCoruble** [comment]
Hello,

Having the same issue with last version from git !
Dashboard seems to be freezed when going on "/home.php" for both admin and client account !
Moreover all link on the interface seems to go to same page "/home.php", I saw this when passing mouse over each link.

HOWEVER !! Only "MyAccount" and "Logout" works, and when I go to "MyAccount" then the interface works again !

Conclusion => Seems like whole interface is frozen only when going on "Dashboard" and so going on "/home.php"

Any idea why or any quick & dirty fix ?

**Comment by ilakskill** [comment]
Sounds like a js issue.  Make sure the file are loading correctly.

**Comment by tit0n** [comment]
Apparently home.php doesn't load properly because of the following error: 

> Call to undefined function: simplexml_load_string()

You can either remove the following line from home.php

`<?php include(ROOT_DIR.'/home-news-widget.php'); ?>`

Or you need to install php-xml module
```
apt-get install php7.0-xml
service php7.0-fpm restart
```
