### ISSUE TITLE
no categories

### ISSUE THREAD

**Issue by zeroc1** [projectsend/projectsend#506]
Hello,

in Version r754 everything works well except the categories.
If I click in the menu on "categories" as user "systemadministrator" I get the following message:
"Your account type doesn't allow you to view this page. Please contact a system administrator if you need to access this function."

I think as systemadmin I have the highest rights ... whats the Problem? 
Do I forgot something or is some setting not or wrong set? 

I would be very grateful for an indication :( ....

**Comment by mschop** [comment]
@zeroc1 does the problem still exist in latest release?

**Comment by mschop** [comment]
@zeroc1 I was not able to reproduce this in the latest release. I the problem persists, do not hesitate to reopen the issue. Thanks!
