### ISSUE TITLE
CSS problem

### ISSUE THREAD

**Issue by hubthomas** [projectsend/projectsend#523]
Hi, after using my ProjectSend platform, CSS changed from itself. I replaced by the defaults one and cleared the cache of my browser but the problem persists. 

Could you help me figure out where my problem come from ? 

Using the r754 version. 

Thanks

**Comment by ignacionelson** [comment]
Hello!
Looks like one or more css files are not loading.
Please check out the browser's console to see if there are any warnings regarding this and let me know!

**Comment by hubthomas** [comment]
@ignacionelson Hi, 

No errors in the console except those ones : 

![capture d ecran 2018-02-26 a 08 54 23](https://user-images.githubusercontent.com/36629575/36658881-c162d8c2-1ad2-11e8-9392-1b7c56beb5f6.png)

**Comment by hubthomas** [comment]
I have made a new ProjectSend platform and I am admin however, I can't access the categories page, like there is a problem with my ID when I click on My account after that. 

![capture d ecran 2018-02-26 a 16 41 53](https://user-images.githubusercontent.com/36629575/36679844-8be824da-1b14-11e8-8241-9f5b52731e09.png)
![capture d ecran 2018-02-26 a 16 45 40](https://user-images.githubusercontent.com/36629575/36679845-8c10127e-1b14-11e8-9f3a-75d72566fae1.png)

The problem is probably from my Database ?
