### ISSUE TITLE
Activity graph issue BUG

### ISSUE THREAD

**Issue by GitGoppy** [projectsend/projectsend#543]
The activity graph on projectsend works fine until I change 15 days to 30 days or 60 days, then the graph just gets blank and i need to refresh the page to fix it.

**Comment by ignacionelson** [comment]
Hello! Can you please check the browser's console for errors? Looks like ajax function that returns the data is being stopped.

**Comment by ignacionelson** [comment]
Are you calling the rocket.min.js file? It returns a 404

**Comment by ErikV2000** [comment]
cloudflare is using the rocket.min.js file, it's used for speeding up javascript but i disabled it so my web apps don't break, The rocket.min.js file is still present altough it's function is disabled. The file is fetched from cloudflare servers with a session bound one time link, that is why you are getting a 404.

**Comment by ignacionelson** [comment]
Oh, I didn't notice it was from cloudflare, sorry.
Does this happen if you use files locally?

**Comment by ErikV2000** [comment]
My server is public, it's not local.

**Comment by ErikV2000** [comment]
![image](https://user-images.githubusercontent.com/31779285/38917715-daa2a1d2-42eb-11e8-9d43-bfb0050d2fca.png)

**Comment by ignacionelson** [comment]
Sorry, by local I mean the js files loaded from your server, in the includes/js directory of projectsend, and not via cloudflare

**Comment by ErikV2000** [comment]
Yes it still happens, the files are always loaded from the includes.js, can you reproduce this bug or is it just me?

**Comment by mschop** [comment]
Could you please try deactivating CloudFlare completely for the whole domain. As I cannot reproduce this bug.

**Comment by ignacionelson** [comment]
Flot has been replaced with chart.js. This is solved.
