### ISSUE TITLE
Email related problem

### ISSUE THREAD

**Issue by gaspolo** [projectsend/projectsend#558]
Hi to all , i have install the last version of projSend , on my debian apache php and mysql last version, everithins seems ok,

Only problem in on email sistem,  i try every combination:
phpmailer , sendmail , exim4 smtp , postfix, 
And in each case, i receive ONLy email of new user to Admin email , 
So all new user that register through registration form
xxxwebsite/register.php   (public registration form) , ( after i need to activate manually )
they did not receive email registration,  why?

i try also debug phpmailer , but dont say error.. everything seem good
log from sendmail:

 when some one register on my site:

root@test:/var/log# cat mail.log
May  3 14:17:53 test sm-mta[7815]: w43IHro7007815: from=<,myEMAIL>, size=2554, class=0, nrcpts=1, msgid=<d7cbde71ad348f98b834d90d17cc0b0d@MYIP>, proto=ESMTP, daemon=MTA-v4, relay=localhost.localdomain [127.0.0.1]
May  3 14:18:57 test sm-mta[7817]: STARTTLS=client, relay=gmail-smtp-in.l.google.com., version=TLSv1/SSLv3, verify=FAIL, cipher=ECDHE-RSA-AES128-GCM-SHA256, bits=128/128
May  3 14:18:57 test sm-mta[7817]: w43IHro7007815: to=<USEREMAIL>, delay=00:01:04, xdelay=00:01:04, mailer=esmtp, pri=122554, relay=gmail-smtp-in.l.google.com. [74.125.197.27], dsn=2.0.0, stat=Sent (OK 1525371558 a81si14656643pfg.200 - gsmtp)

ANd all seems OK, Admin receive registration email...
But the user no.

and when i activate this user , the user will not receive email , but i think is a problem of projectsand ,because on log on my server ther is no email outside log.

**Comment by TheShaft72** [comment]
I'm having the same issue, the creation of system accounts or client accounts as a system user will send the welcome email.

When self registration is enabled and approved automatically or approved by an administrator it does not send the Welcome email message. 

There is nothing in the logs on my SMTP gateway to indicate an attempted connection for the client Welcome message when self registration is happening but I do see the connection to notify the site administrator of the new client registered and also when adding the client as a system user I can see the SMTP communication for the welcome message

I have updated a few of the php files with the latest versions from here I started with version is r1053 but have replaced the following files with the latest versions.
clients-membership-requests.php
clients-form.php
clients-edit.php
clients.php
I was hoping this had already been fixed and was located in one of these files, this doesn't seem to be the case.

Any ideas / suggestions / fixes ?

**Comment by gaspolo** [comment]
i have made a modify on register side... and change the codethat:  when someone register, the system send mail to ADMIN, now  when someone register ,system send mail to admin and register email. ( 2 email )

**Comment by gaspolo** [comment]
i change this: in register.php

 /**
                         * Prepare and send an email to administrator(s)
                         */
                        $notify_admin = new PSend_Email();
                        $email_arguments = array(
                                                                                        'type'                  => 'new_client_self',
                                                                                        'address'               => $add_client_data_email,
                                                                                        'username'      => $add_client_data_user,
/**                                                                                     'address'               => ADMIN_EMAIL_ADDRESS, **/

--------------
explain:
remove or comment this:   'address'               => ADMIN_EMAIL_ADDRESS
add:                                     'address'               => $add_client_data_email,

now new user receive email.

**Comment by TheShaft72** [comment]
This doesn't really solve the problem of sending an email when the account has been approved, all this is doing is changing who gets the new client registration email, so instead of the administrator getting the email the client now gets this email. Since I need to approve all the accounts this wont work as I want them to be notified once it has been approved not when they have requested it. This is a nice feature to add so they know they have requested an account though so I may leave it, but I need to be able to have the system automatically email them once the account is approved and active.

**Comment by TheShaft72** [comment]
I worked out the issue, well a work around, I removed the line 
'preview'		=> true,
 from client-requests.php

from this section of client-requests.php
 * 3- Send email to the client
 */
/** Send email */
$processed_requests = $process_requests['memberships'];
$client_information = get_client_by_id( $client['id'] );

$notify_client = new PSend_Email();
$email_arguments = array(
'type'=> $email_type,
'username'=> $client_information['username'],
'name'=> $client_information['name'],
'addresses'=> $client_information['email'],
'memberships'=> $processed_requests,
'preview'=> true,
);
$notify_send = $notify_client->psend_send_email($email_arguments);

**Comment by jeff-fab** [comment]
I ran into the same issue and found that in addition to changing preview to false, I needed to change send-email.php so that the value of $this->addresses comes from $arguments['address'] instead of $arguments['addresses'].  Not sure if it's a perfect fix or why you wouldn't have needed the same, but I found that $arguments['addresses'] had no value.

	function psend_send_email($arguments)
	{
	   
	   
	```
	/** Generate the values from the arguments */
		$this->preview		= (!empty($arguments['preview'])) ? $arguments['preview'] : false;
		$this->type			= $arguments['type'];
               // below is modified
		$this->addresses	= (!empty($arguments['address'])) ? $arguments['address'] : '';
		//error_log($this->addresses);
		$this->username		= (!empty($arguments['username'])) ? $arguments['username'] : '';
		$this->password		= (!empty($arguments['password'])) ? $arguments['password'] : '';
		$this->client_id	= (!empty($arguments['client_id'])) ? $arguments['client_id'] : '';
		$this->name			= (!empty($arguments['name'])) ? $arguments['name'] : '';
		$this->files_list	= (!empty($arguments['files_list'])) ? $arguments['files_list'] : '';
		$this->token		= (!empty($arguments['token'])) ? $arguments['token'] : '';
		$this->memberships	= (!empty($arguments['memberships'])) ? $arguments['memberships'] : '';
```

**Comment by ignacionelson** [comment]
Fixed in r1265
