### ISSUE TITLE
wont show statistics and recent activity

### ISSUE THREAD

**Issue by rcs27** [projectsend/projectsend#560]
Hi there,
After upgrade from r754 to r1053, the statistics and recent activities fields on dashboard wont load up, attaching image for better understanding, (file permission is set with 644 value)
thanks for any help!
*** Also happen with Fresh new Installation. same error
![errorprojectsend](https://user-images.githubusercontent.com/37030044/39732577-19d4a03a-5223-11e8-82c8-bac6a596a9be.jpg)

**Comment by mschop** [comment]
@rcs27 this seems like a file permission problem and not a bug in ProjectSend. Could you please verify, that you have correctly set the file permissions for the files, that cannot be loaded? You see the files, that could not be loaded (because forbidden) in the network tab of the browser debugger.

**Comment by rcs27** [comment]
Hi, I finally found the issue, all permission for the files were fine, the problem was fixed once I disabled  ModSecurity from my cPanel.
