### ISSUE TITLE
File size 2GB+ wrong.

### ISSUE THREAD

**Issue by crashff00** [projectsend/projectsend#57]
I dug into the code in functions.php and went back to the stackoverflow source. the code does not work for files over 2GB. I have 2 files -4.2GB and 5.1GB that are showing up as 22.71 MB and 957.01 MB.

There is an alternative function I would propose located here: https://github.com/jkuchar/BigFileTools

**Comment by crashff00** [comment]
It appears that not only are file sizes over 2GB showing up wrong, but it is also corrupting the downloads in the process.. I uploaded a 4.4GB file, which was displayed as 470MB, and when I downloaded the file, it stopped at the 470MB which resulted in a corrupt file, rather than the complete 4.4 GB file

**Comment by lenamtl** [comment]
I remember there was an issue with opera browser..
Have you set the correct value
The value is in mb  sys.config.php file

also check the PHP.ini values
php_value upload_max_filesize 
php_value post_max_size 
memory limit

Here are some old archived issue about this, you will maybe found a temporary solution.
https://code.google.com/p/clients-oriented-ftp/issues/list

**Comment by crashff00** [comment]
I found those too. I'm using IE 11, Chrome, and Firefox, and all have the same result. The sys config php file is set for 8192, as well as the php ini files.  The problem only occurs once the file exceeds 2GB, because at that point, Project send records the file size wrong in the database, and the corrupt file matches the incorrect size recorded.

**Comment by VincentSC** [comment]
Is this resolved?

**Comment by kkplein** [comment]
It works fine for me, with a 4.4G iso image.

**Comment by lukas-runge** [comment]
I have the same Problem. At a File size of 2.147.483.647 Bytes he stops increasing file size but pretends to still be uploading. Resulting in a corrupt file being uploaded. Uploading thru FTP works just fine. I have adjusted my php.ini files to the correct file size by now, does not change the situation.
I would really like to see this bug fixed.

Thanks for the great work developing ProjectSend! Keep up the great work and support :+1: 
Lukas

**Comment by lenamtl** [comment]
I'm closing this, let us know if you still have this issue
