### ISSUE TITLE
Unable to limit download speed

### ISSUE THREAD

**Issue by dalla89** [projectsend/projectsend#580]
With R1083 I'm unable to limit the download speed.

I tried a lot of values of usleep() inside process.php but it seems to have no effect on download speed.
With R754 I'm sure it was working, but I'm not sure on which version it changed.
I will do some test during the weekend to check with an older release.

Is there any other way I can try to limit the download speed?

* ProjectSend version: r1083
* php version: 7.0.30
* MySQL version: 5.7.22

**Comment by mschop** [comment]
I would be very careful, limiting the download speed this way. ProjectSend blocks a complete PHP worker while sending the file to the client. If you use usleep to set the process to sleep, you could run out of worker when having many requests.

Instead you should use a server configuration for this. E.g. you could use the apache module mod_bandwidth or other equivalents.

If you would nevertheless go this way (to hell ;-)) search for ` //usleep(1000000); //Reduce download speed` in the file process.php. Uncomment the line and set the value you like. This should reduce the bandwidth, as you imagine.
