### ISSUE TITLE
online doc viewer and no download option

### ISSUE THREAD

**Issue by johanpeters** [projectsend/projectsend#583]
Implement a online / internal document viewer and no download option.
more secure that way.. to protect the user for " user errors".. say.. login on public computer.

or encryption of the documents and user gets a unique password when he downloads a file.

**Comment by mschop** [comment]
Hi @johanpeters,

I'm not sure, whether I understand you request. You are saying 

> implement a online / internal document viewer and no download option

does that mean, that you would like to display a previews instead of providing a download to the client?

The rest does not make sense to me. Could you please explain your request more detailed? Thanks right now!

**Comment by johanpeters** [comment]
Offcourse.... 
if documents are online to read (secure).. than the user does not have to download the articles.
Lets see your at a public library.. and whant to access a document.. you don't whant that the user must download the file on a public / schared computer.. anyone else can read that article after you left.. so default read article online, optional download the file (perhaps incl. authorisation) / file encryption of the document so he must use a generated password to open that file..
generated for each document... 

so make download option less attractive.. 

all of this as option to configure.. for some users no issue.. for others a major issue..

I am living inside the EU.. and GDPR is very stricts on privacy.. 
my sister is looking for a sollution to share documents with here clients (healthcare).. 
ProjectSend would be a greate sollution for that.. 
Perhaps a special version / setting for Privacy envoirement.. so that special settings are only needed / availible for those users ..
if Privacy is Enabled then
- 2FA
- view online only
- password generated for download
- force password change on first logon
- etc.etc.

**Comment by mschop** [comment]
What you are requesting is a preview functionality. I created a new Issue #595 as a collective issue for file previews. Because of this I close this issue.

Please note: even if the file is only previewed. The browser cache could contain the file, even if it was only previewed. If you have such strict policies, you should ensure the client cache is disabled through .htaccess rules.

**Comment by bobylapointe63** [comment]
> Hi @johanpeters,
> 
> I'm not sure, whether I understand you request. You are saying
> 
> > implement a online / internal document viewer and no download option
> 
> does that mean, that you would like to display a previews instead of providing a download to the client?
> 
> The rest does not make sense to me. Could you please explain your request more detailed? Thanks right now!

it would be very useful to imagine if you have lots of documents if you have a preview it would be easier to download the right file right?

**Comment by johanpeters** [comment]
Online document viewer and NOT a download option
So the file stays in projectsend and not externally saved.. 

- 2FA.. for CD e 2fa configuration for users to secure user access.. only when 2fa is configured than access 

Option for download files.. regenerate the pdf with security (no printing,  generated password)
