### ISSUE TITLE
r1053: Localization / Language selector missing

### ISSUE THREAD

**Issue by maybor** [projectsend/projectsend#592]
## Type

[x] Bug report

[] Feature request

### Description of the problem

Hello Ignacio
first of all, r1053 seems to fantastic! Thank you for your efforts!
One thing: I remember there was a language option in r756. Can't find it anymore in r 1053. I have built a rough german translation and copied de.mo and de.po into the directories folder, but this doesn't help. Next I tried to define the language in sys.vars.php, but unfortunatley without success. Could you please give me hint how to enable languges in r1053? Once my german files are complete I will contribute them.
Cordialmente
maybor

### Environment

* ProjectSend version: r1053
* php version: 7.1.x
* MySQL version: 5.6.x

**Comment by KILLERJC** [comment]
I followed the instruction and worked for me, i downloaded and completed the traduction of spanish(mx) in Transifex page, this are the instruction:

https://www.projectsend.org/how-to-use-translation-files/

The file where language is defined is /includes/sys.config.php

**Comment by maybor** [comment]
--SOLVED --
Hello KILLERJC
sorry for my late reply, don't know what I did wrong but now it's working as described! Perfect, thank you to all of you!
Best regards
maybor
