### ISSUE TITLE
Still an Issue - Database Restore from Ubuntu 14.04 to 18.04

### ISSUE THREAD

**Issue by LaurenAdelle** [projectsend/projectsend#599]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[X] Bug report

[] Feature request

### Description of the problem
I have an old server running Ubuntu 14.04 with the following key components:
• Apache 2.4.7
• Mysql 5.5.59
• PHP 5.5.9
• ProjectSend build 1022, upgraded from 754

The server is being retired and the projectsend information needs to be moved to a new Ubuntu 16.04 server with the following key components:
• Apache 2.4.29
• PHP 7.2.5
• Mysql 5.7.22

TO BE VERY CLEAR, CLEAN INSTALL OF PROJECT SEND WORKS PERFECTLY.  I CAN LOGIN WITH THE ADMINISTRATOR.

But then, I try to the following:
• use msyqldump to backup the database from the old server, and restore it to the new server
• straight SCP the file structure of project send (i.e. php files, uploads, client files, etc) exactly the same on the new server.
Now, when I try to login, I get  blank screen and it shows HTTP Server ERROR 500 on home.php according to web developer tools

What is missing or how can I fix this?  PLEASE HELP. I've been looking for a solution since January 2018.

There were instructions on another page that said to edit debug value in the sys.config.php file to true, but I could not find this line.  Instead I added this line, but still, no debug messages appeared.

### List the steps to reproduce the issue

1. Clean install Ubuntu 18.04 server with LAMP server features.
2. Create Database
• sudo mysql -u root -p
• create database projectsend
• create and grant privileges to a non root user
3. download new copy of project send from git or projectsend.org and make sure r1063 works properly and can access the database by logging in and creating users.
4. on old Ubuntu 14.04 backup database with
•mysqldump -u root -p projectsend > projectsend.sql
5. on new 18.04 run
• sudo mysql -u root -p -Dprojectsend < projectsend.sql
6. grant all privileges to non root user again

Attempt to login to projectsend on website.
Observed: white screen hang after entering username/password on projectsend login page.

### Environment

* ProjectSend version: r1063
* php version: 7.2.5
* MySQL version: 5.7.22

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by ignacionelson** [comment]
Hello!
I see that you closed the issue, were you able to solve the problem? Is there anything you need help with? Thanks!
