### ISSUE TITLE
use https FQDN for external clients. Breaks ProjectSend

### ISSUE THREAD

**Issue by jasonburkeman** [projectsend/projectsend#600]
## Type
Protocol Change. Site Access/

Ignacio,
Great product. I became lowest backer today!. Hopefully, I can do more later.
Sorry about Argentina in World Cup. :(

Please complete with an X between the brackets to indicate the type of submission.
This is an: Issue

### Description of the problem
I have ProjectSend running on Ubuntu 18.04. Comes up great. Works.
I have set up external DNS and an FQDN for external users.
Site: so you can see behavior:
https://watchfileshare.watchsystems.com (IP =208.75.1.153)

I am trying to use HTTPS (443) and have firewall rules and NAT working.
When ProjectSend redirects the FQDN to the BASE_URI, which is HTTP, it breaks the site.
I have tried simply putting "https://(site IP) in the Site URI in Options, but it breaks ProjectSend.
I have a Netscaler SSL offloading working. The site is port 80, Netscaler has the SSL cert and performs SSL offloading using 443. This seems to work. 
When externally testing: The HTTPS://(FQDN site name) changes to the HTTP  BASE_URI and breaks. No page displays, says "The page cannot be reached".
It tries to redirect and shows internal BASE_URI with or without the FQDN; when using https://208.75.1.153
### List the steps to reproduce the issue

1. I have tried changing the <VirtualHost = 443>, I have tried setting the site to https in Options.
2. I have tried using FQDN in the site uri as well. Error"The site cannot be reached."

### Environment

* ProjectSend version: r754
* php version: 5.6
* MySQL version: Mariadb101

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue
I am not that great at PHP. I am not a developer. It seems that it is somehow related to the BASE_URI.

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.
Thanks for any help.
Shawn Burke (jasonburkeman = online alias!!!!)

**Comment by ignacionelson** [comment]
Hello Shawn!!
First of all, thank you for your comments and your support through Patreon!

This might seem like something trivial, but have you tried reaching any file outside of ProjectSend using https on that FQDN? I mean, an absolute minimal test like uploading an HTML or image file to the root via SFTP.

**Comment by jasonburkeman** [comment]
DUUUUUUDE! You are my hero. You made me think. Ahhhhhh. maybe I need to work on the hosts file, make sure my names and <VirtualHost> configs were correct. It works!!! I am able to use https://watchfileshare.watchsystems.com under General Options. ... you can check it out if you want!!! It comes up and properly redirects the "Home.PHP" page.

Also, on a side, hopefully helpful note for you and anyone out there. 
This does not appear to perform SSL offloading when using Citrix Netscaler as a proxy for 80 > 443.
I had to local install the certificate and all works now.
thanks again. Good luck, I will spread the word.

Shawn Burke

**Comment by ignacionelson** [comment]
:D Glad that you found the solution!
