### ISSUE TITLE
Waiting to the server responding

### ISSUE THREAD

**Issue by nelsondcosta23** [projectsend/projectsend#607]
After few hours of prefect working, now when I upload something after I press upload

page "upload-process-form.php" shows up and if I press Save keep wating for the server...
Same when I create users.

But it works like 20 min ago -.-' only try to change language, already turn back that step.

### Environment

* ProjectSend version: r1053
* php version: 7.0
* MySQL version: MariaDB 10

OVH Performance Hosting

---

Some help? need more info?!

**Comment by nelsondcosta23** [comment]
Just reisntaled everything, and works fine again... 
Im wonder what happend

**Comment by ignacionelson** [comment]
Hello @nelsondcosta23 
Maybe a process was kept on the background and it never stopped its execution. If this happens again, then please check your php.ini timeout settings

**Comment by nelsondcosta23** [comment]
Hi Nelson, 

I might found out where is the problem, when I enable the SMTP mail config.
