### ISSUE TITLE
Unable to upload files to ProjectSend

### ISSUE THREAD

**Issue by kennyyeam** [projectsend/projectsend#609]
Hi,

I have installed the ProjectSend recently in my Windows Server 2008 with IIS platform. However, when I try to upload the files into ProjectSend. There's nothing inside "Manage Files" tab. Could you please advise what was going wrong?

Thanks,
Kenny Yeam

**Comment by lenamtl** [comment]
Hi, I will close this one.

You need some IIS help as I can see from your other questions ...
Check your IIS log and PHP logs
You may check Udemy tutorial on how to set IIS
