### ISSUE TITLE
Templates Are Blank

### ISSUE THREAD

**Issue by wolftone1916** [projectsend/projectsend#613]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[X] Bug report

[] Feature request

### Description of the problem

When switching to either one of the other 2 templates for the client view, it will only show a blank page when the client logs in instead of the template.

### List the steps to reproduce the issue

1. Switch to a template that is not default
2. View as a client or log in as a client

### Environment

* ProjectSend version: r1053
* php version: 7.0.29
* MySQL version:  10.2.13-MariaDB-log
--

### Related PR

___

**Comment by ignacionelson** [comment]
Hello! Please enable debug mode by setting the value to true on sys.config.php and see if you get any errors then. You could also look into the server's php error file for a clue. Let me know if you find anything!

**Comment by wolftone1916** [comment]
Will do, I'm heading to work now, I will do it this evening once I am home. Thank you for the prompt reply

**Comment by IB-Rahn** [comment]
Maybe it's the same problem as in [https://github.com/projectsend/projectsend/issues/518](url)?

**Comment by wolftone1916** [comment]
Where is that file located ignacionelson. I found one with that name but nothing in it for debug mode...

**Comment by wolftone1916** [comment]
with it set to true in the file sys.vars.php it gave this error when trying to load the template:

Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1210 Incorrect arguments to mysqld_stmt_execute in /home/slummy5/public_html/receipts/templates/common.php:192 Stack trace: #0 /home/slummy5/public_html/receipts/templates/common.php(192): PDOStatement->execute(Array) #1 /home/slummy5/public_html/receipts/templates/gallery/template.php(22): include_once('/home/slummy5/p...') #2 /home/slummy5/public_html/receipts/my_files/index.php(8): include_once('/home/slummy5/p...') #3 {main} thrown in /home/slummy5/public_html/receipts/templates/common.phpon line 192

**Comment by wolftone1916** [comment]
Any updates on this issue?

**Comment by IB-Rahn** [comment]
I guess there is too much work with the refactoring. Did you try the temporary solution from me?
