### ISSUE TITLE
Disable ckeditor does not work

### ISSUE THREAD

**Issue by Gerard64** [projectsend/projectsend#617]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[x] Bug report

[] Feature request

### Description of the problem

In options ckeditor is not enabled but it shows up in for example client group manager and all other places. Also in client group description the html tags `<p>` and `</p>` are visible.

### List the steps to reproduce the issue

1.
2.

### Environment

* ProjectSend version: r1053
* php version: 5.6.36-0+deb8u1
* MySQL version: 5.5.60-0+deb8u1

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by AlanReiblein** [comment]
I had the same problem to stop using ckeditor on groups description as on file descriptions
I have changed groups-form.php
line 47 
from
`			<textarea name="add_group_form_description" id="add_group_form_description" class="ckeditor form-control"><?php echo (isset($add_group_data_description)) ? html_output($add_group_data_description) : ''; ?></textarea>`
to
`			<textarea name="add_group_form_description" id="add_group_form_description" class="<?php if ( DESCRIPTIONS_USE_CKEDITOR == 1 ) { echo 'ckeditor'; } ?> form-control"><?php echo (isset($add_group_data_description)) ? html_output($add_group_data_description) : ''; ?></textarea>
`

**Comment by Gerard64** [comment]
That worked perfectly.
Thank you!
