### ISSUE TITLE
Delete whole active log is not working

### ISSUE THREAD

**Issue by Gerard64** [projectsend/projectsend#618]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[x] Bug report

[] Feature request

### Description of the problem

On the tools / action log page the option to empty all log items does not work. only per page i can delete log items.

### List the steps to reproduce the issue

1.
2.

### Environment

* ProjectSend version: r1053 
* php version: 5.6.36-0+deb8u1
* MySQL version: 5.5.60-0+deb8u1

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by WowHesTall** [comment]
There is an error in actions-log.php ("clear" instead of "log_clear") which prevents the deletion code from being executed.

**Comment by Gerard64** [comment]
The only relevant **clear** i found in this file is in switch `case 'clear':` wen i change this to log_clear it is still not working.

**Comment by WowHesTall** [comment]
That's the correct piece of code. I've just re-tested the fix and it's working for myself. Sorry I can't help you any further.

**Comment by Gerard64** [comment]
Thank you anyway WowHesTall.

**Comment by ignacionelson** [comment]
Thank you for the fix! Already applied and credited you @WowHesTall
