### ISSUE TITLE
Printing other users files

### ISSUE THREAD

**Issue by wolftone1916** [projectsend/projectsend#619]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[] Bug report

[X] Feature request

Is there a way for a user to login and print or rather download the images and files of other users? I want a user/admin to be able to login and download any users images as a zip file instead of each one separately.

**Comment by mschop** [comment]
Hi @wolftone1916,

this is not possible and not planned. See issue #549.

Best Regards
mschop
