### ISSUE TITLE
500 Error after logging in

### ISSUE THREAD

**Issue by quintingsnj** [projectsend/projectsend#623]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[X] Bug report

[] Feature request

### Description of the problem

I moved my site to a new host, same domain name. I have the database imported successfully, and have changed the sys.config.php file to reflect the new database location/login info. I get to the login page OK, but after logging in it generates a 500 error - but no entry in the logs (I know the logs are working, because there are other pages on that site that I had to fix, and there were errors in the error log for them until I fixed).

### List the steps to reproduce the issue

1. Go to site
2. login with admin creds, 500 error comes up

### Environment

* ProjectSend version: r1053
* php version: 7.2.7
* MySQL version: 5.7.23

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by WowHesTall** [comment]
I know it sounds too simple, but have you tried clearing your cache?

**Comment by quintingsnj** [comment]
That is simple...I hadn't thought of that...so just tried that, and still same issue....I'm going to try and re-download the zip file for ProjectSend and see if that works...maybe something is missing from my capture of the site on the old host...

Thanks.

**Comment by WowHesTall** [comment]
I also had some issues with my FTP client uploading in the wrong mode (ASCII/Binary). Do you happen to have a .htaccess file in the root dir? If so, I would try removing it temporarily.

**Comment by quintingsnj** [comment]
Tried removing the .htaccess file, same issue. I am uploading the entire zip (from a linux machine to a linux machine), and then unzipping, so I would think everything would still be intact....

Tried a reinstall, and same issue.

Thanks for the prompt responses.

**Comment by quintingsnj** [comment]
Can't even get a new install to work...different issues...must be a permissions thing maybe...the install goes fine, but the login page is weird, and once logged in, Once logged in, redirects to some weird location with our address in the location...but I didn't enter our address (physical address of business) into any field in the install...

Very strange...

Any idea if there are any special permissions needed anywhere? I have it world readable, and only owner writable - owned by apache user (www-data)....


Thanks,

Q

**Comment by quintingsnj** [comment]
Couldn't find anything related...at least not with a solution...

I did figure out though, that if I click on my name, it brings me to my account, and then all the menu items work. It seems that the menu items don't work when on home.php....

Any ideas? If I need to, I can open a new ticket...

Thanks!

**Comment by quintingsnj** [comment]
Got it fixed...needed to install php-xml
