### ISSUE TITLE
Slow login 

### ISSUE THREAD

**Issue by gonook** [projectsend/projectsend#624]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[] Bug report

[] Feature request

### Description of the problem

When trying to login in project send its loading slow dont know why i have uploaded 34 files after that its creating issue

### List the steps to reproduce the issue

1.
2.

### Environment

* ProjectSend version:
* php version:
* MySQL version:

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by mschop** [comment]
Hi @gonook,

your request is too general. This could have many reasons. Please provide more details to further issues. I close this issue, as it does not provide even the basic information. The minimum is to fill the issue form completely.

Best Regards
mschop
