### ISSUE TITLE
FEATURE REQUEST: CATEGORIES DISPLAY ON FILE LISTING PAGES

### ISSUE THREAD

**Issue by IRSCompliance** [projectsend/projectsend#628]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[] Bug report

[X] Feature request

### Description of the problem

Please be as clear as possible

### List the steps to reproduce the issue

1.
2.

### Environment

* ProjectSend version: r1053
* php version: 5.6
* MySQL version: 5.6.39-cll-lve - MySQL Community Server (GPL)

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by ignacionelson** [comment]
Hello!
Is this a request to add a column with the file categories to the Default template?

Thank you!

**Comment by IRSCompliance** [comment]
@ignacionelson 
Yes, template wide on "Default" template for both end users, account managers etc.

We are using the "Category" option heavily.

**Comment by IRSCompliance** [comment]
@ignacionelson 
Additionally, the category descriptions do not show elsewhere as well, which is important to our team/clients.

**Comment by ignacionelson** [comment]
All templates now allow filtering by category (since r1265).
