### ISSUE TITLE
Bug Report: Error 503 after uploading files

### ISSUE THREAD

**Issue by WildnerDesigner** [projectsend/projectsend#629]
### Type

This is a:
[X] Bug report
[] Feature request

### Description of the problem

After we uploaded a file, the page is loading very long and then we get a 503 error. We must close the browser and log in again. The file is uploaded correct.

Log error: [Wed Aug 29 09:38:53.870275 2018] [proxy_fcgi:error] [pid 453] (70007)The timeout specified has expired: [client 178.145.95.125:56382] AH01075: Error dispatching request to : (polling), referer: https://domain.com/upload-process-form.php

First intention: Increase limitation (see https://support.plesk.com/hc/en-us/articles/115000064929-Website-is-not-accessible-The-timeout-specified-has-expired-Error-dispatching-request-to)
We did this together with our hosting provider. He said, that he can increase the timeout to 10 hours and then the 503 error would appear. After the upload, the script doesn't give any response. There is no problem with the server.

### List the steps to reproduce the issue

1. Select file for upload
2. Manage file for upload (e.g. insert title or assign user)
3. After saving, the page is loading long time
4. In the end, a 503 error appears

### Environment

* ProjectSend version: r1053
* php version: 7.0.30-0+deb9u1
* MySQL version: 5.5.5-10.1.26-MariaDB-0+deb9u1

### Additional information

We checked it with SSL on and off.
We reinstalled the data of r1053.
The error also appears by creating another user.
We tested other PHP versions (5.6 and 7.2).

Any ideas? Thank your very much!

**Comment by WildnerDesigner** [comment]
We have solved the problem :)
We have implemented the sending of messages with SMTP. There we had the port wrongly indicated. For all actions when sending messages (eg file upload), the system has hung up. There was no error message (eg "SMTP mail failed"), so we did not get it directly.

**Comment by mschop** [comment]
Nice to hear, you solved the issue. If you have any further problems, don't hesitate to create a new issue.
