### ISSUE TITLE
& character not being treated properly in Descriptions

### ISSUE THREAD

**Issue by AlanReiblein** [projectsend/projectsend#634]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[X] Bug report

[] Feature request

When a "special" character (e.g. & )  is added to a description it is converted to its html representation but not translated back when displayed in default template or sent as a notification in a default email.
I am only interested in the ampersand & because we use it a lot. This did not occur in the previous version I was using (r583)

Example file description is 
This a cartoon of G&S 

This shows
This a cartoon of G&amp;S 
in the default template for client files

and

This a cartoon of G&amp;amp;S 

in the default email notification.

I use ckeditor for descriptions as without its even worse affecting newlines.

### List the steps to reproduce the issue

1. Edit a file so that the description contains an & e.g. "Gilbert & Sullivan file for client Steptoe & Sons"
2.Assign this file to a client.
3. View Files for client
4 Read email notification

### Environment

* ProjectSend version:
r1503
* php version:
7.2.7
* MySQL version:
5.0.12-dev - 20150407

**Comment by AlanReiblein** [comment]
above should be 

This shows
This a cartoon of **G&amp;amp;S** 
in the default template for client files

and 
This is a cartoon **G&amp;amp;amp;S** 
in the default email notification

**Comment by AlanReiblein** [comment]
It also happens with apostrophes'

**Comment by AlanReiblein** [comment]
I managed to fix my immediate problem but not sure if it's a true fix.
in functions/functions.php

function htmlentities_allowed

**I replaced line 742** 
`$description = str_replace($find, $replace, $description);`
**with**
`$description = str_replace($find, $replace, $description);`
`$description = str_replace(array('&amp;amp;','&amp;#039;','&amp;rsquo;'),array('&','&#039;','&rsquo;'),$description);`


It could be that all the allowed special characters that a user could type into a description
 could be added.


Alan

**Comment by ignacionelson** [comment]
Solved in r1265
