### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by abyss909** [projectsend/projectsend#635]
Please complete with an X between the brackets to indicate the type of submission.
This is a:

[] Bug report

[X] Feature request

Administrative tool to allow Data Base Backup / Export & Restore

**Comment by mschop** [comment]
Hi @abyss909,

there are enough tools out there for creating backups from PHP-Projects. I think there is no need to reinvent the wheel. Just use existing solutions.

Best Regards
mschop
