### ISSUE TITLE
Blank home page

### ISSUE THREAD

**Issue by outrecording** [projectsend/projectsend#646]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[x] Bug report

[] Feature request

### Description of the problem

I've been using Projectsend for a few years now without issue. But about a week ago I just get a blank white page at the login page. Looking at the source code, there's nothing there. I didn't have the most recent version installed so I thought maybe that was the issue. I updated to the most recent version and still have the same problem. 

To my knowledge nothing has been changed on my end and no cpanel or server upgrades on the host's end. 

Thanks for any help

### List the steps to reproduce the issue

1. Go to the projectsend page
2. White page

### Environment

* ProjectSend version: r1053
* php version: 5.6 (I tried switching to 7.0 with same results)
* MySQL version:   5.6.41 - MySQL Community Server (GPL)

**Comment by lenamtl** [comment]
Hi, 

from which version have you udpate?

right click / inspect and check if any error into the log

**Comment by fubian** [comment]
I experienced quite a similar issue: I have a fresh installation. I am able to login successfully but when I try to go to another page I only get a blank page as a response.

**Comment by ignacionelson** [comment]
Closing as no php details of the error hae been shared. Please reopen if this happens again.
