### ISSUE TITLE
Suggestion: Misc improvements ( SSL, download count)

### ISSUE THREAD

**Issue by diegologo14** [projectsend/projectsend#65]
Hello,
I actively use the project for a business. Here are a couple of things that I have done, and might help other users:

Download count: 
I have added the following code in the template.php to show how many times the file has been downloaded.

``` php
<h2><?php echo htmlentities($file['name']); ?></h2>
                                <?php  
//used for security so it only runs from an specific machine. 
// SECTION ADDED BY DIEGO 
if($_SERVER['REMOTE_ADDR']=='172.17.17.1') 
                                    {?><h2><?php echo 'Uploaded: '.$file['timestamp']; ?></h2><?php
                                        $file_download_query = "SELECT * FROM tbl_downloads WHERE file_id  = '".$file['id']."' ";
                                        //$file_download_query = "SELECT * FROM tbl_downloads WHERE file_id  = '10' ";
                                        $file_download_1 = $database->query($file_download_query);
                                        $file['DownloadCount']=0;
                                        while($count = mysql_fetch_array($file_download_1)) { $file['DownloadCount']++;}
                                        ?><h2><?php echo 'Download Count: '.$file['DownloadCount']; ?><./h2><?php
                                    }
?>
```

SSL:
Had an issue with a client that requested all their logins to be on secure connection. The migration from HTTP to HTTPS was not the simplest. 

Field systemuri had to be changed from http: to https. can this be a default?

File Purge:
The project is being used by a client that uploads hundreds of files a day. After a few months there are TONS of unneeded files.

I had to create a purge option. That deletes the files from the system based on a date. Not sure if you want to add this to the admin side:

``` php
<?php
if($_SERVER['REMOTE_ADDR']!='172.17.17.1') die('Not Allowed');
$servername = "localhost";
$username = "username";
$password = "password";
$dbname = "dbname";
// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
     die("Connection failed: " . $conn->connect_error);
} 
$sql = "SELECT  *  FROM tbl_files where expires =1 and timestamp < '2014-12-31 12:12:12' LIMIT 400";
//$sql = "SELECT  *  FROM tbl_files where uploader ='username'";
$result = $conn->query($sql);
if ($result->num_rows > 0) {
     // output data of each row
     while($row = $result->fetch_assoc()) {
 echo "<br>$row[id] : <strong> Link:<./strong> <a href='upload/files/$row[url]' >$row[url]<./a>- <.strong>Created:</strong> ". $row["timestamp"]. " " . $row["uploader"] ;
         $sql2="DELETE FROM tbl_files        WHERE id = '$row[id]' ";
         $result2 = $conn->query($sql2);
         $filetodel='upload/files/'.$row["url"];
         unlink($filetodel);
         echo " <strong>DELETED</strong><br>"; }
} else {
     echo "0 results";
}
$conn->close();
?>  
```

**Comment by diegologo14** [comment]
One more:
HTTPS checkbox in the admin page.
If checked the following command will run on index.php to force https
//base uri has to have the https url otherwise it will be an endless loop
if($_SERVER['HTTPS']!='on')header('Location:'.BASE_URI);

**Comment by lenamtl** [comment]
Thanks a lot :)

**Comment by Invictaz** [comment]
@diegologo14 Thanks for the script but I need something to purge automatically files with no filesize (like your client who uploads so much every day). Is this possible in a cronjob?

**Comment by lenamtl** [comment]
Yes you can use cronjob to do it and you can adapt it to your need.
You can always hire a dev for your custom code

**Comment by Invictaz** [comment]
@lenamtl Would you please be so kind to not answer the question. It isn't very cooperative.

**Comment by andreicaba** [comment]
Hey. I just changed BASE_URI from the database into "/" and seems to work eitherways. I'm asking the developers - is this not an acceptable solution?...

**Comment by ignacionelson** [comment]
@andreicaba it will probably work for the frontend, but a full url will help with functions that use this parameter from the php side

**Comment by andreicaba** [comment]
Which functions would be?... I want to use it in production. Is it safe to use it like this?...
I just want users to be able to:
 - upload files;
 - change their password.
And our Company to be able to
 - create/manage users;
 - manage groups;
 - download files;
 - download archives.

Would those work?... (for now, only download archives doesn't work, but no idea why - I am not use if it worked before I made the change I specified above...)

**Comment by ignacionelson** [comment]
Well, the url is defined as a constant called BASE_URI and used across the system several times. I don't think you'll have issues, but please give it a try and let me know if the features you need are indeed working!

**Comment by andreicaba** [comment]
By the way - everything works - only when sharing links, I have to manually add the full URL. All the features seem to work (only the "download as archive" doesn't - but it can't be related to this, as it was also not working before changing the BASE_URI).
Thanks and have a great time!...

**Comment by KitoKatGH** [comment]
> Well, the url is defined as a constant called BASE_URI and used across the system several times. I don't think you'll have issues, but please give it a try and let me know if the features you need are indeed working!

Hi there, Im having this issue and trying to locate the BASE_URI is defined, are you able to tell me?

**Comment by ignacionelson** [comment]
> > Well, the url is defined as a constant called BASE_URI and used across the system several times. I don't think you'll have issues, but please give it a try and let me know if the features you need are indeed working!
> 
> Hi there, Im having this issue and trying to locate the BASE_URI is defined, are you able to tell me?

Hi! It's on the options table in the database, the records has the name base_uri

**Comment by tshives26** [comment]
Is there any chance you could give a quick how-to set up HTTPS/SSL? Based on the thread above, it's not so obvious what needs adjusted to allow HTTPS to work. Currently, it breaks the css/formatting of the whole page if its using HTTPS:

https://i.imgur.com/vau1Ti8.png
https://i.imgur.com/SN3fjNe.png

**Comment by tshives26** [comment]
Is there any chance you could give a quick how-to set up HTTPS/SSL? Based on the thread above, it's not so obvious what needs adjusted to allow HTTPS to work. Currently, it breaks the css/formatting of the whole page if its using HTTPS:

https://i.imgur.com/vau1Ti8.png
https://i.imgur.com/SN3fjNe.png

Before setting up certbot for HTTPS everything looks and works as intended.

To save time, I'm curious if this is the solution: https://www.cyberciti.biz/faq/how-to-setup-mariadb-ssl-and-secure-connections-from-clients/

@ignacionelson
