### ISSUE TITLE
Error uploading files with the same name as a previously uploaded file

### ISSUE THREAD

**Issue by AlanReiblein** [projectsend/projectsend#652]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[X] Bug report

[] Feature request

### Description of the problem
When I upload a file with the same name as another file previously uploaded, the file uploads and Then I am presented with the upload process page to add description etc..
When this is complete and the save button is pressed the upload process stalls.

**Update**
I am leaving my previous report as is but I have a more succinct view of the issue.

After intensive investigation I found that the "stall" occurs when there is a entry in the field original_url in the table files which is the same as the filename being uploaded. This occurred as the result of database upgrade with various iterations of the projectsend system and its attached database. 

A fix is outlined in the comments below.

### List the steps to reproduce the issue

**Original report**
1.Select upload
2.Pick a file with the same name as a file previously uploaded (see fault01.PNG)
3. Start the upload process by clicking upload
4. Allocate the file and description etc. (see fault02.PNG)
5 Press the start button
6 The process stalls.(see fault03.PNG)

This process was reported to me by one of my users, I was unable to reproduce until I forced a stall by having a file to be uploaded held by an open process on the local machine.

I repeated the process again this time the file uploaded being given a filename of filename_1

I repeated again and got filename_2 (see fault04.PNG)
I note that the first file had been uploaded and was resident on the server but not been renamed to the the system url. (see fault05.PNG)

The fault occurs when there is an original_url which is the same as this file uploaded. 
Is there a check somewhere that checks that original_url is unique within the table?
Although I am a very experienced systems programmer my MySQL database knowledge is skimpy.

This did not occur with my previous version r583 because the original_url would be unique as file renaming did not take place and the filestore check ensured this.

snapshots of screens
![fault01](https://user-images.githubusercontent.com/16509189/48983685-e2ec8e00-f0e9-11e8-8039-5ab7baae254c.PNG)

![fault02](https://user-images.githubusercontent.com/16509189/48983689-e3852480-f0e9-11e8-8d7a-de88b9cef8ae.PNG)

![fault03](https://user-images.githubusercontent.com/16509189/48983688-e3852480-f0e9-11e8-9712-581e5efbc210.PNG)

![fault04](https://user-images.githubusercontent.com/16509189/48983687-e2ec8e00-f0e9-11e8-980f-b366081bfce7.PNG)

![fault05](https://user-images.githubusercontent.com/16509189/48983686-e2ec8e00-f0e9-11e8-984f-3f447555e0fc.PNG)

### Environment

* ProjectSend version: r1053
* php version: 5.6.38
* MySQL version: 5.7.24

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by AlanReiblein** [comment]
I have had a look over the code involving the field original_url  and cannot identify where this clash would occur just that it does every time. I have got a work around for my system although the action is not ideal and not a proper fix.

In **process-upload.php** lines 59-70
`// Make sure the fileName is unique but only if chunking is disabled
if ($chunks < 2 && file_exists($targetDir . DIRECTORY_SEPARATOR . $fileName)) {
	$ext = strrpos($fileName, '.');
	$fileName_a = substr($fileName, 0, $ext);
	$fileName_b = substr($fileName, $ext);

	$count = 1;
	while (file_exists($targetDir . DIRECTORY_SEPARATOR . $fileName_a . '_' . $count . $fileName_b))
		$count++;

	$fileName = $fileName_a . '_' . $count . $fileName_b;
}`

I changed to 
`// Make sure the fileName is unique but only if chunking is disabled
if ($chunks < 2 && file_exists($targetDir . DIRECTORY_SEPARATOR . $fileName)) {
	$ext = strrpos($fileName, '.');
	$fileName_a = substr($fileName, 0, $ext) . "_" . date('Y-m-d-H-i-s');
	$fileName_b = substr($fileName, $ext);
	// changes to timestamp rather than just increment
	if(file_exists($targetDir . DIRECTORY_SEPARATOR . $fileName_a . $fileName_b)){
		$count = 1;
		while (file_exists($targetDir . DIRECTORY_SEPARATOR . $fileName_a . '_' . $count . $fileName_b))
			$count++;
		$fileName = $fileName_a . '_' . $count . $fileName_b;
	}else{
		$fileName = $fileName_a . $count . $fileName_b;
	}	
}
`

This is not ideal as the timestamp will only come into play if a file does exist on the filestore. So if there has been another file with an original_url same as the one being uploaded the system will still stall. 


Hopefully this is a rare occurrence.

**Comment by AlanReiblein** [comment]
At long last I have found where this fault is situated and a solution
It is in file **upload-process-form.php**
at lines 112 to 129
`/**
 * Make an array of file urls that are on the DB already.
 */
$statement = $dbh->prepare("SELECT DISTINCT original_url FROM " . TABLE_FILES);
$statement->execute();
$statement->setFetchMode(PDO::FETCH_ASSOC);
while( $row = $statement->fetch() ) {
	$urls_db_files[] = $row["original_url"];
}`


This a  sequence to obtain an array of urls to check if they names are already in the database.

Now with the new code of time-stamping and hashing filenames to be stored on the server and actually on the database the check this array is used for is probably redundant (except for legacy databases) but that is for further investigation.

From my investigation I believe the field **original_url** now is only used to be able to reproduce the filename for download purposes.
It is the field url that should be used for the check of files resident on the server.  But I do not 

So the lines 112 - 129 should read:-

`/**
 * Make an array of file urls that are on the DB already.
 */
$statement = $dbh->prepare("SELECT DISTINCT url FROM " . TABLE_FILES);
$statement->execute();
$statement->setFetchMode(PDO::FETCH_ASSOC);
while( $row = $statement->fetch() ) {
	$urls_db_files[] = $row["url"];
}`


I would hope this will be incorporated in the next release, (after verification).

**Comment by ignacionelson** [comment]
Thank you!! I've just applied this fix to the legacy branch and it will be available on the next release.
