### ISSUE TITLE
Advisory from Netsparker - ProjectSend r1053 - Reflected XSS

### ISSUE THREAD

**Issue by DanielBishtawi** [projectsend/projectsend#653]
Hello,

While testing the Netsparker web application security scanner we identified a Reflected XSS vulnerability in ProjectSend. Can you please advise whom shall we contact to disclose the vulnerability details so it can be fixed?

Please email me at daniel@netsparker.com for the technical details.

Looking forward to hearing from you.

Regards,

Daniel Bishtawi
Marketing Administrator | Netsparker Web Application Security Scanner

**Comment by kkplein** [comment]
A week... and no response yet... making us feel uneasy about how secure ProjectSend really is. Such a great project, we love and use it, but really more presence from the developers is needed here, specially when it comes to security reports...
