### ISSUE TITLE
Password bug

### ISSUE THREAD

**Issue by JeffO12** [projectsend/projectsend#655]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[x] Bug report

[] Feature request

### Description of the problem

Please be as clear as possible

### List the steps to reproduce the issue

1. create new user
2. welcome email is sent

### Environment

* ProjectSend version: R1053
* php version: latest
* MySQL version: latest

### Additional information

Sorry I am newer user and found out I was doing something wrong. Don't know how to delete this.

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by mschop** [comment]
> Sorry I am newer user and found out I was doing something wrong. Don't know how to delete this.

@JeffO12  No problem. I close the issue for you.
