### ISSUE TITLE
Main Menu not working after login

### ISSUE THREAD

**Issue by s0n0s** [projectsend/projectsend#659]
## Type
[X] Bug report

[] Feature request

### Description of the problem

After the login, the (lateral) main menu does not respond to any click. It works only after clicking on the My Account button. From there, if I come back (by clicking on the Dashboard button), it does not work again.

### List the steps to reproduce the issue

1. log in
2. try to click a button on the side menu

### Environment

* ProjectSend version: r1053
* php version: PHP 7.2.10-0
* MySQL version: 8.0.13

### Additional information

ubuntu0.18.04.1

**Comment by kkplein** [comment]
Did you install php-xml..?

**Comment by s0n0s** [comment]
Nope. After installing it, it works.
Thanks.

**Comment by ignacionelson** [comment]
@kkplein Thanks for the tip. News retrieving will be disabled in the next release if the module is not enabled.
