### ISSUE TITLE
each action takes exactly 60 seconds only under admin account

### ISSUE THREAD

**Issue by onlinestatements** [projectsend/projectsend#661]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[X] Bug report

[] Feature request

### Description of the problem

When I log into my admin account it takes exactly 60 seconds to load the file list.
Exactly 60 seconds to upload a file, exactly 60 seconds for file assignation.
When I log in as a regular user everything is instant.
It was fine yesterday.
Nothing has been modified on the website in weeks.
I have rebooted the server and MySQl server with no difference.
The rest of the website is functioning just fine.
The file list is only set to display 100 files.
I deleted a lot of old files about a month ago and dramatically reduced the database size.
I tried to run repair database under WHM but it says it is incompatible with the repair.

Id    | User | Host | db | Command | Time | State | Info
520 | onlinest_upl | localhost | onlinest_upl | Sleep | 54 |   | NULL
523 | root | localhost | NULL | Query | 0 | init | SHOW PROCESSLIST

It's like it sleeps for 60 seconds everytime the MySQL database is called on.

### List the steps to reproduce the issue

1. Click Manage My files, upload files or anything that reads or writes to the MySQL database.
2.

### Environment

* ProjectSend version: R754
* php version: 7.0
* MySQL version: 5.7 I think?

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by onlinestatements** [comment]
Never-mind,
It ended up being some problem with my webhost.
I can post the resolution to the cause as soon as I can.

**Comment by onlinestatements** [comment]
The webhost said:
We rebuilt the php and Apache configuration files by executing the following command:
/scripts/php_fpm_config --rebuild 
Then we restarted the HTTPD service and the issue has been resolved.

**Comment by mschop** [comment]
@onlinestatements as the problem seems to be solved, I close the issue.
