### ISSUE TITLE
Projectsend loading very very  slow

### ISSUE THREAD

**Issue by GiuCanda123** [projectsend/projectsend#662]
Projectsend loading very very  slow the backend is impossible to use every page takes 2 minutes to open!!!

**Comment by ChanOP** [comment]
Same problem to me. 
"Waiting time" is about 80-180 secs for every page load with logged in as Administrator user.

If I log in with normal user then the site is fast so only administator account is affected. Logging out from Admin user tooks 2-3 minutes too.

**Comment by 3rdfloordesign** [comment]
Same problem, anyone know how to fix this issue?

**Comment by jellovator** [comment]
Same...

**Comment by rpslivex** [comment]
I believe I have figured out and solved the issue.  I noticed 2 things while experiencing this issue:
1st...when logged in as admin, I see "waiting for mywebsite .  com" this right away from experience leads to DNS (resolution issues), especially when my projectsend folder is the only app on my site doing this.  (So it ain't my site or server)

2nd...I found myself here, trying to investing this same issue.  So I tried to click on the actual website projectsend.org and it doesn't even load, no shock the error is "ERR_NAME_RESOLUTION_FAILED".

What is happening (and exactly explains why this happens only to the admin user) is that when you login as admin the software is trying to "call home" to the projectsend website, which is not going to resolve.  The delay is essentially your server timing out, then your page loads.

Fix:
-Navigate to the install/root directory of where you installed ProjectSend, edit this file:
**sys.vars.php**

Comment out any calls to projectsend website.  A simple **_/*_** in front of the entries to look like this below:
```
Line 62: /* define('NEWS_FEED_URI','https://www.projectsend.org/feed/');
Line 72: /* define('UPDATES_FEED_URI','https://projectsend.org/updates/versions.xml');
Line 222: /* define('DONATIONS_URL','https://www.projectsend.org/donations/');
```

**Comment by rpslivex** [comment]
> Same...



> Same...

Guess I could have quoted you incase it sends out a notification on replies by quote.  Either way, the solution above works.

sys.vars.php was being called by home.php.  Wouldn't think any other file would be calling those URLs.  If they are, it's going to be same thing, find the php file trying to reach projectsend website (until that website ever comes up again, if it even does).

**Comment by ignacionelson** [comment]
Thank you everyone.
I'm having a lot of trouble with my hosting lately, and looking into moving PS's site somewhere else.
Sorry for the issues that this is causing you :(

**Comment by rpslivex** [comment]
> Thank you everyone.
> I'm having a lot of trouble with my hosting lately, and looking into moving PS's site somewhere else.
> Sorry for the issues that this is causing you :(

I presume you could verify then my relatively sloppy work around would be valid in the mean time.  Works for me, but I know some ppl don't like editing files if it's not proper way to do it.

**Comment by ignacionelson** [comment]
Indeed, the problem is the update checker and the news widget trying to get the info from the site. This is fixed on the upcoming version by using a cache, and loading data conditionally.

If your workaround is fixing this for you now, great! :) Hopefully you won't need it in the future!

**Comment by Korenchkin** [comment]
Hello,just to inform fix still works on latest version,i had problems with slow loading,includes/app.php commenting 3 uris and works like charm...i have ipv4 only,if that matters

**Comment by mayk78** [comment]
> 

works like a charm :-)

**Comment by ignacionelson** [comment]
This should help with this issue
https://github.com/projectsend/projectsend/commit/7d3c8120cc24fcb2f2b7084571620cb27582740d

**Comment by EnMaster** [comment]
> I believe I have figured out and solved the issue. I noticed 2 things while experiencing this issue: 1st...when logged in as admin, I see "waiting for mywebsite . com" this right away from experience leads to DNS (resolution issues), especially when my projectsend folder is the only app on my site doing this. (So it ain't my site or server)
> 
> 2nd...I found myself here, trying to investing this same issue. So I tried to click on the actual website projectsend.org and it doesn't even load, no shock the error is "ERR_NAME_RESOLUTION_FAILED".
> 
> What is happening (and exactly explains why this happens only to the admin user) is that when you login as admin the software is trying to "call home" to the projectsend website, which is not going to resolve. The delay is essentially your server timing out, then your page loads.
> 
> Fix: -Navigate to the install/root directory of where you installed ProjectSend, edit this file: **sys.vars.php**
> 
> Comment out any calls to projectsend website. A simple **_/*_** in front of the entries to look like this below:
> 
> ```
> Line 62: /* define('NEWS_FEED_URI','https://www.projectsend.org/feed/');
> Line 72: /* define('UPDATES_FEED_URI','https://projectsend.org/updates/versions.xml');
> Line 222: /* define('DONATIONS_URL','https://www.projectsend.org/donations/');
> ```

This solve my issue.
In the new version, is in `includes/app.php` at lines:
```PHP
define('SYSTEM_URI','https://www.projectsend.org/'); <- line 44
define('SYSTEM_URI_LABEL','ProjectSend on github'); <- line 45
define('DONATIONS_URL','https://www.projectsend.org/donations/'); <- line 46
define('PATREON_URL','https://www.patreon.com/ignacionelson'); <- line 47
define('OPENCOLLECTIVE_URL', 'https://opencollective.com/projectsend'); <- line 48
define('REVIEWS_URL', 'https://www.facebook.com/projectsend/'); <- line 49
define('TRANSLATIONS_URL', 'https://www.projectsend.org/translations/'); <- line 50
define('NEWS_FEED_URI','https://www.projectsend.org/serve/news'); <- line 113
define('UPDATES_FEED_URI','https://projectsend.org/serve/versions'); <- line 119
```

**Comment by nokel** [comment]
can confirm this is still a problem, and that commenting out those lines mentioned by EnMaster still fixes the problem.

**Comment by Downy** [comment]
Still a problem, but commenting out those lines breaks the page for me. 
I did a little testing and by setting only the UPDATES_FEED_URI var to 'localhost' the dashboard became very snappy, loading all pages near-instantly.

Line 119 in app.php
`define('UPDATES_FEED_URI','localhost');`

**Comment by CJastrzab** [comment]
in file /var/www/html/share/includes/updates.functions.php

comment all from line 18 to line 39 

when site on which version information are stored is unavailable or just busy, this affects loading time for all Projectsend installation this is STUPID

few words to developer @#$

**Comment by ignacionelson** [comment]
Hopefully this will help
[Added an option to stop ProjectSend looking for updates](https://github.com/projectsend/projectsend/commit/969370d9ec6c2ff106c0ec9bb5a91292b28f2298)

**Comment by blackjack75** [comment]
@ignacionelson Thanks for the option to disable this !

I took me a while testing my home connection to try to understand the cause of this. 

If I were to suggest a fix in code: - on first or second timeout , set a flag which disables this and show a banner on top to warn about the issue. If seems caching doesn't work as every request seemed slow. Not long minutes but quite painful (I am self hosting in Brazil so quite far from the original server and it is slow even when it is up, especially for something that is hosted one meter away :-)

I would categorize this as a major issue as it is one little detail that ruins the first impression of an otherwise great piece of software.

**Comment by blackjack75** [comment]
If you run projectsend in a LXC or virtual machine one simple option is to edit your /etc/hosts file and add
0.0.0.0 projectsend.org 

This is basically what pihole does. Instant resolution (and failure to load). Now the site is absolutely snappy and I don't have to modify the code and worry about it in future updates.

**Comment by ignacionelson** [comment]
thank you @blackjack75 . 
i've tried a few things on my end to improve loading times. using a cdn, moving to a better hosting provider, and even serving a static file instead of the data being dynamic. Other options i haven't tried yet are moving the data to a subdomain with a separate user and resources, and even going to a top tier provider like AWS, but I can't really afford that cost right now.
the timeout seems like a good idea.
I still wonder WHY retrieving a static file from Dreamhost could be THAT slow for some users. My test run great with those files at https://projectsend.org/serve/versions and https://projectsend.org/serve/news, and I'm even farther away (in Argentina).
Maybe I'm missing something?

**Comment by Korenchkin** [comment]
i have tried https://www.projectsend.org/donations/ opening from browser,~1-2s to load(just before redirect to patreon),
https://www.projectsend.org/feed/ is about 1s
https://projectsend.org/updates/versions.xml is under 1s(i would say ovet 500ms)
all tests repeatedly same..
i guess slow db,is there some way to cache results on server,some php cache or something?you probably don't need to regenerate donators on each load,one hour and precache(pregen) would be okay...

so these may add up,maybe you are reading them multiple times?(i'm not a programmer)
(czech,eu)

edit: https://projectsend.org/serve/versions about 3s on first try...maybe provider is using some kind of waf (web app firewall),or they have slow dns and won't serve until resolved?really strange,but to me it looks like best option is change provider(if they can't fix the problem) (sorry about that)
