### ISSUE TITLE
Redirect error after login

### ISSUE THREAD

**Issue by Philippe-M** [projectsend/projectsend#663]
## Type

[] Bug report

### Description of the problem

After login succefull i've this message :

```
{"status":"success","message":"
×<\/a>Login success. Redirecting...<\/div>","location":"http:\/\/aretzd.fr\/clients2\/home.php"}

```

### Environment

* ProjectSend version: r1053
* php version: 7.0 
* MySQL version: 5.5

**Comment by abyss909** [comment]
Did you apply a CSP policy recently?  I was encountering the same issue until I was able to generate a useful policy.  If CSP is your issue, this policy worked for me.  (Using XAMPP-Apache)

Header set Content-Security-Policy "img-src 'self'; script-src 'self'; script-src-elem 'self' www.gstatic.com; style-src-elem 'self' fonts.googleapis.com; connect-src 'self'; font-src 'self' fonts.gstatic.com;

**Comment by PHPcli** [comment]
Hi, I had the same problem. It is generated by the language files placed in the directory / lang / if we place fr.po and fr.mo we have the problem of redirection. By changing the file name to Francais_fr.po and mo it works. But if we define in sys.config.php "define ('SITE_LANG', 'fr'); or define ('SITE_LANG', 'Francais_fr') we find the concern.

**Comment by MazMarco** [comment]
I have also noticed this with correct username and password, but with message login error.
I have two languages installed. en and it.
To reproduce install PS and login. 
Go to options and enable Language detection. Save.
Logout and then login back-in.
You get the error.
