### ISSUE TITLE
index.php showing up in the downloads? Ummm.

### ISSUE THREAD

**Issue by sburkett** [projectsend/projectsend#677]
[X] Bug report

### Description of the problem

Pretty sure this isn't normal behavior. See the following image:

![Index bug](http://scottburkett.com/uploads/projectsend-index-bug.png)

### List the steps to reproduce the issue

I believe it started showing up after I reclassified some orphan files, if that helps. Wish I could add more here, sorry.

### Environment

* ProjectSend version: r1053
* php version: PHP/7.1.14
* MySQL version: 5.7.21

**Comment by lmsilva** [comment]
Out of the box, index.php in upload/files shows up under orphaned files.
You probably onboarded that file and it now shows up as one of the downloadable files.
You can safely remove it IF you have an .htaccess file in upload/files/ to protect against directory listing, though I wouldn't recommend it.

I think the easiest solution is to remove the file entry from your tbl_files.
