### ISSUE TITLE
E-mail notification couldn't be sent.

### ISSUE THREAD

**Issue by innerground** [projectsend/projectsend#678]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[X] Bug report

[] Feature request

### Description of the problem

E-mailing is not working, whatever option I chose, also, I cannot get any trace, even if I set php.ini to do so.

### List the steps to reproduce the issue

1. Create a user
2. Validate

### Environment

* ProjectSend version: r1053
* php version: 7.00
* MySQL version: 5.5

### Additional information

N/A

### Related PR

N/A

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by achleitner** [comment]
Try SMTP 

Host: smtp.gmail.com

username: youremail@googlemail.com

port: (TLS): 587

If you use 2 factor auth you have to use an app password: https://support.google.com/accounts/answer/185833?hl=en

Also make sure the from email is set up in gmail.

**Comment by achleitner** [comment]
i noticed i get all notifications except the new file upload ones by clients

password recovery etc works fine

**Comment by macintyres** [comment]
I'm experiencing the same issue. It was working until this week. I didn't change anything on the project send server. I did a system update then to test, I switched the previous smtp account to a gmail SMTP, following ahleitner's suggestion. Still no notifications coming through
Version
r1053 
Default upload max. size
2048 mb.
Server
Apache/2.4.18 (Ubuntu) 
PHP version
5.6.40-1+ubuntu16.04.1+deb.sury.org+2+will+reach+end+of+life+in+april+2019
Memory limit
128M
Max execution time
14400
Post max size
8M
Database
Driver
mysql
Version
5.7.25-0ubuntu0.16.04.2

**Comment by macintyres** [comment]
I did a fresh ubuntu 18.04 install and installed projectsend. Same result.
    r1053 
Default upload max. size
    2048 mb.
Template
    Default [Change]

Data

Files
    2
Clients
    0
System users
    1
Groups
    0
Categories
    0

System

Server
    Apache/2.4.29 (Ubuntu) 
PHP version
    7.2.15-0ubuntu0.18.04.1
Memory limit
    128M
Max execution time
    14400
Post max size
    8M

Database

Driver
    mysql
Version
    5.7.25-0ubuntu0.18.04.2

**Comment by Elfernovich** [comment]
> I have the same issue on version r1070. Did anyone found a solution or workaround to this problem?

Found a solution to the problem. The mail address defined in the username field for the SMTP configuration should match the "From" email address.

**Comment by protego-it** [comment]
Unfortunately I have the same problem. Everything works fine but the "new upload" messages.
Elfernovich's workaround doesn't work for me. I have the same address in "From" and SMTP.

**Comment by jeff-fab** [comment]
It seems like there are 2 issues in this thread.  Issue 1 is general email failure resulting in no notifications, which I think was resolved as an SMTP settings issue.  Issue #2 is specific to notification when a client uploads a file is not being sent to admin.

On issue #2:  I did some digging and think I see what's happening here.  We the clients in question created by themselves, or by your admin user?  It looks like the code in upload-send-notifications.php only send a notification to the administrator _that created_ the user in question.  So if your user created themself, then there would be no notification.  You can investigate this by looking at the records in tbl_users to see if created_by is blank. 

If this in fact is your issue, I can see 2 possible workarounds:
a.  update tbl_users set created_by = 'admin' where created_by = '' (substitute the name of the admin user that should get the notification!)
b. updates to the php file to force the system to send the email to a specified user in the event that there is no created_by for the client.  I am working on this code now but will need a little more time before I can share it.  Let me know if you would want this and if so I will try to do it sooner than later.

**Comment by protego-it** [comment]
Hi jeff-fab,
thanks for your reply. I create all users as administrator. Self registration is not allowed.

When i check the database, every system user is created by "NULL", only Clients are created by my admin user.
That might be the problem. 

I updated the table as you suggested, but still no notification for new uploads.
`UPDATE `tbl_users` SET `created_by` = 'Adminuser'` 

It would be great if you could fix this. 

Thank you.

**Comment by jeff-fab** [comment]
@protego-it That's interesting; if this is the case I don't think my fix will help.  Are you using version r1070?  
Can you send me:   select id,user,level,notify,active,created_by from tbl_users; ?

Below are the changes that I made to /upload-send-notifications.php; you would need to adapt them to your current situation.  



```diff upload-send-notifications.php ~/CODE/projectsend-1070/upload-send-notifications.php 
starting at line 94 in r1070 version of file:
< 		//JJF for each client, if the created_by is blank, then we force it to be the admin
< 		$this_createdby = $row['created_by'] ? $row['created_by'] : 'admin';
< 									//JJF Replace line
< 									//'created_by'	=> $row['created_by'],
< 									'created_by'	=> $this_createdby,
> 									'created_by'	=> $row['created_by'],
< 		//JJF Replace line
< 		//$creators[] = $row['created_by'];
< 		$creators[] = $this_createdby;
> 		$creators[] = $row['created_by'];
```

**Comment by protego-it** [comment]
Hi jeff-fab,
database entries as screenshot. created_by is filled now, because i updated it earlier.
![Unbenannt-1](https://user-images.githubusercontent.com/59828196/87790581-0e813680-c841-11ea-824f-36e2264212b5.png)

In /upload-send-notifications.php on line 94 i have this:
`		$clients_data[$row['id']] = array(
									'id'			=> $row['id'],
									'user'			=> $row['user'],
									'name'			=> $row['name'],
									'email'			=> $row['email'],
									'level'			=> $row['level'],
									'notify'		=> $row['notify'],
									'created_by'	=> $row['created_by'],
									'active'		=> $row['active']
								);
		$creators[] = $row['created_by'];
		$mail_by_user[$row['user']] = $row['email'];`

I'm not sure where to implement your code.

**Comment by jeff-fab** [comment]
I see that most of your users are level 7 (=uploader).  In my case they are level 0 (client).   I believe that logins that are created as "user" are considered administrative, while those that are "client" are the end-users of the application.  So in your case, since the login doing the upload is a "user", the notification would go to the client(s) to which the file was assigned.  Are you assigning the file(s) to any client(s) after the upload?

**Comment by protego-it** [comment]
No I don't assign clients to the file. 
I have system users created for my internal uploaders. Clients are external uploaders
I use it only for file sharing when it's too big for email attachments.

It sill should work to receive a message as administrator when someone is upping a file. I want to get informed from both system user and client uploads. 

When I assign a file to a client, I too don't get a message.

**Comment by jeff-fab** [comment]
I see.  Seems like you want something different than what the system does.  You could try custominging upload-process-form.php to behave differently, maybe where it checks the current level around line 210 you could and an or statement to pick up level seven users.

And in the case where you assign the file (that was uploaded by "user" with level 7) to the client, I would expect the **client** to receive the notification rather than the admin.

**Comment by protego-it** [comment]
@jeff-fab 
thanks again. Shouldn't it be a default setting to receive notifications about new uploads for an administrator? 
I'll have a look in the file and try to figure it out. 
But for now - Weekend :)
Have a great day Jeff.

**Comment by ignacionelson** [comment]
Original issue solved in r1265
