### ISSUE TITLE
Can't save General Options without entering "Footer Content"

### ISSUE THREAD

**Issue by achleitner** [projectsend/projectsend#679]
## Type

[x] Bug report

[] Feature request

### Description of the problem

Can't save General Options without entering "Footer Content" even if "Use custom footer text" is not selected.

### List the steps to reproduce the issue

1. Goto General Options
2. Click save options with "Footer Content" field empty and "Use custom footer text" deselected

![unbenannt](https://user-images.githubusercontent.com/42497073/52678256-5061cb00-2f31-11e9-91d3-1c9943f874b5.PNG)
cted

### Environment

* ProjectSend version: r1053

**Comment by ignacionelson** [comment]
Thank you. Will apply a fix for the next release!

**Comment by ignacionelson** [comment]
Fixed on r1070. Thanks!
