### ISSUE TITLE
Notifications for new client upload aren't being sent out to admin

### ISSUE THREAD

**Issue by achleitner** [projectsend/projectsend#683]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[x] Bug report

[] Feature request

### Description of the problem

Notifications for new client upload aren't being sent out to admin. Other notifications work great  using smtp

SEND COPIES
 When a system user uploads files - checked
 When a client uploads files - checked

Define here who will receive copies of this emails. These are sent as BCC so neither recipient will see the other addresses.
Address supplied above (on "From")
filled in the same as from

### Environment

* ProjectSend version: r1053
* php version: 
* MySQL version:

**Comment by ignacionelson** [comment]
Solved in r1265
