### ISSUE TITLE
Login brute force attack security

### ISSUE THREAD

**Issue by achleitner** [projectsend/projectsend#685]
## Type

[] Bug report

[x] Feature request

### Description of the problem

Would like to see some sort of bruteforce login security against bots and hacking attempts.
Log the login attempt IPs and after failed 5 attempts make the user/hacker wait for 5 minutes until they can try again.

https://stackoverflow.com/questions/15798918/what-is-the-best-method-to-prevent-a-brute-force-attack

### Environment

* ProjectSend version:
* php version:
* MySQL version:

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by rhiannon-ppl** [comment]
Looks like there's already a pull request on this: https://github.com/projectsend/projectsend/pull/499 @ignacionelson any chance this could get merged in any time soon?

**Comment by ignacionelson** [comment]
@rhiannon-ppl Will try to include this in the next version. Sadly the PR has issues with many files, but I will extract the useful code and keep the author's name

**Comment by rhiannon-ppl** [comment]
@ignacionelson Fantastic, thanks!

**Comment by Knaui** [comment]
why not make fail2ban work?
atm that is not possible, because failed login attempts dont show up in the apache log, which means fail2ban cannot find them.
I could not find any other log by projectsend itself, where the failed login attempts show up.
Please consider making fail2ban a possibility by writing the failed login attempts in a log.

Maybe this requires less development work too and can implemented fast !?

**Comment by Knaui** [comment]
any updates ? 
haven't seen any commits mentioning security improvements against login attempts

**Comment by ignacionelson** [comment]
Added on https://github.com/projectsend/projectsend/commit/83dcc03ee6cc37d076727dd26b64fef9ca7da280
