### ISSUE TITLE
Plain text passwords at web servers logs

### ISSUE THREAD

**Issue by alexmallo** [projectsend/projectsend#687]
### Description of the problem

After r1053 upgrade user and password are logged. Same behavior with fresh install.
 `10.0.2.2 - - [21/Feb/2019:16:14:23 +0000] "GET /process.php?do=login&username=user&password=mypasswordgoeshere&language=en&_=1550765646522 HTTP/1.1" 200 535 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36"`

### List the steps to reproduce the issue

1. Install projectsend following official instructions: https://www.projectsend.org/how-to-install-projectsend/
2. Create admin user.
3. Try to log in, no matter if fake user and password.
4. Check web server logs (You may filter by process.php if you wish)

### Environment

* ProjectSend version: r1053
* php version: 7.2.15-0ubuntu0.18.04.1
* MySQL version: 5.7.25-0ubuntu0.18.04.2

### Additional information

Passwords not exposed at r756.
Same log line: 
`10.0.2.2 - - [21/Feb/2019:16:27:08 +0000] "POST /index.php HTTP/1.1" 200 2132 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36"`

As web servers stores requests at logs, even https, user and password should not be sent as plain text as GET query.

**Comment by giandi** [comment]
Hi,
I've forked the project and solved this issue for a client of mine. While I'm waiting to finish some changes to customize the product you can download "index.php" and "process.php" to solve that problem from my repository

[https://github.com/giandi/projectsend-legacy](https://github.com/giandi/projectsend-legacy)

**Comment by ignacionelson** [comment]
Thank you for the solution @giandi !

**Comment by ignacionelson** [comment]
Patched on the latest version, r1070 which is now out. Thank you!!
