### ISSUE TITLE
Emails sent with %password%

### ISSUE THREAD

**Issue by david20240** [projectsend/projectsend#688]
Hi ProjectSend Community,

[x] Bug report

[] Feature request

### Description of the problem
trouble is coming into client notifications when subscribing to Projectsend.
When a client open an account he receive an email like this 
Password: %PASSWORD%
and
In the Groups: %GROUPS_REQUESTS%
And only `%FULLNAME% and %USERNAME%` are OK
### List the steps to reproduce the issue

1.
2.

### Environment

* ProjectSend version: r1053
* php version: 5.6.40
* MySQL version: 5.5.60

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

Thank you so much for helping me;-)
David
I'm really sorry to bother u again with so little things but I cannot setup the SMTP to send notifications:
-1- I use a domain called domain.fr
-2- I entered the user like [test@domain.fr] and the password
In the Options:
HOST:
-1- I tried smtp.domain.fr (does not work)
-2- I tried mail.domain.fr (does not work)
-3- I tried localhost (does not work)
Then I entered Port 587 and TLS
I don't know what to do, may be you may help me.

**Comment by ignacionelson** [comment]
Solved in r1265
