### ISSUE TITLE
Non stop HTTP requests to projectsend.org

### ISSUE THREAD

**Issue by BenoitPoulet** [projectsend/projectsend#695]
Hello,

The site is doing https request to projectsend.org, on every page you visit . why ? and how to desactivate this ?

480 43.282854679 10.66.113.56 -> 10.64.1.1    DNS 75 Standard query 0x6d45  A projectsend.org
481 43.282877962 10.66.113.56 -> 10.64.1.1    DNS 75 Standard query 0x7163  AAAA projectsend.org
482 43.283122918    10.64.1.1 -> 10.66.113.56 DNS 178 Standard query response 0x6d45  A 75.98.33.100
483 43.283283527    10.64.1.1 -> 10.66.113.56 DNS 161 Standard query response 0x7163
484 43.293545246 10.66.113.56 -> 75.98.33.100 TCP 74 40978 > https [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=230650 TSecr=0 WS=128

**Comment by david20240** [comment]
Hi,
Have a look on this:
[https://stackoverflow.com/questions/35623192/wireshark-sack-perm-1](url)
and this:
[https://www.iana.org/help/abuse-answers](url) 
As those IP'S (like 10.66.113.56) are in use by many millions of independently operated networks, which might be as small as a single computer connected to a home gateway, and are automatically configured in hundreds of millions of devices.  They are only intended for use within a private context  and traffic that needs to cross the Internet will need to use a different, unique address.
My personal advice is to block IP Range like: 
NetRange:       10.0.0.0 - 10.255.255.255
CIDR:           10.0.0.0/8
But you have to know that you block 16 777 214 machines ;-);-)
It's a choice ;-)
Have a nice day
David

**Comment by BenoitPoulet** [comment]
Hello,

I don't know why you are talking about this. I know what IP i'm using that's not the point.

The point here is the code of this project is trying to contact projectsend.org on every page.

**Comment by david20240** [comment]
`484 43.293545246 10.66.113.56 -> 75.98.33.100 TCP 74 40978 > https [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=230650 TSecr=0 WS=128
Is explained into `the first link I gave you and it's quite dangerous ;-)
Tu ferais mieux de te renseigner sur les liens que je t'ai envoyé.
De plus tu devrais aussi blacklister sur ton parefeu les adresses IP commençant par 10.0.0.0
Mais enfin ce ne sont que des conseils @BenoitPoulet 
Bien à toi
David

**Comment by ignacionelson** [comment]
@BenoitPoulet It's probably the update checker looking for new versions, but it should only happen once a day. Does it ping a specific url or just the domain?

**Comment by BenoitPoulet** [comment]
@ignacionelson I didn't export the capture content so i don't know the URL who was called.

The server do not have access to internet so if it's the update checker, he can't reach the destination server.
So between each page we need to wait the timeout of the external HTTP call to projectsend.org

So the app is so slow that we can't use it.

**Comment by ignacionelson** [comment]
I see. This is fixed on the development version, but what you could do for now is removing the urls so the calls are not executed. 
On the file sys.vars.php (root of the project) find this line
define('UPDATES_FEED_URI','https://projectsend.org/updates/versions.xml');
and replace it with
define('UPDATES_FEED_URI','');

And also, replace
define('NEWS_FEED_URI','https://www.projectsend.org/feed/');
with
define('NEWS_FEED_URI','');

Sorry for the inconvenience!

**Comment by ignacionelson** [comment]
The new version r1070 uses less calls as the data is now cached. I believe this mitigates this problem.
