### ISSUE TITLE
Thumbnail missing - HTTP Error 400 

### ISSUE THREAD

**Issue by mikibarzilay** [projectsend/projectsend#697]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[X] Bug report

[] Feature request

### Description of the problem

I installed a fresh ProjectSend-r1053 system on a CentOS server.
Uploading works fine, but the thumbnail are missing from the preview uploaded files, although the system is creating a thumbnail file.

In addition, while trying to access the thumbnail URL directly:
https://my.server.com/includes/timthumb/timthumb.php?src=upload/files/1555413700-b3daa77b4c04a9551b8781d03191fe098f325e67-untitled-copy.jpg&w=100&q=90

I'm receiving HTTP Error 400 - Bad Request.

Accessing the thumbnail image directly:
https://my.server.com/upload/files/1555413700-b3daa77b4c04a9551b8781d03191fe098f325e67-untitled-copy.jpg
is working well and I can see the image.

Furthermore, I tried to execute the access the same UTL (https://my.server.com/includes/timthumb/timthumb.php?src=upload/files/1555413700-b3daa77b4c04a9551b8781d03191fe098f325e67-untitled-copy.jpg&w=100&q=90) 
on the Linux server itself (using wget) and god the same HTTP 400 error.

I changed in the Options -> Thumbnail the setting to use absolute path, unfortunately it didn't solve the issue.

The Apache (HTTPD) version is 2.4.6
The PHP version is 5.4.16

I'm attaching some screenshots.

### List the steps to reproduce the issue

1.
2.

### Environment
* Linux CentOS version: 7.6
* ProjectSend version: r1053
* Apache version: 2.4.6
* php version: 5.4.16
* MySQL version: mysql Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the 
![image3](https://user-images.githubusercontent.com/10675448/56209008-2d4fb680-605b-11e9-9bf2-65ddfcec8cd0.png)
![image2](https://user-images.githubusercontent.com/10675448/56209011-2de84d00-605b-11e9-9792-b1b13ef41e32.png)
![image (1)](https://user-images.githubusercontent.com/10675448/56209014-2de84d00-605b-11e9-97da-2475a2cd67c4.png)
![image](https://user-images.githubusercontent.com/10675448/56209015-2de84d00-605b-11e9-8b21-061fbbca395d.png)

issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by david20240** [comment]
Hi @mikibarzilay,
I do not know if it may help you but into projectsend R1053 when you simply go to:
[https://www.projectsend.org/](url) it's written: 

> **Please see that your server has at least php 5.6 and MySQL 5 or better to run the software. The PDO extension MUST be installed.**
I hope this may help you
David

**Comment by ignacionelson** [comment]
timthumb is no longer part of PS since r1265. Thumbnail issues are solved.
