### ISSUE TITLE
Username Length

### ISSUE THREAD

**Issue by fle108** [projectsend/projectsend#699]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[] Bug report

[X] Feature request

### Description of the problem

when creating a user with less than 5 letters we obtain the following error : 
` Username length should be between 5 and 60 characters long`
is there a way to disable this limitation ? we have user names with 4 characters 

### List the steps to reproduce the issue

1. go to System users\Add new
2. create user with less than 5 characters in username (e.g: jdoe)

### Environment

* ProjectSend version: r1053
* php version: 5.6.40
* MySQL version: 5.7.25

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by ignacionelson** [comment]
Hello! You can edit the file sys.vars.php on the root of the project. There's this line:
define('MIN_USER_CHARS', 5);
Change that to 4 and give it a try please, it should work fine!

Please keep in mind that the location of this setting will be different on the next version, and you will need to set it again after upgrading.

**Comment by kkplein** [comment]
On 4/17/19 5:31 AM, Ignacio Nelson wrote:
> 
> Please keep in mind that the location of this setting will be different 
> on the next version, and you will need to set it again after upgrading.
> 

We keep hearing about a new version with many fixes. How is that version 
coming along?

MJ

**Comment by ignacionelson** [comment]
Not as polished as it needs to be for a release.
I have a list of 20 very small things and 2 big ones to finish before release. The full list is around 70 but I had to push some of them since time is an issue. Personal life has been in the middle too :/

You can see the many changes already done on the legacy branch.

**Comment by kkplein** [comment]
Hi Ignaio! We just noticed the new 1070 (legacy) version and upgraded our systems. Upgrade went fin, no issues at all. Nice. Does this version fix all (current) reported security issues? So we sleep can again at night?! ;-)

Thanks for the release!

**Comment by ignacionelson** [comment]
Hi! Yes, this fixes all of the security issues that I'm aware of :) Thank you for your support, as always!
