### ISSUE TITLE
Config folder missing from r1070

### ISSUE THREAD

**Issue by fhoubie** [projectsend/projectsend#702]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[X] Bug report

[] Feature request

### Description of the problem

Downloaded the latest version, r1070. Installation process does not work, the screen for database parameters does check the values, but nothing happens

### List the steps to reproduce the issue

1.unzip r1070
2.Go to host/ProjectSend/install
3. Fill in value
4. Click check

### Environment

* ProjectSend version: r1070
* php version: 5.6
* MySQL version: 5

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by fhoubie** [comment]
The web console complains as well of a missing file

/includes/js/install/make-config.php net::ERR_ABORTED 404 (Not Found)

**Comment by amirasyraf** [comment]
yep, can confirm.

**Comment by ignacionelson** [comment]
That file should not be loaded when making the config.
Can you run a little test?
Edit assets.php and replace line 26

`$load_js_files[] = BASE_URI . 'includes/js/js.functions.php';`

with

```
if (!defined('IS_MAKE_CONFIG')) {
	$load_js_files[]	= BASE_URI . 'includes/js/js.functions.php';
}
```

**Comment by fhoubie** [comment]
I've tried, I don't have messages in the console anymore, but can't go further than the check, the button stays in Check instead of Install

![image](https://user-images.githubusercontent.com/3958446/56953870-bf68bc00-6b3d-11e9-93f6-c1909154f71c.png)

**Comment by ignacionelson** [comment]
Fixed, I've re-uploaded r1070. Sorry about this!
