### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by Richard76000** [projectsend/projectsend#707]
Hi,

Did you set up the ldap module ?

Thanks !

**Comment by tsener** [comment]
LDAP and  at least  one REST call for file download/upload  is a must to adopt the solution.

**Comment by Richard76000** [comment]
I Think this feature, it is important for your application.

**Comment by ignacionelson** [comment]
@tsener Indeed. These problems need an update to the auth method. I'm doing some tests with Sentinel and JWT. If everything goes ok, then I will finish the integration of Hybridauth will be the next step. After that, LDAP, but I will need some extensive help testing. I'm currently working on moving everything into an MVC app which should make everything a LOT easier. Still, the process is very time consuming

**Comment by ssbaksa** [comment]
If you need help with testing, you can contact me. We are using OpenLDAP as source of User identity for many of our services/servers. Bugzilla and NextCloud are just examples of software which are using successfully  our local LDAP database.

**Comment by Richard76000** [comment]
Hi,

we need a ldap active directory windows server connection, and that it is configurable via the application.

Thanks.

Richard JACQUES
Direction des Systèmes d’Informations et du Numérique



De : ssbaksa [mailto:notifications@github.com]
Envoyé : mercredi 22 mai 2019 10:00
À : projectsend/projectsend
Cc : Richard Jacques; Author
Objet : Re: [projectsend/projectsend] LDAP (#707)


If you need help with testing, you can contact me. We are using OpenLDAP as source of User identity for many of our services/servers. Bugzilla and NextCloud are just examples of software which are using successfully our local LDAP database.

**Comment by thiagoldaniel** [comment]
Hello, a LDAP feature are Available ? How to enable ?

**Comment by ignacionelson** [comment]
Duplicate of #312
