### ISSUE TITLE
Version r1070 - seems to have a problem.

### ISSUE THREAD

**Issue by quintingsnj** [projectsend/projectsend#710]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[x] Bug report

[] Feature request

### Description of the problem

When uploading a file, it finishes, but the next page does not load. Have tried with both an admin account, and just an uploader account.

### List the steps to reproduce the issue

1. Upload a file
2.

### Environment

* ProjectSend version:r1070
* php version: 7.2
* MySQL version: 5.7.26

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by thameerakn** [comment]
I just update the version and not found any issues. Which browser are you using? Any error on browser? If you could use PHP 7.0 and check

**Comment by overclockedllama** [comment]
I have the same error and I am using PHP-FPM v7.0.33
```PHP 7.0.33-0+deb9u3 (fpm-fcgi) (built: Mar  8 2019 10:01:24)
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u3, Copyright (c) 1999-2017, by Zend Technologies```
I am using Chrome. I get this error: 
![image](https://user-images.githubusercontent.com/12625848/60143137-c7974d80-97b4-11e9-8453-6bdc5ccee077.png)

**Comment by thameerakn** [comment]
Did you set permission correctly to upload folder? How big is the file? Check upload limits in PHP as well as projectsend.

**Comment by overclockedllama** [comment]
I feel so silly! Everything was root. Chowning to www-data fixed it. Thank you so much!

**Comment by thameerakn** [comment]
It's good to check Upload limits before you go production with ProjectSend.

**Comment by quintingsnj** [comment]
I feel equally silly! Same issue for me...wrong ownership.....sorry about that.
