### ISSUE TITLE
MariaDB & Nginx support?

### ISSUE THREAD

**Issue by Robakimou** [projectsend/projectsend#713]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[] Bug report

[x] Feature request

### Description of the problem

Are MariaDB and Nginx supported and from which version?

### List the steps to reproduce the issue

1.
2.

### Environment

* ProjectSend version:
* php version:
* MySQL version:

### Additional information

_[Optional]_ Write any additional information that you believe might be useful to reproduce the issue

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by ignacionelson** [comment]
I've tested r1070 with MariaDB 10.1.40 and nginx/1.14.0 and everything seems to be working just fine.

**Comment by Robakimou** [comment]
Thanks,  I have successfully updated to version r1070 with 10.0.27-MariaDB and nginx/1.10.0

Regards,

Rob
