### ISSUE TITLE
Your browser doesn't support HTML5, Flash or Silverlight

### ISSUE THREAD

**Issue by punitvaria** [projectsend/projectsend#722]
[] Bug report

When we try upload an image from Upload files menu it shows following message : 

Your browser doesn't support HTML5, Flash or Silverlight. Please update your browser or install Adobe Flash or Silverlight to continue. 

### Description of the problem

It works in **Apache**. But in **Nginx** it doesn't allow to upload files. 

### List the steps to reproduce the issue

1. Go to Files -> Upload 

### Environment

* ProjectSend version: r1070
* php version: 5.6.40
* MySQL version: 5.5.62
* **Nginx 1.14.2**

**Comment by ignacionelson** [comment]
Thanks for the report. A new version is coming out soon that includes an updated version of Plupload, which I believe solves this.
I will keep testing, as I had no issues with nginx on my end, but haven't tested with that specific versions combination.

**Comment by kkplein** [comment]
Hi Ignacio,
Nice to hear that a new versions is coming out shortly. Any idea when? And is this a completely refactored version, or "just" the legacy one with fixes..?

**Comment by ignacionelson** [comment]
Things have changed. The refactored branch will be deleted, it was just impossible to modernize the code that way. I've been working on 2 things:
- An update to the legacy version, that includes many changes to the core and fixes (like the use of  dependencies, better use of classes, replacement of thumbnails generator, cleaner code, etc), that's not far from finished. Just to be clear, the legacy branch works fine and has no known security issues right now, but it's very hard to maintain and add new features and themes to.
- A new version written completely from scratch. This is very early into development but is the right way to go in the long term... won't have a public test version for this in a while, so in the meantime the public updates will go to the legacy branch.
It's a double effort but I think will be worth it.

**Comment by kkplein** [comment]
Hi Ignacio,
Nice to know a bit of what is going on. Thanks for updating us. Looking forward to the new release!

**Comment by ignacionelson** [comment]
Fixed in r1265 after updating plupload
