### ISSUE TITLE
mod_rewrite disabled

### ISSUE THREAD

**Issue by LiohMoeller** [projectsend/projectsend#725]
In the default sources, there is a .htaccess which disables mod_rewrite. Is there a specific reason for that, because I want to replace it with a non-ssl -> ssl redirect like:

```
RewriteEngine on

# http non-www -> https non-www
RewriteCond %{HTTPS} !=on
RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
```

**Comment by mschop** [comment]
AFAIK there is no `.htaccess` that disables RewriteEngine. Which file do you mean?

**Comment by mschop** [comment]
As here is no further update on this topic, I close the Issue.
