### ISSUE TITLE
SMTP-error

### ISSUE THREAD

**Issue by Kent-Agent** [projectsend/projectsend#727]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[x] Bug report (More like issue i guess..) 

[] Feature request

### Description of the problem

Hello!

I am trying to send mail with Projectsend using our SMTP-server located in our net. 
I'm not quite sure where it fails, or why. There does not seem to be any documentation regarding how to handle this action, and I am not quite sure what I am doing wrong here.. 

The fields filled in the GUI is as follows:

Mailer: SMTP
Username: empty
Password: empty
Host: our-smtp-server
Port: 25
Authentication: None

The servers only requirement is that the client trying to access is in the same net as the server. Hence meaning it does not need special authentication.

However, this does not work. I have managed to turn on debugging and I get this error when trying to create a user and sending out the login-info by email. 

2019-09-24 08:17:08 SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Name or service not known (0) 2019-09-24 08:17:08 SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

It does not make a difference if i enter a Username/Password in the fields above. The error stays the same.
To me it seems like Projectsend does not try to connect to our SMTP-server, it acts like there is none specified.
Is there any config-file where these values are specified? I cannot find them.. 

Anyone can clarify this for me, thanks and best regards! 

### List the steps to reproduce the issue

1.
2.

### Environment

* ProjectSend version: r1070
* php version: 7.2
* MySQL version: 5.7.27

### Additional information

Running on Ubuntu and Apache if that makes any difference. 

If i select PHPMailer in the GUI, the mail gets sent using the internal SMTP-server. But this is wrong since all mail will get selected as spam etc. 
I want to use my company's SMTP-server. 

### Related PR

_[Optional]_ If you have submitted a PR related to this issue, please paste the link here

___

### IMPORTANT

Before submitting an issue, please [do a search on the issues page](https://github.com/ignacionelson/ProjectSend/issues) to make sure that the problem hasn't been reported already.

**Comment by Kent-Agent** [comment]
Problem solved by using PHPmailer instead. 
The entires above was also listed in the database, but not used by Projectsend for unknown reasons.

**Comment by ignacionelson** [comment]
Thanks for letting me know the solution. I will check this for the next release.
