### ISSUE TITLE
Big File (1.5 GB) download gets canceled 

### ISSUE THREAD

**Issue by PhilmacFLy** [projectsend/projectsend#730]
## Type

Please complete with an X between the brackets to indicate the type of submission.
This is a:

[x] Bug report

[] Feature request

### Description of the problem

After uploading a 1.5 GB File and trying to download it (tried with Chrome and Firefox) it gets canceled after 6.7MB but shows as completed. Also neither Chrome nor Firefox are showing how big the file is supposed to be.

### List the steps to reproduce the issue

1. Upload 1.5GB File
2. Try to download with Chrome or Firefox

### Environment

* ProjectSend version: r1070
* php version: php7.3
* MySQL version: MariaDB 10.3.15

### Additional information

php.ini:
memory_limit = 128M 
post_max_size = 8M
upload_max_filesize = 64M

**Comment by Dargazo** [comment]
I am also experiencing this issue with php 7.3. Is there any progress, or perhaps a workaround available?

**Comment by ignacionelson** [comment]
Hello!
Try setting this values on php.ini and let me know if that worked please (did well in other cases)

post_max_size 256M
max_input_time 3600
max_execution_time 3600

You could try setting the post_max_size larger, and even set the other values to 0, but I would not recommend that other than for testing if that fixes the issue

**Comment by Dargazo** [comment]
Unfortunately, my webhost does not allow me to change php values. Is there an other way to fix this?

I noticed that, once the download (a large zip file) is canceled. I can resume it (I am using FireFox), and the download finishes. Testing the zip using 7-zip shows no errors, so my guess is that I am getting the files correctly (eventually), but something goes wrong during transfer. Does this information help, or is there something else I can test?

**Comment by ignacionelson** [comment]
If possible, install the XSendFile module on your webserver and enable it in ProjectSend to bypass php when downloading files. This solves the issue. If you cannot add modules or edit php, sadly I don't think large files can be served.
