### ISSUE TITLE
Would like the public page to look just like the my files.

### ISSUE THREAD

**Issue by AppySauce** [projectsend/projectsend#734]
Where can I drop some code so that when on the public.php, we also see pics rather than just the file name.
Would like the public page to look just like the my files.

**Comment by AppySauce** [comment]
I'm guessing that this software is so old that no one cares any more.

**Comment by ignacionelson** [comment]
Sorry you feel that way. It's just me doing everything, along with both my daily jobs, so time is limited. You can modify the file as you like, just be aware that it will get overwritten when you update the software. It's not a bad idea to give the public page the same template as the files list.

**Comment by AppySauce** [comment]
I have no idea how to do that. I have selected Pine Box as the Theme.  But I have no idea how to make the icons and pictures appear on the public page.

**Comment by AppySauce** [comment]
I tried adding this TEMPLATE_VIEW', true in the public.php, but the public then displays nothing.

 require_once('../sys.includes.php');
	define('IS_TEMPLATE_VIEW', true);
	$this_user = CURRENT_USER_USERNAME;
	if (!empty($_GET['client']) && CURRENT_USER_LEVEL != '0') {
		$this_user = $_GET['client'];
	}
	include_once(TEMPLATE_PATH);

**Comment by ignacionelson** [comment]
Sorry, it's not going to work simply like that since the data that file receives is quite different. If you check the public page you will find that it has different ways of showing files depending on their permissions. You would need to take the layout from the template you like and try to redo it on the public page, also taking care of copying the css the template uses.

**Comment by AppySauce** [comment]
Yep, I'm lost. don't know what file does what...

**Comment by AppySauce** [comment]
can not tell the difference between the files that display or not the icons/pics.

**Comment by AppySauce** [comment]
Is it somewhere in here?
function list_file($data, $origin) {
	$show = false;
	if ( $origin == 'group' && PUBLIC_LISTING_SHOW_ALL_FILES == 1 ) {
	}
	else {
		if ( $data['public'] != 1 ) {
			return;
		}
	}

	$output = '<li class="file"><i class="fa fa-file-o" aria-hidden="true"></i> ';
	if ( PUBLIC_LISTING_USE_DOWNLOAD_LINK == 1 && $data['expired'] != true && $data['public'] == 1 ) {
		$download_link = BASE_URI . 'download.php?id=' . $data['id'] . '&token=' . $data['token'];
		$output .= '<a href="' . $download_link . '">' . $data['filename'] . '</a>';
	}
	else {
		$output .= $data['filename'];
	}

	$output .= '</li>';

	return $output;

**Comment by ignacionelson** [comment]
Exactly! The function is called list_file. You could use the info passed in the $data array and check if the file is an image, and show a thumbnail in that case.
Check the default template for an example of that:

`if ( file_is_image( $file_absolute_path ) ) {
    $thumbnail = make_thumbnail( $file_absolute_path, null, TEMPLATE_THUMBNAILS_WIDTH, TEMPLATE_THUMBNAILS_HEIGHT );
    if ( !empty( $thumbnail['thumbnail']['url'] ) ) {
        $preview_cell = '<img src="' . $thumbnail['thumbnail']['url'] . '" class="thumbnail" alt="' . htmlentities($file['name']) .'" />';
    }
}`

You will need to modify that part to use the info the in $data array!

**Comment by AppySauce** [comment]
oooooo, k. Just spent the last half hour destroying and replacing the template and public.php.
FYI, the entire 'function thing you posted' does not exist anywhere in entire ProjectSend script.
k, got to go to work now, somebody needs a laptop and printer...

**Comment by AppySauce** [comment]
moved on... new script...

**Comment by ignacionelson** [comment]
Sorry to hear that :( Hope you found what you needed!
