### ISSUE TITLE
Feature Request: Folders for Organization

### ISSUE THREAD

**Issue by ggnabasik** [projectsend/projectsend#738]
Would be nice to have a "folder" structure to allow users to place files in folders for organizational purposes.  For an active user/client account, this would be ideal.  Option to have "global" folders.  Option for default Upload folder.  We want to help organize the files for the customers that will use this and there doesn't seem to be an easy way to do this.

**Comment by Degenn** [comment]
I agree, this would be very useful.  I think it can be worked around using categories, but this is less intuitive for the client.

**Comment by iincitr** [comment]
Yes, folder based file share would be very useful. My client assigned to folder(s) just it.

Thank you for your efforts.

**Comment by ignacionelson** [comment]
Done on r1720
