### ISSUE TITLE
Can't assign an uploaded file to a user.

### ISSUE THREAD

**Issue by sandtim** [projectsend/projectsend#74]
At the "Files ready to upload" screen, I can choose a user to assign the file to and click continue.  The screen flashes and comes right back to the same screen.  The file is not assigned to a user.

I upgraded PHP and Apache on the server over the weekend in order to install Drupal 8 for a client.  I'm now at PHP 5.6.16 and Apache 2.4.18.  I've also taken several steps over the weekend to harden the server against attacks.  ( I'm having to rebuild a couple of my web sites due to back-door hacks that I can't find.)  Something I've done may be conflicting with ProjectSend, but I don't know what.

I'm not seeing anything in the error_log files that is related to this.  I've looked at the error_ log files in both the directory that ProjectSend is installed as well as the one for the whole server.

I've checked, analyzed, and optimized the database tables and they showed no errors.

Any help in getting this back up and going would be appreciated.

**Comment by lenamtl** [comment]
Hi,

You will have to investigate, that could be a lot of things...
Make sure you check Apache and PHP log file.

At the moment I'm using the latest Projectsend version with PHP 5.4.12  with no problem.
Some users have reported problems using 5.5 and later.

Here are the Backward Incompatible changes between PHP 5.4 and PHP 5.5
http://php.net/manual/en/migration54.incompatible.php
I know that ob_start(); is used in the code

So good chance you will have error & problem using 5.6 +

For now, you can use another server to run Projectsent.
Also there are some ways to run multiple PHP version on a server.
