### ISSUE TITLE
Github releases

### ISSUE THREAD

**Issue by thelamer** [projectsend/projectsend#743]
If it is possible can r1070 be a github release with your release or zip or tarball attached to it? 

From a programmatic standpoint it makes ingestion much easier to determine the latest version of the software and consume it. 

Thanks, let me know if you have any questions about generating Github Releases from your Build env or uploading release assets.

**Comment by thelamer** [comment]
Pinging in to see if this will be possible, if not no hard feelings, feel free to close this out.

**Comment by ignacionelson** [comment]
I've tried but it seems that I cannot make a release from 1070 since it's not from a specific commit. Next version will sure be one. Sorry :(

**Comment by thelamer** [comment]
Not a problem, thanks for looking into this
