### ISSUE TITLE
Sudden Logouts

### ISSUE THREAD

**Issue by torstenbergemann** [projectsend/projectsend#747]
We are using r1070 on a LAMP server and we are experiencing problems with sudden logouts. Sometimes a session lasts no longer than a few seconds. The more inactivity, the more likely the user is logged out and sees the login screen again. Performing the same steps again then, the procedure works and the user gets logged out a few seconds later. So this must be a problem with the login session management. 
I cannot find any hints to how the system works. In other issues, I found hints to cookies being set. I cannot find values to longer the session time or control when the user session get timed out.
Does anyone have a similar problem?

**Comment by ignacionelson** [comment]
This seems to be a php session related issue, not PS. Sorry!
