### ISSUE TITLE
Client cannot use "manage files" with full funtion

### ISSUE THREAD

**Issue by amirulrb** [projectsend/projectsend#75]
I got problem with "manage files" menu,when i login using admin i can edit "File information,Expiration date,Assignations" ,but when using client i only can use "File information" funtion....is it normal or just happen to me? thanks

**Comment by lenamtl** [comment]
The client have very limited actions.
Depending of the admin settings the client can upload and download file.
This need to be improve, so the admin can set client actions, like delete...

**Comment by ignacionelson** [comment]
Added manage files for clients in r1265
