### ISSUE TITLE
Templates not working

### ISSUE THREAD

**Issue by protego-it** [projectsend/projectsend#750]
Hi projectsend team,
first, great work so far. 
I have an issue with the templates. I've copied the default template to create my own. I've changed Template name, URI and so on and changed cftp_template to cftp_template_own. 
My template is visible at the backend and if I put it as default, it changes correctly in the database. 
Problem is that the css is not loaded.
I've switched to the default template and edited the css with no change. I've inspected the source code and found out that no css is loaded neither from the default template nor from my cloned template.
I need to put the css file in assets.php to get it loaded. Is this a bug? Do I need to change something important in the cloned template? 
As far as I can see, template's css should be loaded. 
In assets.php on line 113
`if ( isset( $this_template_css ) ) {
	$load_css_files[]	= $this_template_css;
}`
Unfortunately not working.
Could you please assist? Thank you.

**Comment by ignacionelson** [comment]
Please try r1265, this should be solved.
