### ISSUE TITLE
Problem to access website.

### ISSUE THREAD

**Issue by lucasfecap** [projectsend/projectsend#752]
After the turn of the year and returning from vacation I realized that when accessing the project folder. nothing has been changed.

Unable to access this site It was not possible to find the IP address of the server.
DNS_PROBE_FINISHED_NXDOMAIN.

**Comment by ignacionelson** [comment]
Hi @lucasfecap 
This looks like a DNS issue within your domain/server, unrelated to PS. Please check that your domain exists, points to the right nameservers and that they resolve using a tool like https://dnschecker.org/
Good luck!

**Comment by lucasfecap** [comment]
Thank You So much!
