### ISSUE TITLE
Membership requests fails

### ISSUE THREAD

**Issue by bertoldus** [projectsend/projectsend#756]
If I try to enter *Membership requests* bookmark, On my screen shows none, but close on label shows number 6. Membership in groups I can add only by enter in group description and add user in appropriate filed on bottom. Another form (enter in user and add to group fails (none errors, but not successful)
Furthermore, if I try to click on another tabs (other as *Clients groups*) this not expands. I think this is bug.
![Screenshot_20200207_173534](https://user-images.githubusercontent.com/60789453/74047232-4baee600-49d0-11ea-92ed-449efd36915d.png)
Lech
[r1070, polish language]

**Comment by bertoldus** [comment]
This is screenshot AFTER clicking on "Prośby o członkowstwo" (membership rerquests)
![Screenshot_20200207_173915](https://user-images.githubusercontent.com/60789453/74047589-e6a7c000-49d0-11ea-937e-cd098354da71.png)

**Comment by ignacionelson** [comment]
Hello! It seems that the page is not rendering fully, most likely due to a php error.
You would need to activate the debug mode, or check the php error log to see the actual issue.

**Comment by ignacionelson** [comment]
Also, if the page is not rendered completely, jQuery will not be available, that's why most javascript functions will not work (eg: expanding the menu)

**Comment by ignacionelson** [comment]
Solved in r1265
