### ISSUE TITLE
No Vendor folder

### ISSUE THREAD

**Issue by edputt** [projectsend/projectsend#758]
No vendor folder in zip

[client 0.0.0.0:59869] PHP Warning:  require_once(/var/www/html/prep/projectsend/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/prep/projectsend/bootstrap.php on line 12
[Mon Feb 10 15:49:16.317580 2020] [php7:error] [pid 6448] [client 0.0.0.0:59869] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/prep/projectsend/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/prep/projectsend/bootstrap.php on line 12

**Comment by ignacionelson** [comment]
Please download the full version from the official site. If you download from the git repo, you need to install the dependencies and compile the assets (details are in the Readme file). Thanks!

**Comment by infracritical** [comment]
I ran into the same issue today (24-Sep-2024). You should *fix* your online documentation, as there are many people (like me) who simply download from GitHub and install/configure from there.

https://docs.projectsend.org/about/installation/manual-installation states:

"Download and unzip the lastest version of ProjectSend to a folder of your choice, either from https://www.projectsend.org/ or https://github.com/projectsend/projectsend."

Note also grammatical error "lastest" should be "latest".

Please fix this for future reference.

**Comment by ignacionelson** [comment]
Thank you, I've just fixed the documentation!
