### ISSUE TITLE
Admin works, Client area blank (Error 500)

### ISSUE THREAD

**Issue by harrycustom** [projectsend/projectsend#762]
Hi, I installed this great software a few days ago. It works perfectly administrator side, but every time I access as a customer (https://www.site.it/my_files/) I see a completely blank page. Opera, unlike other browsers, shows an error 500.
The software is correctly configured, php updated and my server provider says there is no problem.
I simply activated the Italian language and activated it according to the instructions in the configuration file.

I'm following issue #342 (https://github.com/projectsend/projectsend/issues/342) and I can say that:

1. all the files are present
2. I have redone the installation three times.
3. Php error display shows no error
4. If I force https://www.site.it/manage-files.php I see the customer account correctly
5. I tried to change:

Line 14
if (isset($_SESSION['access']) && $_SESSION['access'] == CURRENT_USER_USERNAME) { $grant_access = 1; $is_client = 1; }

change to
if (isset($_SESSION['access']) && $_SESSION['access'] == CURRENT_USER_USERNAME) { $grant_access = 1;}

but nothing happens.
6. php_pdo.dll, php_pdo_mysql.dll are active

Any suggestions on how to solve the problem?

**Comment by harrycustom** [comment]
Addendum: I've realized that the issue seems to occurr switching template to Pinboxes. 
The solution of issue #518 :

In /templates/pinbox/template.php I changed the line:
define('TEMPLATE_RESULTS_PER_PAGE', -1);
to
define('TEMPLATE_RESULTS_PER_PAGE', 100);

seems to work.
Reverting to Default template seems to work too.

**Comment by airdogvan** [comment]
You should take out that pinbox template.  I've puzzled for hours trying to figure out why the clients were showing a blank page!

**Comment by ignacionelson** [comment]
That issue is fixed here https://github.com/projectsend/projectsend/commit/59d540a1471646e11405bab1948ae1ade36d1046 so in the next release this should not be a problem. Sorry!

**Comment by ignacionelson** [comment]
Fixed in r1265
