### ISSUE TITLE
Error 500: Call to a member function query()

### ISSUE THREAD

**Issue by zynimus** [projectsend/projectsend#765]
Tried to install Project Send using the source code .zip from the website directly. When attempting to install, was prompted with error 500. 
After enabling debug in sys.vars.php, I was able to see the following error:
`PHP Fatal error:  Uncaught Error: Call to a member function query() on null in ...`

I discovered the pdo construct was missing... so for now I add: 
`$dbh = new PDO("mysql:host=".DB_HOST.";dbname=".DB_NAME, DB_USER, DB_PASSWORD);`
And was able to get the install page to show vs blank pages.

Where is this actually suppose to be so i can make sure it's in the proper place.

Thanks!

**Comment by Gingervirus** [comment]
What Version of MYSQL DB are you using?

**Comment by ignacionelson** [comment]
Closing since no more info has been posted
