### ISSUE TITLE
force connection only with email address

### ISSUE THREAD

**Issue by Richard76000** [projectsend/projectsend#768]
Hi,

is it possible to force the connection only with the user's email address ?

**Comment by ignacionelson** [comment]
r1265+:
includes/Classes/Auth.php
Edit this line
`$statement = $this->dbh->prepare("SELECT * FROM " . TABLE_USERS . " WHERE user=:username OR email=:email");`
to
`$statement = $this->dbh->prepare("SELECT * FROM " . TABLE_USERS . " WHERE email=:email");`
