### ISSUE TITLE
Group assignment for multiple files?

### ISSUE THREAD

**Issue by KuhlmannJens** [projectsend/projectsend#77]
Newbie running r582 trying to manage a larger number of files that are already uploaded.
Couldn't find an efficient way to put a number of them into a newly created group; only available for a single file?
Thanks for helping!

**Comment by lenamtl** [comment]
The best way for now is on upload to assign a file to a default group.
You can set a default group in the settings, so when uploading a file this will associate to this group by default, so I you upload a lot of file in one operation this can be a temporary solution

I agree there is no quick way for now forseveral files to get assign to a group.

**Comment by KuhlmannJens** [comment]
Thanks for the temp!
Currently, there is already an option checkmarking individuals in the file management. At the moment, the only action available on the selected group is deleting. Could be a place to add the mamagement option there producing the similar view as during the upload worklflow where with all the group assignment, expirery setting and all that is available.

**Comment by lenamtl** [comment]
yes that can be to place to add this feature or another interface to do batch file action like
switching file from client A to client B for example.

**Comment by Simms91** [comment]
Hi, 
is there now perhaps a solution for this problem? I neither find an option to assign multiple files at once to one client nor do I find an option to auto-assign data to a default group.

**Comment by ignacionelson** [comment]
Editing multiple files is enabled on r1265
