### ISSUE TITLE
Remove Project Send Details from Header

### ISSUE THREAD

**Issue by vinaypasari** [projectsend/projectsend#776]
we been using this open source software since long time for our clients, we really loved it and wish to remove Project Send from Navigation from Header. we are even ready to go with paid version. 
![Capture](https://user-images.githubusercontent.com/62843923/77852665-7e6da180-71fd-11ea-8229-779fe5d5b5f7.PNG)

**Comment by ignacionelson** [comment]
Hello! To remove that icon create a file called custom.css in the css folder and add this as content:

.navbar-brand {
    display: none !important;
}

**Comment by vinaypasari** [comment]
Hi, this removes the brand name as well from the top , any other alternative where we can have brand name as well. 

this command does not displays anything on the top left.

**Comment by cwt3c** [comment]
`#header .navbar-header svg {
display: none !important;
}`

Should do the trick inside the custom.css :)

**Comment by ignacionelson** [comment]
@cwt3c Thanks!
