### ISSUE TITLE
Setup not starting

### ISSUE THREAD

**Issue by joseon-penggwin** [projectsend/projectsend#777]
Hello,

after following the Install instructions on: https://www.projectsend.org/how-to-install-projectsend/
and navigating to...: _yourprojectsendlocation/install_ 

I can see Warnings next to the Fields _Host, Database Name, Username, Password, Table prefix_ but I don't know what they mean as there's no Info or hover over message on what could be wrong.

I've added the **DB_NAME, DB_USER, DB_PASSWORD** in sys.config.php. The created user has all privileges on the database.

Clicking on "check" does nothing.
Restarted Apache and the Server.

**Config**, **Upload** and **Cache** directory are Writable.

**MySQL version**: 8.0.19-1debian10
**OS**: Debian 10: 4.19.0-4-
**PHP version**: 7.3.14-1~deb10u1
**PHP SAPI**: apache2handler
**ProjectSend**: r1070

I don't know how to proceed.
Whats wrong? I get no Error, what do I have to fix?

Kind Regards.
penggwin

**Comment by ignacionelson** [comment]
Hello! This is a known error and the solution will be ready on next release.
Usually what happens is that the permissions check on the folders does not pass, but the installer fails to mark the error.
Try to set the required folders to 775 and see if the installer advances then. Sorry about this.

**Comment by joseon-penggwin** [comment]
Hi! Thank you for your reply.

Sadly, that didn't do it.

I chmod'ed the **Config, Upload** and **Cache** directories (and after that, the whole projectsend directory) to **775** but the error still persists. 

Here's (part of) my installation Log:

# Edit Config Files
At the end of the file: `/etc/php/7.3/apache2/php.ini`
I appended:

```
extension=mysqlnd    
extension=pdo
extension=pdo_mysql
```
I tried several combinations ( with *.so and without). I also had to add `mysqlnd` to the extensions, otherwise PHP would throw Warnings and Errors.

In the file: `/opt/projectsend/includes/sys.config.php`
I edited:
```
/** Database name */
define('DB_NAME', 'projectsend');

/** Database host (in most cases it's localhost) */
define('DB_HOST', 'localhost');

/** Database username (must be assigned to the database) */
define('DB_USER', 'psdbuser');

/** Database password */
define('DB_PASSWORD', 'SomePassword');
```
# Enabling PHP extensions
```
phpenmod pdo
phpenmod pdo_mysq

```
# Installing more PHP Extensions
```
apt-get install php7.3-zip
apt-get install php7.3-gd
```

# Created Database projectsend and User in MySQL
```
CREATE DATABASE projectsend;
CREATE USER 'psdbuser'@'localhost' IDENTIFIED BY 'SomePassword';
GRANT ALL PRIVILEGES ON projectsend.* TO 'psdbuser'@'localhost';
```

`systemctl restart apache2` (and a `reboot` for good measure) and clearing Client Browser Cache out of desperation.

Alas, still not working. Clicking on "check" still does nothing.

I'm not sure what I'm doing wrong. I would really like to use this software, but after two days of troubleshooting this I'm starting to lose my mind. Please help...

**Comment by joseon-penggwin** [comment]
Removed php7.3 and installed php7.1 :

`PHP version: 7.1.33-14+0~20200320.35+debian10~1.gbpb15fae`

Still no success. Installer still hangs at "check" doing nothing.

**Comment by joseon-penggwin** [comment]
Tried once again with php5.6 but still, it's not working. With php5.6 it's not even possible to get the "make-config.php" page visible.

Unless you have a solution I am giving up on ProjectSend. I can not for the life of me figure out what the problem is.

**Comment by ignacionelson** [comment]
This is weird! Sorry. Please enable the error output by changing
define('DEBUG', true);
in sys.vars.php
Maybe a warning or error will come up

**Comment by joseon-penggwin** [comment]
Hi!

I did a fresh install of the server and and config files and tried it anew. Settings the same as above, and I think I got a step further.

Accessing: ```yourprojectsendlocation/install/make-config.php```
Now shows: **The configuration file already exists.**

Accessing: `yourprojectsendlocation/install`
Throws an **HTTP ERROR 500**

I enabled the Debug mode:

 ```
[Wed Apr 08 14:53:09.625730 2020] [php7:error] [pid 12034] [client IPADDRESS:45154] PHP Fatal error:  Uncaught Error: Call to a member function query() on null in /opt/projectsend/includes/site.options.php:19\n
Stack trace:\n
#0 /opt/projectsend/sys.includes.php(22): require_once()\n
#1 /opt/projectsend/install/index.php(11): require_once('/opt/projectsen...')\n
#2 {main}\n
thrown in /opt/projectsend/includes/site.options.php on line 19
```

Checking `/opt/projectsend/includes/site.options.php` (not modified) on line 19:

```...
 16 global $dbh;
 17 $options_values = array();
 18 try {
 19     $options = $dbh->query("SELECT * FROM " . TABLE_OPTIONS);
 20     $options->setFetchMode(PDO::FETCH_ASSOC);
 21 
 22     if ( $options->rowCount() > 0) {
 23         while ( $row = $options->fetch() ) {
 24             $options_values[$row['name']] = $row['value'];
 25         }
 26     }
 27 }
 28 catch ( Exception $e ) {
 29     return FALSE;
 30 }
...```

Which leads me to the idea it's something to do with the PDO access?

Thanks for your help so far!

**Comment by ignacionelson** [comment]
Looks like it! Are you sure your database user has all permissions enabled?

**Comment by schmohan** [comment]
This could be related. I am a new user to web servers, so sorry for any stupid mistake I might have done. 

I have the projectsend files in the folder home/user_name/public_html/projectsend and enabled apache2 config to use public_html

I tried both official installation (https://www.projectsend.org/how-to-install-projectsend/) and (https://www.youtube.com/watch?v=YlwWcrz3Xkw) and localhost/projectsend either doesn't load or gives me this message: 

> Not Found
> 
> The requested URL was not found on this server.
> Apache/2.4.29 (Ubuntu) Server at localhost Port 80

MySQL version: Ver 14.14 Distrib 5.7.29 for Linux 
OS: Ubuntu 18.04.4
PHP version: 7.2.24-0ubuntu0.18.04.3
Apache2 version: Apache/2.4.29 (Ubuntu)
ProjectSend: r1070

**Comment by joseon-penggwin** [comment]
Hi,

> Looks like it! Are you sure your database user has all permissions enabled?

I'm not fluent in Databases, but to me this looks right:

```
mysql> SHOW GRANTS FOR 'psdbuser'@'localhost';
+-------------------------------------------------------------------+
| Grants for psdbuser@localhost                                     |
+-------------------------------------------------------------------+
| GRANT USAGE ON *.* TO `psdbuser`@`localhost`                      |
| GRANT ALL PRIVILEGES ON `projectsend`.* TO `psdbuser`@`localhost` |
+-------------------------------------------------------------------+
```


-----
> I tried both official installation (https://www.projectsend.org/how-to-install-projectsend/) and (https://www.youtube.com/watch?v=YlwWcrz3Xkw) and localhost/projectsend either doesn't load or gives me this message:
> 
> > Not Found
> > The requested URL was not found on this server.
> > Apache/2.4.29 (Ubuntu) Server at localhost Port 80

I am not good with webservers either but could it be that you havn't changed the DocumentRoot in ```/etc/apache2/apache2.conf``` ? For example:

```
<Directory /home/user_name/public_html/projectsend>
   Options Indexes FollowSymLinks
   AllowOverride None
   Require all granted
</Directory>
```

And change your site-configuration: ```/etc/apache2/sites-available/projectsend.conf```

```
...
DocumentRoot /home/user_name/public_html/projectsend
...
```
Reload/Restart apache2 and see if it works. Otherwise I'd open another ticket, this looks like a different problem.

**Comment by joseon-penggwin** [comment]
@ignacionelson any news?

**Comment by joseon-penggwin** [comment]
@ignacionelson 

Hi,

I tried another last fresh install but this time I tried **php5.6** and projectsend **r1053** - alas, still no success.

Accessing: ```yourprojectsendlocation/install/make-config.php```
Shows: **The configuration file already exists.**

Accessing: `yourprojectsendlocation/install`
Throws an **HTTP ERROR 500**

At this point I'm afraid to ask, but does this software even run? If so, what are the requirements?

The last two major releases do not work. It seems impossible to get it up and running.

If there is no answer I consider this project dead.

**Comment by jellevdbos** [comment]
> 
> 
> @ignacionelson
> 
> Hi,
> 
> I tried another last fresh install but this time I tried **php5.6** and projectsend **r1053** - alas, still no success.
> 
> Accessing: `yourprojectsendlocation/install/make-config.php`
> Shows: **The configuration file already exists.**
> 
> Accessing: `yourprojectsendlocation/install`
> Throws an **HTTP ERROR 500**
> 
> At this point I'm afraid to ask, but does this software even run? If so, what are the requirements?
> 
> The last two major releases do not work. It seems impossible to get it up and running.
> 
> If there is no answer I consider this project dead.

I had the same issue. I fixed it by setting the authentication method on my mysql user to 'mysql_native_password'. This seems to do the trick. Let me know if you get it working this way

**Comment by joseon-penggwin** [comment]
> > @ignacionelson
> > Hi,
> > I tried another last fresh install but this time I tried **php5.6** and projectsend **r1053** - alas, still no success.
> > Accessing: `yourprojectsendlocation/install/make-config.php`
> > Shows: **The configuration file already exists.**
> > Accessing: `yourprojectsendlocation/install`
> > Throws an **HTTP ERROR 500**
> > At this point I'm afraid to ask, but does this software even run? If so, what are the requirements?
> > The last two major releases do not work. It seems impossible to get it up and running.
> > If there is no answer I consider this project dead.
> 
> I had the same issue. I fixed it by setting the authentication method on my mysql user to 'mysql_native_password'. This seems to do the trick. Let me know if you get it working this way

What can I say, you are a saint. I would've never figured that out. I simply changed the _mysql_native_password_ for the psdbuser like you said and it instantly worked!

Thank you **so much** for finding out and commenting!
