### ISSUE TITLE
View Files page cannot be loaded

### ISSUE THREAD

**Issue by outerspace2040** [projectsend/projectsend#779]
View My Files: [site] /ProjectSend-cftp/my_files/ cannot be loaded. But the rest works.

**Comment by lavinhatti** [comment]
Hi, @outerspace2040.
This session is for reporting errors in the project, not for isolated cases. If you believe that this issue has a general impact, and not just on your configuration and installation of the project in the hosting, detail how the issues occurs with technical information. Use the community correctly.

**Comment by lavinhatti** [comment]
Hi, @outerspace2040 .
This session is for reporting issues in the project, not exactly for isolated cases. If you believe that this issue has a general impact, and not just on your configuration and installation of the project in the hosting, aniway detail how the issues occurs with technical information. Use the community correctly.

**Comment by lavinhatti** [comment]
Hi, @outerspace2040 .
This session is for reporting issues in the project, not exactly for isolated cases. If you believe that this issue has a general impact, and not just on your configuration and installation of the project in the hosting, anyway please detail how the issues occurs with technical information.

**Comment by outerspace2040** [comment]
Good Morning Murilo Lavinhatti, The above link is a landing page for client, which gives a 'page cannot be loaded' error. That is the detail. What else you have in mind? Can you elaborate your conclusion on this being an isolated issue. As an user, how can we confirm that it is an isolated issue, and if isolated, is there a place to discuss a solution?

By the way, I received an email with your previous impolite response before you edited, you may want to work on that.

**Comment by outerspace2040** [comment]
Uninstalled.

**Comment by ignacionelson** [comment]
Sorry about that. You can enable debug mode if you need to check for specific errors

**Comment by lavinhatti** [comment]
Hello @outerspace2040 , I am learning English which makes it a little difficult for me to give a formal answer, I also do not represent this project. GitHub is a community of collaborators in the programming world, I'm sorry if you were offended by me talking about the purpose of this category "issues".
