### ISSUE TITLE
Not an issue - Filesize on download page

### ISSUE THREAD

**Issue by keehan-git** [projectsend/projectsend#780]
Hi,
This is not an issue and I'm not a coder by any means, but I wanted to have the file size shown on the download page so someone would know what they're in for before downloading a large file, so in download.php at around line 52 I added the following variable right below the line starting $file_on_disk where the script gets the file on disk name;

`$file_on_disk   = $got_url['url'];`
`$formatted_size = html_output(format_file_size(get_real_size(realpath(UPLOADED_FILES_FOLDER.basename($file_on_disk)))));`

...and then I added $formatted_size where ever I wanted to see it, for example;
Around line 157;
`<?php echo $real_file_url; ?><br/>File Size: <?php echo $formatted_size; ?>`
and on the download button around line 163;
`<?php _e('Download file'.' ('.$formatted_size.')','cftp_admin'); ?>`

I'm just offering this in case someone else might find it useful.   Thanks!

**Comment by ignacionelson** [comment]
Added in r1265, thank you!
