### ISSUE TITLE
current list of dependencies - out of date & some missing 

### ISSUE THREAD

**Issue by thewriteway** [projectsend/projectsend#786]
The existing required list of packages doesn't seem to let projectsend work correctly out of the box.

I had to install the following packages specifically to get it to work:
mariadb-server mariadb-client
php7.3 php7.3-fpm php7.3-mysql
nginx
php-xml

Can this be updated in the docs?

**Comment by thewriteway** [comment]
no response from developer

**Comment by ignacionelson** [comment]
Hi @thewriteway 
I have updated the readme a while ago, but I recognize that I do need to add some more details about known good configurations. Thanks for your  input!
