### ISSUE TITLE
download slowly and never finish

### ISSUE THREAD

**Issue by 4allprograms** [projectsend/projectsend#789]
Hello... does anyone here have the same problem as I had? my users complain that download is very slow...

![download](https://user-images.githubusercontent.com/48699477/81504988-a67d1400-9316-11ea-865f-da78a6677e6a.png)

I have upgraded my server to SSD, RAM 8GB, 4 cores, 200 Mbit/s port, and UNLIMITED Traffic. But I still have facing the same issue.
I hope I can find any solution here...

**Comment by ignacionelson** [comment]
If possible, enable XSendFile module on your webserver, and then check the option in PS itself. This bypasses php when downloading files.
