### ISSUE TITLE
white screen after install

### ISSUE THREAD

**Issue by pieterv1981** [projectsend/projectsend#791]
hi

i just installed projectsend r1070 on a fresh centos 7 with php 7.3 and mariadb latest version

when i do a tail i'm getting below error

 [php7:error] [pid 1659] [client 192.168.230.206:53146] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/projectsend/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/projectsend/bootstrap.php on line 12

when i go to my ip i'm getting a white screen so not possible to configure it.

**Comment by ignacionelson** [comment]
Hello! It seems like you downloaded the master from this repository, but that won't work just yet. Please install the latest release from https://www.projectsend.org/
Thanks!

**Comment by jlowe42** [comment]
Hi Ignacio, I have the same problem as pieterv1981.  I tried to download the file from https://www.projectsend.org/   first, but was unable to.
There does not appear to be a file to download?

**Comment by ignacionelson** [comment]
Please try with the latest version. Thanks!
