### ISSUE TITLE
problem with connecting to database - SOLUTION

### ISSUE THREAD

**Issue by jellevdbos** [projectsend/projectsend#793]
Hi! People keep opening issues about nog being able to connect to their database. You always respond with folder permissions. Altough this might be an issue, I have noticed that most of the time that is not the problem. I found that this issue sits in the mysql database. When people use a mysql 8.x database, they encounter the problem of not being able to connect and not getting an error message in the webpage. This is due to the mysql 8.x default authentication method (caching_sha2_password). You can resolve this issue by setting the authentication method of your database user to mysql native password. You can read more about it here: https://dba.stackexchange.com/questions/209514/what-is-mysql-native-password

Maybe you could state this in the install instructions? I think this would prevent a lot of peoples issues.

**Comment by ignacionelson** [comment]
Thank you! I've added this to the readme and made sure to mention you too!
