### ISSUE TITLE
Translation link not work

### ISSUE THREAD

**Issue by webriz** [projectsend/projectsend#795]
Download Link in this page not work:
https://www.projectsend.org/translations/index.php

**Comment by ignacionelson** [comment]
Thanks for the heads up! Fixed it!

**Comment by alexschomb** [comment]
@ignacionelson No translations are available anymore - likely a bug? Unfortunately this causes our docker container to infinitely reboot (because the ZIP file for the translation couldn't be found).

**Comment by ignacionelson** [comment]
@alexschomb  Sorry about this. I need to update the translation manager on the site, transifex changed their API and it seems the version I was using is not available since yesterday. I'll fix this today, it's a huge issue. Thanks for reporting
