### ISSUE TITLE
Download Zipped bug

### ISSUE THREAD

**Issue by hcstudiosrl** [projectsend/projectsend#796]
Hi there,

I've found a bug in r1070 ProjectSend version. If i select more than one file and then select "download zipped", ProjectSend freezes and download never starts.

How i can fix it? Is there a patch?

PHP Version: 7.1

![Screenshot_1](https://user-images.githubusercontent.com/67115695/85047939-d4b20700-b192-11ea-8dcb-8376e35751fd.jpg)

Thanks

**Comment by ignacionelson** [comment]
Please try with version r1265
