### ISSUE TITLE
Remove: ProjectSend news

### ISSUE THREAD

**Issue by vinaypasari** [projectsend/projectsend#797]
Hi ,

Is there any Posibility to Remove ProjectSend news from the Admin Login Page ?

**Comment by PalmaSolutions** [comment]
Just remove or comment this line out of home.php:

                                <?php include_once(WIDGETS_FOLDER.'news.php'); ?>

**Comment by ignacionelson** [comment]
Since r1265, you need to remove this line from dashboard.php
`<?php include_once WIDGETS_FOLDER.'news.php'; ?>`
