### ISSUE TITLE
File upload incomplete, file corrupt (1 MB missing)

### ISSUE THREAD

**Issue by paulantongerlitz** [projectsend/projectsend#799]
Hi!

I encountered several instances where an uploaded file, despite showing as completely uploaded, was missing around 1 MB at the end and was corrupt after downloading.
It happened with larger and smaller files (100 MB and 700 MB) and different file types (zip, mp4). The upload progress always seemed to be fine within the Project Send interface. Also, the file on the FTP server looked fine (was renamed correctly), but was missing some Bytes compared to the local original.

Has anyone encountered something similar? What steps can I take to trace down this behaviour?

**Comment by ignacionelson** [comment]
Should be fixed on version r1265
