### ISSUE TITLE
[Feature Request] Add file by URL?

### ISSUE THREAD

**Issue by Skyridr** [projectsend/projectsend#800]
I noticed that there's only a function to upload files. But what about existing files you have on your web server that you can use? I don't seem to see any option to add a file by URL instead. Which is quite useful if a lot of those files are over 1GB in size and don't wish to re-upload those.

**Comment by jeff-fab** [comment]
I'm a new user, so pardon me if I'm missing the point -- if the files are already on your web server, you can just move them to the /upload/files folder and then in the interface you can use Files > Find Orphaned Files to pull them into the system and assign them.

I've also been playing with the idea of bulk files, and have been doing sql updates to tbl_files_relations and tbl_notifications to avoid having to tag each file individually in the GUI, let mek now if you want to know more about that.

**Comment by Skyridr** [comment]
I wasn't actually aware of this! I was looking for the function when adding a file. Thanks :).
