### ISSUE TITLE
Automated <br /> in description not working? Shows as text.

### ISSUE THREAD

**Issue by Skyridr** [projectsend/projectsend#802]
When you set a description like so:

![image](https://user-images.githubusercontent.com/6794064/87333378-52242980-c53d-11ea-9e27-d0f71cd1bd0c.png)

And save it, so it'll add the brackets automatically: 

![image](https://user-images.githubusercontent.com/6794064/87333413-5e0feb80-c53d-11ea-8844-cb9fa3ef0e9c.png)

It'll show like this (on php 7.4, nginx) on the download page:

![image](https://user-images.githubusercontent.com/6794064/87333461-6d8f3480-c53d-11ea-89b9-7b9bd53e9fbd.png)

Brackets are broken in **non**-visual editor? As when I switch to use visual editor, everything works fine.

**Comment by Elfernovich** [comment]
I have the same problem. Did anyone have a solution or idea on how to solve this?
/Thanks

**Comment by ignacionelson** [comment]
Should be fixed in r1265
