### ISSUE TITLE
Symbols like " and > < breaks description, replaced with "&amp;quot; &amp;gt;"

### ISSUE THREAD

**Issue by Skyridr** [projectsend/projectsend#803]
Apparently " and < > (most likely more)

![image](https://user-images.githubusercontent.com/6794064/87515894-d0d3b080-c67c-11ea-94d4-31c234be396e.png)

Are being replaced with: 

![image](https://user-images.githubusercontent.com/6794064/87515919-dcbf7280-c67c-11ea-8117-c367e484fef0.png)

Same happens if I disable the visual editor. Because of this, I can't properly use HTML in descriptions.

**Comment by Skyridr** [comment]
It also seems to be affecting file titles btw.

**Comment by ignacionelson** [comment]
The easiest solution for a new install is to replace the collation of the tables and the fields to utf8mb4_general_ci and then cancel the function that encodes/decodes the strings. I've been trying to find a solution that will apply to existing installations but I don't have a fully working one right now.

**Comment by Skyridr** [comment]
@ignacionelson 

I get the utf8mb4 convert, no clue how to cancel the en/decode function though.

**Comment by ignacionelson** [comment]
Check these 2 functions in includes/functions.php:
html_output 
and
encode_html

I believe that just by returning the untouched string, most functions that save and then return a value from the db should be fixed.

**Comment by Skyridr** [comment]
Still lost, sorry ^^. This is not my area of expertise.

**Comment by Skyridr** [comment]
Any updates?

**Comment by Skyridr** [comment]
@ignacionelson Update would be nice. Would appreciate it.

**Comment by ignacionelson** [comment]
Should be fixed in latest release r1265
