### ISSUE TITLE
(Auto) Delete expired files

### ISSUE THREAD

**Issue by protego-it** [projectsend/projectsend#804]
Is it possible to auto wipe expired files? 
Best would be a cron job wiping all expired files once a week. If it's not possible, is it on the roadmap as a new feature?
Would be really appreciated.

**Comment by ignacionelson** [comment]
I will be adding a cron job to handle deleting files and sending emails in the next version. Thanks for the suggestion!

**Comment by protego-it** [comment]
Hey Ignacio, thanks for your reply. I still use your software, so an upgrade would be great. 
Many thanks for your work.

**Comment by kfoxton** [comment]
Hi Ignacionelson, has this been implemented into a build yet?

Thanks!

**Comment by mayk78** [comment]
Hi,

i would love such feature to auto clean expired files (optionally with a definable grace period as to wait x days between expiry date and effective deletion).
thanx

**Comment by Racle** [comment]
Hey @ignacionelson, is this implemented yet?

This seems to pretty much the same request as #92 from 2016

If not, is there any workaround to do this automatically ex. in [docker container](https://hub.docker.com/r/linuxserver/projectsend)?

**Comment by ignacionelson** [comment]
Working on it!

![cron](https://user-images.githubusercontent.com/6926562/161908923-f507c48f-f86f-42fe-a916-6e19503e39ed.png)

**Comment by iincitr** [comment]
Very good news:)

6 Nis 2022 Çar, saat 09:22 tarihinde Ignacio Nelson <
***@***.***> şunu yazdı:

**Comment by rose-a** [comment]
@ignacionelson Awesome! 👍 🎉 

Now the last thing missing ist to make file expiring "opt out" instead of "opt in", since your average user will of course forget to check that box... 🙈

**Comment by ignacionelson** [comment]
@rose-a Done! You can pull the files from ace39c09c3e435a85c5cd2f419406a4dae87cc29 if you don't want to wait for a new release
