### ISSUE TITLE
[Question] How do I change the Upload Folder in ProjectSend?

### ISSUE THREAD

**Issue by joseon-penggwin** [projectsend/projectsend#805]
Hello,

since we need more space for uploaded files and want to attach an external storage, how can I change the file path in ProjectSend?

Thank you!

**Comment by ignacionelson** [comment]
Hello!
You could make a symlink between the /upload folder and any folder in the external storage that you might want to use
Here's an example on how to do it
https://www.shellhacks.com/symlink-create-symbolic-link-linux/
Hope that helps!

**Comment by joseon-penggwin** [comment]
Thank you! I will give this a try and will open a bugreport if this doesn't work.
