### ISSUE TITLE
Can I protect webpage with password?

### ISSUE THREAD

**Issue by 4allprograms** [projectsend/projectsend#811]
Does anyone here know how to protect the webpage with a password? such as file "download.php"
before user try to download a file then they must enter a password to access the file before!

**Comment by ignacionelson** [comment]
Hi! If you are using Apache, you could do something like this:
https://stackoverflow.com/questions/23312929/password-protecting-a-single-page-using-htaccess-and-htpasswd

**Comment by 4allprograms** [comment]
I'm using Nginx... do u have other tips?

**Comment by ignacionelson** [comment]
You can do something similar, just a little big more involved
https://geekflare.com/protect-page-with-password/
