### ISSUE TITLE
ProjectSend Directory Suddenly Redirects to /Install/index.php

### ISSUE THREAD

**Issue by Pirate727** [projectsend/projectsend#814]
Everything has been working fine, then all of the sudden it started sending to the install subdirectory and index.php.  No matter what we type to get there...the subdomain or the domain + directory.  It sticks the install/ after it.  Checked everything and I'm not sure why this is happening.  Ideas?

Thanks in advance.

**Comment by ignacionelson** [comment]
Seems like ps is not finding the required tables in your database. Please check if mysql is up, if all tables are present, and if the prefix defined in the config file corresponds to the ones on the actual database

**Comment by Pirate727** [comment]
After fighting to figure this one out for over 5 hours, it turns out that Cpanel pushed out a corrupted SQL update today at 2:30P ET.  We rolled it back and solved the issue.  I'm gonna start with that next time.  Especially when all other vars are correct.  What a waste of an evening.  Thanks for your response @ignacionelson
