### ISSUE TITLE
Recent activites (needs type fixing) and doesn't load on debug mode on latest version

### ISSUE THREAD

**Issue by Skyridr** [projectsend/projectsend#817]
activites should be activities ^_^

Also. When using debug mode on the latest (beta) version, its not loading the history at all. 

![image](https://user-images.githubusercontent.com/6794064/98517942-fc535a00-226e-11eb-8834-8e11347310d4.png)

Does work when not using debug mode. But it appears these errors may have something to do with it when I go to actions-log.php

> 
> Notice: Undefined index: details in /includes/functions.actionslog.php on line 16
> 
> Notice: Undefined index: details in /includes/functions.actionslog.php on line 16
> 
> Notice: Undefined index: details in /includes/functions.actionslog.php on line 16
> 
> Notice: Undefined index: details in /includes/functions.actionslog.php on line 16
> 
> Notice: Undefined index: details in /includes/functions.actionslog.php on line 16
> 
> Notice: Undefined index: details in /includes/functions.actionslog.php on line 16
> 
> Notice: Undefined index: details in /includes/functions.actionslog.php on line 16
> 
> Notice: Undefined index: details in /includes/functions.actionslog.php on line 16
> 
> Notice: Undefined index: details in /includes/functions.actionslog.php on line 16
> 
> Notice: Undefined index: details in /includes/functions.actionslog.php on line 16
> 
> Notice: Undefined index: details in /includes/functions.actionslog.php on line 16
> 
> Notice: Undefined index: details in /includes/functions.actionslog.php on line 16
> 
> Notice: Undefined index: details in /includes/functions.actionslog.php on line 16
> 
> Notice: Undefined index: details in /includes/functions.actionslog.php on line 16
> 
> Notice: Undefined index: details in /includes/functions.actionslog.php on line 16

Yup, same line gets spammed on the same page.

Running nginx on PHP 7.4 FPM

**Comment by ignacionelson** [comment]
This should be fixed in r1270. r1265 wasn't creating the details column. Thanks!

**Comment by Skyridr** [comment]
@ignacionelson 

What about the small type in the word "activites"? Should be activities
