### ISSUE TITLE
Error 500 while trying to download file

### ISSUE THREAD

**Issue by kimsvane** [projectsend/projectsend#818]
This page isn’t working right URL can't currently handle this request.
HTTP ERROR 500

I am trying to download a file by clicking on it, this ends up with an error 500.

**Comment by Skyridr** [comment]
See: https://github.com/projectsend/projectsend/issues/812#issuecomment-723851505

**Comment by podzit** [comment]
same issue here. Download doesn't work anymore with shared URL. I'm thinking about downgrading.

**Comment by ignacionelson** [comment]
Oh :( Is there anything in the error log?

**Comment by ignacionelson** [comment]
What php version are you using?

**Comment by podzit** [comment]
The php version is 7.3
Download in debug mode:
Notice: Undefined index: HTTP_CLIENT_IP in /home/skankinbox/www/skankinbox/includes/functions.php on line 1710

Notice: Only variables should be passed by reference in /home/skankinbox/www/skankinbox/includes/functions.php on line 1618

Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'details' in 'field list' in /home/skankinbox/www/skankinbox/includes/database.php:25 Stack trace: #0 /home/skankinbox/www/skankinbox/includes/database.php(25): PDO->prepare('INSERT INTO tbl...') #1 /home/skankinbox/www/skankinbox/includes/Classes/ActionsLog.php(154): PDOEx->prepare('INSERT INTO tbl...') #2 /home/skankinbox/www/skankinbox/includes/Classes/Download.php(166): ProjectSend\Classes\ActionsLog->addEntry(Array) #3 /home/skankinbox/www/skankinbox/includes/Classes/Download.php(39): ProjectSend\Classes\Download->downloadFile('1601739361-839d...', 'pack-promo-the-...', '93') #4 /home/skankinbox/www/skankinbox/process.php(91): ProjectSend\Classes\Download->download('93') #5 {main} thrown in /home/skankinbox/www/skankinbox/includes/database.php on line 25

**Comment by Skyridr** [comment]
It's like the updating isn't adding a new sql column that exists in the new version?

**Comment by podzit** [comment]
I didn't see any database update after updating because login has a bug I need to refresh to log correctly. How can I manually do the database update?

**Comment by ignacionelson** [comment]
I missed a ! during the update process. The script was not creating the new tables because they were **not** found
I've uploaded a new release, r1270 with this fix. Sorry!

**Comment by podzit** [comment]
Where is the r1270?

**Comment by ignacionelson** [comment]
https://www.projectsend.org/download/367/

**Comment by podzit** [comment]
ok login is better I don't need to refresh anymore but download has allways a bug. It download a 0 byte file with the correct name.

**Comment by ignacionelson** [comment]
Is XSendFile enabled in the general options page? If you enabled it but don't have the module, downloads will be 0 bytes

**Comment by podzit** [comment]
Ok ! With Xsendfile disabled everything is fully functional ! Thank you !

**Comment by ignacionelson** [comment]
Glad it worked! Closing the issue then.
