### ISSUE TITLE
Login never redirects

### ISSUE THREAD

**Issue by kimsvane** [projectsend/projectsend#819]
When logging in, the page never redirects to the dashboard, users have to refresh page before able to access site.

**Comment by Skyridr** [comment]
Can confirm this. Logging in just makes the login button "spin" indefinitely but does nothing.

**Comment by podzit** [comment]
Same issue here.

**Comment by ignacionelson** [comment]
Looks like there's an error in the json response. Could you please check the network tab in the browser's console for the ajax call to the login method? In the response tab there should be a visible php error

**Comment by Skyridr** [comment]
@ignacionelson 

> Failed to load resource: the server responded with a status of 500 ()

Guess its tied to the other 500 errors regarding the missing column in database.

**Comment by kimsvane** [comment]
@ignacionelson [https://imgur.com/a/MdE91FP](url)
Here you can see the error, its also gives an error 500 when logging out.

**Comment by ignacionelson** [comment]
Guess it's related to the missing column on the log table. r1270 should solve this, sorry!

**Comment by kimsvane** [comment]
Awesome, works now. 
The only thing, which i dont know if i shoule create a new thread, but the download zip, does "work" it downloads a zip file, but it's empty. 
Any idea why it's not zipping files?

**Comment by kimsvane** [comment]
I'll close it now :) 
Thanks alot @ignacionelson for solving this quickly. :)
