### ISSUE TITLE
Changing FOOTABLE_PAGING no longer possible? 

### ISSUE THREAD

**Issue by kimsvane** [projectsend/projectsend#820]
I had just changed the FOOTABLE_PAGING number, and then i updated. Wanted to change it again, but now the settings seems to be gone in the file, and i cant find then in the database... 

how can i change the items to show on a files page ?

**Comment by ignacionelson** [comment]
Hi!
On includes/app.php you can change
define('RESULTS_PER_PAGE', '10');
To anything you need
FOOTABLE_PAGING_NUMBER is still there, but unused. Sorry!

**Comment by kimsvane** [comment]
Thanks, that helped :D
