### ISSUE TITLE
Latest Statistics in new update are not mine.

### ISSUE THREAD

**Issue by Skyridr** [projectsend/projectsend#822]
For some reason, the Statistics that shows in the latest update, are not mine at all:

![image](https://user-images.githubusercontent.com/6794064/98550906-f70d0400-229c-11eb-9711-a008d9136bf0.png)

I only have 1 user, not 21. Any idea what's up with this? All my own data seems to be gone.

**Comment by ignacionelson** [comment]
Sorry, uploaded the wrong file (the one you got is used for testing). I've updated the zip with the right one. Please download again from https://www.projectsend.org/download/367/
Sorry!

**Comment by Skyridr** [comment]
No worries, I shall try.. Thanks! ^_^

Love the project btw! Really appreciate it.

**Comment by Skyridr** [comment]
Seems to be solved, many thanks!
