### ISSUE TITLE
install/index.php

### ISSUE THREAD

**Issue by freejaso** [projectsend/projectsend#825]
I am getting a blank page.

Turned on the debug in app.php and I get the following:

Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1835 Malformed communication packet in /home/surveyhealthcare/public_html/fileshare/includes/database.php:20 Stack trace: #0 /home/surveyhealthcare/public_html/fileshare/includes/database.php(20): PDO->query('SELECT version(...') #1 /home/surveyhealthcare/public_html/fileshare/install/index.php(15): PDOEx->query('SELECT version(...') #2 {main} thrown in /home/surveyhealthcare/public_html/fileshare/includes/database.php on line 20

How to fix?

**Comment by ignacionelson** [comment]
Hi!
Are you by chance using the latest mariadb version and php 7.2 or lower? There's a mariadb bug that produces this error. The solution is to upgrade php to 7.3 or newer,  or downgrade mariadb.

**Comment by freejaso** [comment]
PHP: 7.3.6
MariaDB: 10.3.26

**Comment by freejaso** [comment]
Upgraded to PHP 7.4 and I am good now.

**Comment by ignacionelson** [comment]
Great! Thanks for the update!
