### ISSUE TITLE
How to modify the number of results?

### ISSUE THREAD

**Issue by mike-miguel** [projectsend/projectsend#838]
I want to change the number of files that are listening on new version r1270
It is possible to avoid looking page a page?
Thanks in advance!
M.

**Comment by ignacionelson** [comment]
Hi! You can change the constant RESULTS_PER_PAGE in includes/app.php to any number you want.
I've added an option for this in the general options page and will be available in the next release.

**Comment by mike-miguel** [comment]
Hi Ignacio,

Thanks for your great support! It works fine for admin, but not for Clients (still have 10).
Cheers,
M.

**Comment by ignacionelson** [comment]
Oh sorry! In that case you need to modify templates/default/template.php, line 12
define('TEMPLATE_RESULTS_PER_PAGE', 10);
With your desired value

**Comment by mike-miguel** [comment]
Great! Thanks a lot for your great support @ignacionelson 
Cheers!
M.
