### ISSUE TITLE
Account Manager can't see news/stats

### ISSUE THREAD

**Issue by Znuff** [projectsend/projectsend#839]
Users with Level 8 ("Account Manager") get the embedded ajax widgets on their dashboards -- the stats and the news one.

But the `statistics.php` file is hardcoded to allow only Level 9 users to view them:

```
if (!defined('CURRENT_USER_LEVEL') or CURRENT_USER_LEVEL != 9) {
    header("Location: ".BASE_URI);
    exit;
}
```

Resulting in an infinite loading graphic on the dashboard.

Version: r1270

**Comment by ignacionelson** [comment]
Pushed the fix, thanks

**Comment by ignacionelson** [comment]
Fixed in r1295
