### ISSUE TITLE
Normal users can't browser own files pages

### ISSUE THREAD

**Issue by Znuff** [projectsend/projectsend#840]
As per title, 

When a normal client logs on and browses the "My Files" section, he gets the wrong link for pagination, as the code is hardcoded to `users.php`:

https://github.com/projectsend/projectsend/blob/8b6d0aec9913b2409dfa85f346b9304cd1f1115c/templates/default/template.php#L307

This will result in an error, because clients aren't allowed to access `/users.php`

Version: r1270

**Comment by mike-miguel** [comment]
Yes...same problem to me!

**Comment by ignacionelson** [comment]
Oh, sorry about this!
@mike-miguel thanks for the solution. I've applied it to the same release to have it available quickly, but will have a new release with this and a few more tweaks ready in a couple of days.
@Znuff please apply mike's change or redownload r1270.

**Comment by Znuff** [comment]
How is that a proper solution, though?

Isn't that template used anywhere else? Shouldn't the filename/url be generated automatically?

Previous versions used `basename()` on a `$_SERVER` key.

**Comment by ignacionelson** [comment]
This needs to be standarized. Some pages use basename($_SERVER['SCRIPT_FILENAME']), others don't.
As a quick solution to prevent more broken downloads it's ok, not as a long time one.

**Comment by ignacionelson** [comment]
Fixed in r1295

**Comment by mike-miguel** [comment]
Congrats @ignacionelson
