### ISSUE TITLE
Corrupts / renames files on mass upload

### ISSUE THREAD

**Issue by sjgarth** [projectsend/projectsend#842]
I upload xlsx files with members details for a region. I upload 13 files at a time and allocate them to 13 groups for members to download. This has worked fine for over a year now.
Each file has the file name which includes the date and the region, for example '16-11-2020 WEST MIDLANDS.xlsx'
After the recent update the weirdest thing happens.
13 files all with individual names, all contain the data for the last file in the list,
I have checked the files that I am uploading before upload, they all contain different data. However after uploading they all contain the same data, but with their individual file names.

I have just tried it with two files, and the first file retained its name but contains the data of the second (last) file.

**Comment by ignacionelson** [comment]
Wow, this is weird indeed!
The upload processing didn't change much. But plupload was updated so maybe it has something to do with it? Never had this happen before.
Which php version are you using?

**Comment by ignacionelson** [comment]
I've tested locally with the files you attached and everything went well.

**Comment by sjgarth** [comment]
Thanks for your reply.I am usingPhp 7.4.9Mysql 5.7.32I have pre-installed latest project send files to see if that helped (maintaining my sys-config file) with no change.YoursSteve GarthSent from my phone.
-------- Original message --------From: Ignacio Nelson <notifications@github.com> Date: 17/11/2020  01:50  (GMT+00:00) To: projectsend/projectsend <projectsend@noreply.github.com> Cc: sjgarth <sjgarth@gmail.com>, Author <author@noreply.github.com> Subject: Re: [projectsend/projectsend] Corrupts / renames files on mass upload (#842) 
Wow, this is weird indeed!
The upload processing didn't change much. But plupload was updated so maybe it has something to do with it? Never had this happen before.
Which php version are you using?

**Comment by ignacionelson** [comment]
Have you checked the files in the upload/files directory? It would help to know if they actually are wrong in the disk, or this is a download problem

**Comment by sjgarth** [comment]
Very interesting results.
I uploaded and allocated 13 files all named, as before, date then region, e.g 16-11-2020 WEST MIDLANDS.xlsx.
On the frontend everything went as normal.
![frontend](https://user-images.githubusercontent.com/74574374/99388563-b1b88a00-28cd-11eb-98a7-1f3a39dcaac0.png)
Using Filezilla I went to uploads/files and saw only 4 recent files uploaded, all with incomplete names, shown in the screenshot. Note the files uploaded before the update are also shown with correct names.
![filezilla](https://user-images.githubusercontent.com/74574374/99387630-3c988500-28cc-11eb-8855-5d21c43b1c49.png)
The four files have different content.
Attempts to download any file from the frontend is one of these files except the file starting with pre which downloads as Wales.
I changed the filenames to remove any spaces, replacing spaces with -.
This had no effect. I uploaded 4 files, again front end was normal
![frontend2](https://user-images.githubusercontent.com/74574374/99388603-be3ce280-28cd-11eb-8255-080e11e6e641.png)
Looking at the upload/files folder showed only one upload this time, again with file name cut short
![filezilla2](https://user-images.githubusercontent.com/74574374/99388663-d7de2a00-28cd-11eb-8b6b-88df7826796d.png)
When downloading the files, only one was correct.
Over to you.

**Comment by sjgarth** [comment]
I've just been looking at the pictures above. I did the update around the 9th/10th of November and I noticed that the upload by a client on the 11th has had the capital letters removed. All my file names are capitals.
I will rename a few files and see if that makes a difference.

**Comment by ignacionelson** [comment]
Great find! I'll apply a patch. I want to release a new version this week, so I'll make sure to fix this

**Comment by sjgarth** [comment]
Great.
I will await the update.
Great program by the way.
I tried a number of document managers and this one ticks all the boxes I need.
Thanks.

**Comment by ignacionelson** [comment]
Thanks for the comment! If you need a fix right away, please try this
includes/functions.php

Replace
`$search = array('/[^a-z0-9\-<>_]/', '/[\-]+/', '/<[^>]*>/', '/[  *]/');`
with
`$search = array('/[^a-zA-Z0-9\-<>_]/', '/[\-]+/', '/<[^>]*>/', '/[  *]/');`

and
`return strtolower($filename.'.'.$extension);`
with
`return $filename.'.'.$extension;`

Hope that helps!

**Comment by sjgarth** [comment]
Your fix in the latest update works a treat, thank you
