### ISSUE TITLE
Download method X-Accel (Nginx)

### ISSUE THREAD

**Issue by 4allprograms** [projectsend/projectsend#849]
Hello dear...
I've been waiting for this feature for a long time but how do I use it? when I change it then I could not be able to download any files.

What do I need to do to make it work?

**Comment by ignacionelson** [comment]
Hi! You need to make a change to the domain config file in nginx.
When you select it in the admin area, PS gives you the code you need to use.
Here's an example from the official documentation:
https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/

**Comment by 4allprograms** [comment]
Don't you have another example... it's still confused me! I'm not familiar with that... thank you

**Comment by ignacionelson** [comment]
Oh, you need to put that into the site configuration in nginx sites.
The file is probably at /etc/nginx/sites-enabled/YOURSITE-FILE
Then you need to restart nginx. On debian based systems you could try sudo service nginx restart
If you are not really familiar with this, it's probably best to ask a developer to help you out

**Comment by 4allprograms** [comment]
hello... my codes look like this:
# Redirect server error pages to the static pages
error_page 500 502 504  /500.html;
location = /500.html {
    root	/usr/local/apps/nginx/etc/conf.d;
    internal;
}

error_page  404			/404.html;
location = /404.html {
    root	/usr/local/apps/nginx/etc/conf.d;
    internal;
}

error_page  497			/497.html;
location = /497.html {
    root	/usr/local/apps/nginx/etc/conf.d;
    internal;
}

error_page  555 /555.html;
location = /555.html {
    root	/usr/local/apps/nginx/etc/conf.d;
    internal;
}

location @maintenance {
    root	/usr/local/apps/nginx/etc/conf.d;
    rewrite ^(.*)$ /noindex.html break;
}

# Pass the INDEX.PHP script to FastCGI server listening on 127.0.0.1
location = / {
    fastcgi_read_timeout 3600;
    try_files $uri /index.php /index.html @maintenance;
    fastcgi_pass	unix:/usr/local/apps/php74/var/php74_9001.sock;
    fastcgi_param	SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param	SCRIPT_NAME	  	$fastcgi_script_name;
    include			fastcgi_params;
}

# For userdir files
location ~* ^/~(.+?)(/.*\.php)$ {

	alias /home/$1/public_html$2;
	fastcgi_pass	unix:/usr/local/apps/php74/var/php74_9001.sock;
	include fastcgi_params;
	fastcgi_param SCRIPT_FILENAME $request_filename;
}

# For userdir files
location ~ ^/~(.+?)(/.*)?$ {
	alias /home/$1/public_html$2;
	index  index.html index.htm index.php;
	autoindex on;
}

# To catch index.php by default
location ~ (index.php|/)$ {
    fastcgi_read_timeout 3600;
    try_files  $uri $uri/index.php $uri/index.html;
    fastcgi_pass	unix:/usr/local/apps/php74/var/php74_9001.sock;
    fastcgi_param	SCRIPT_FILENAME	$document_root$fastcgi_script_name;
    fastcgi_param 	SCRIPT_NAME		$fastcgi_script_name;
    include        	fastcgi_params;
}
            
# Pass the regular PHP scripts to FastCGI server listening on 127.0.0.1
location ~ \.php$ {
    fastcgi_read_timeout 3600;
    try_files $uri =404;
    fastcgi_pass	unix:/usr/local/apps/php74/var/php74_9001.sock;
    fastcgi_index	index.php;
    fastcgi_param	SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param	SCRIPT_NAME	  	$fastcgi_script_name;
    include		fastcgi_params;
}

location ~ \.pl|cgi$ {
    try_files $uri =404;
    gzip off;
    fastcgi_pass	127.0.0.1:8999;
    fastcgi_index	index.cgi;
    fastcgi_param  	SCRIPT_FILENAME	$document_root$fastcgi_script_name;
    fastcgi_param	SCRIPT_NAME     $fastcgi_script_name;
    include 		fastcgi_params;
}

could you help me for this matter?
