### ISSUE TITLE
Managing large number of files

### ISSUE THREAD

**Issue by KuhlmannJens** [projectsend/projectsend#86]
We've successfully launched or client support system with ProjectSend: a real blessing!!! While growing our file base, we look for ways to overview the growing amount of files.
E. g.: how to get more files viewed on one page? I recall someone mentioned that in another issue.
Other suggestions for structuring?
Thanks folks!

**Comment by lenamtl** [comment]
How many file you like to view per page?
I'm not sure to understand your needs...

**Comment by KuhlmannJens** [comment]
A number around 40 or 50 would be great: scrolling the page vertically 
is simply
quicker than swapping the page in the page number buttons (I assume, 
there will be
scrollbar when the files do not fit into the window).
My request was pretty vague in a way: sorry for that! The guys in our 
team who provide the
uploads also had other ideas like categorizing in folders or the like.
But as that means much more than just changing a number in the code, I 
think increasing
the files per page (on the long run making it configurable in the 
options, may be)
would definitely do a good job.
One of the postings sounded like having found an changed that number, 
but neither our
admin nor me found the respective line of code.

Thanks a lot for caring!

Best Regards

Jens

Am 04.03.2016 um 16:53 schrieb lenamtl:
>
> How many file you like to view per page?
> I'm not sure to understand your needs...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ignacionelson/ProjectSend/issues/86#issuecomment-192331411>.
>

-- 
Fwd: neu Email-Signatur Stage Tec
Messe Banner

*Jens Kuhlmann*
Dipl.-Ing
Support, Training, Service

	


	
	
	

Stage Tec Logo

	

Stage Tec Entwicklungsgesellschaft für professionelle Audiotechnik mbH
Tabbertstraße 10 - 11 | D-12459 Berlin | www.stagetec.com 
<http://www.stagetec.com/> | 
*/j.kuhlmann@stagetec.com/**/<mailto:office@stagetec.com>/*
*T: +49 30 639902-63* | F: +49 30 639902-32 | *M: +49 - 172 - 86 805 86*

	


Legal domicile: Berlin  | Commercial register Charlottenburg, HRB 49640
Managing Directors: Dr. Helmut Jahne
Authorized representatives: Claus-Peter Thomas, René Harder

**Comment by crashff00** [comment]
the file is includes\site.options.php
the lines to modify are: 
define('FOOTABLE_PAGING_NUMBER', '**50**');
define('FOOTABLE_PAGING_NUMBER_LOG', '**50**');

**Comment by chewy-chewbacca** [comment]
If anyone finds this and is on a newer version, like r1295 this option has moved into the DB in tbl_options and the previous fix doesn't work. Option is "pagination_results_per_page".
