### ISSUE TITLE
Update r1070 -> r1295 

### ISSUE THREAD

**Issue by hpdorn** [projectsend/projectsend#861]
After an update (as described here: https://www.projectsend.org/how-to-update-projectsend/) the screen reamins blank after a refresh of the page.

Is an update  r1070 -> r1295 supported?

**Comment by Errious** [comment]
Use a different Browser, had the same with using Chrome in Firefox was working.

**Comment by hpdorn** [comment]
Thanks for the answer, but it didn't work in:

Firefox
Firefox developer edition
Brave
IE
Edge
Opera
Blisk
Chrome

**Comment by davidsandbrand** [comment]
I am having the same issue after the same upgrade, on two separate installations.

Any diagnosis steps would be appreciated, and I'm happy to provide logs or any info that could help.

Thanks all.

**Comment by ignacionelson** [comment]
Sorry about this everyone.
I don't think this is a browser issue. Maybe a php compatibility one. Please make sure that you are using php 7.1 or newer.
Also, any errors from the php error log (or anything that php may output if you enable debug mode in includes/app.php) could help me debug this.

**Comment by davidsandbrand** [comment]
I'm running PHP 7.2.  The server is a WHM/cPanel server that we run ourselves, for us (ie: I have root control).

Here's what gets output to screen with debug=true


`Warning: Use of undefined constant BASE_URI - assumed 'BASE_URI' (this will throw an Error in a future version of PHP) in /home/REDACTED-ACCOUNT_NAME/public_html/files.REDACTED-SITE_NAME.com/includes/text.strings.php on line 24`

`Warning: Use of undefined constant PUBLIC_GROUP_URL - assumed 'PUBLIC_GROUP_URL' (this will throw an Error in a future version of PHP) in /home/REDACTED-ACCOUNT_NAME/public_html/files.REDACTED-SITE_NAME.com/includes/text.strings.php on line 25`

`Warning: Use of undefined constant PUBLIC_DOWNLOAD_URL - assumed 'PUBLIC_DOWNLOAD_URL' (this will throw an Error in a future version of PHP) in /home/REDACTED-ACCOUNT_NAME/public_html/files.REDACTED-SITE_NAME.com/includes/text.strings.php on line 26`

`Warning: Use of undefined constant ASSETS_IMG_URL - assumed 'ASSETS_IMG_URL' (this will throw an Error in a future version of PHP) in /home/REDACTED-ACCOUNT_NAME/public_html/files.REDACTED-SITE_NAME.com/includes/text.strings.php on line 27`

`Warning: Use of undefined constant WIDGETS_URL - assumed 'WIDGETS_URL' (this will throw an Error in a future version of PHP) in /home/REDACTED-ACCOUNT_NAME/public_html/files.REDACTED-SITE_NAME.com/includes/text.strings.php on line 28`

`Warning: Cannot modify header information - headers already sent by (output started at /home/REDACTED-ACCOUNT_NAME/public_html/files.REDACTED-SITE_NAME.com/includes/text.strings.php:24) in /home/REDACTED-ACCOUNT_NAME/public_html/files.REDACTED-SITE_NAME.com/includes/active.session.php on line 10`

`Warning: Cannot modify header information - headers already sent by (output started at /home/REDACTED-ACCOUNT_NAME/public_html/files.REDACTED-SITE_NAME.com/includes/text.strings.php:24) in /home/REDACTED-ACCOUNT_NAME/public_html/files.REDACTED-SITE_NAME.com/includes/active.session.php on line 11`

`Warning: Cannot modify header information - headers already sent by (output started at /home/REDACTED-ACCOUNT_NAME/public_html/files.REDACTED-SITE_NAME.com/includes/text.strings.php:24) in /home/REDACTED-ACCOUNT_NAME/public_html/files.REDACTED-SITE_NAME.com/includes/active.session.php on line 15`

**Comment by davidsandbrand** [comment]
One other thing:  

The request to "/" is returning a 302 redirect to "/install/index.php", even though the system is not new, and is already configured.

/install/index.php is then returning a 500.

**Comment by ignacionelson** [comment]
I see. So PS is not finding the required tables on the database.
Are you using mariadb? The latest (or previous at least) version has a compatibility issue with php <= 7.3 that could be the cause of this.
Apache's log (or php's one) might have something on the 500 error too.

**Comment by davidsandbrand** [comment]
Fantastic, it's working now.

Yes, the server uses mariaDB.  So I changed the PHP version to 7.4, and then got a `Uncaught Error: Call to undefined function mime_content_type() ` error, so installed the fileinfo extension (which _was_ installed for v7.2) and all is good now.

Many thanks for the quick help, and I hope this helps others!

**Comment by hpdorn** [comment]
After changing PHP from version 7.2.x to 7.4.x the update worked as expected.
Thanks for all comments.
