### ISSUE TITLE
change password in the database

### ISSUE THREAD

**Issue by kkplein** [projectsend/projectsend#864]
Hi,

It is possible to change a user password directly in the mysql database?

We migrated to a different server, I imported the database, but we lost the admin password, and the lost password function uses email, which we cannot configure yet, because that has to be done from th GUI, which we cannot yet login to...

**Comment by kkplein** [comment]
We found of course the tables in the database, but the thing is: the password is encrypted in a way we don't recognise.

How can we generate a correct hash to set in the password field through mysql?

**Comment by ignacionelson** [comment]
Hi! You could create a new user from the registration form and copy the hashed password from that one. From the db directly it's not possible to set a password.
Another option would be to have a small script overwrite a password, but it will be dangerous to keep it in the server so you'll have to delete it after using it

**Comment by ignacionelson** [comment]
If you don't have self registrations allowed, change it in the db. Options table -> clients_can_register set to 1

**Comment by kkplein** [comment]
Ah yes! Excellent idea to take a hashed password from another user. It worked perfectly...! Thanks! We like the new version!

**Comment by eduardo18delta** [comment]
Just use bcrypt generator: https://bcrypt-generator.com/
