### ISSUE TITLE
r1295, file download is 0 bytes

### ISSUE THREAD

**Issue by pscarnegie** [projectsend/projectsend#866]
I can see the file within the uploads directory, and can successfully download it from there, however when I try to download it from the web interface the dowloaded file is always 0 bytes. I've tried both ZIP archives as well as downloading the file from the Manage Files link, both of them end up on the desktop as 0 bytes.

ProjectSend v1295
PHP v7.4.13

**Comment by zekikoese** [comment]
you probably activated x-sendfile download method. Try with PHP or configure x-sendfile first.

**Comment by pscarnegie** [comment]
Yep, that was it. I had the x-send option selected for the download method in the general options. I changed it back to PHP and it all works now as expected. Thank you for the rapid response.

**Comment by ignacionelson** [comment]
Glad you got this working, and thanks @zekikoese for answering!
