### ISSUE TITLE
Enable video files to be previewed

### ISSUE THREAD

**Issue by danielnr87** [projectsend/projectsend#87]
Hi,
This is almost perfect for a client who wants to server their clients videos they make. They have a current clientarea built upon wordpress but it is clunky and is causing issues with caching etc... A feature that is really good though is the ability to preview/watch the video in a lightbox before downloading it. It is a great feature as some of their video files are 1gb+ and a client doesn't have to wait before watching it.

Is this something that may be added in the future?
Also looking forward to bootstrap 3 version :)
Thanks

**Comment by lenamtl** [comment]
Hi,

I don't know about the load on the server about this.
When you say a preview is this mean that they will have the full version and a light version for the preview? like a movie preview ?

Bootstrap3 version is almost ready but I still have some issue to fix.

**Comment by danielnr87** [comment]
Hi, what I mean, is just a direct link to the file be opened, rather than compressing another version. Maybe opening in a standard html5 video embed, for certain formats like mp4. Maybe a fancybox http://fancyapps.com/fancybox/#docs

It wouldn't be a huge load on the server, as it would be the same as downloading.

Cheers

**Comment by lenamtl** [comment]
Ok I see

**Comment by earsneyes** [comment]
+1, a thumbnail for video files would be nice as well

**Comment by lenamtl** [comment]
I'm using this for the videos, so there is thumbnails when user click on it the video is in popup / overlay
http://dimsemenov.com/plugins/magnific-popup/

**Comment by earsneyes** [comment]
Nice thanks! Will see if i can make it work with my installation 👍

**Comment by mschop** [comment]
I created a new Issue #595 as a collective issue for file previews. Because of this I close this issue.

**Comment by ignacionelson** [comment]
Added in r1265
