### ISSUE TITLE
SVG Problems?

### ISSUE THREAD

**Issue by riiwjohnson** [projectsend/projectsend#871]
Hey all,

I pulled down the latest release and when I attempted to deploy it on buster w/the standard PHP 7.1 and Apache I got a blank page after the successful installation.  I dug around in the include directory, found the app.php and enable debug.  When I refreshed the page this was displayed:

`Fatal error: Uncaught Error: Class 'DOMDocument' not found in /var/www/ps/public_html/vendor/enshrined/svg-sanitize/src/Sanitizer.php:96 Stack trace: #0 /var/www/ps/public_html/vendor/enshrined/svg-sanitize/src/Sanitizer.php(200): enshrined\svgSanitize\Sanitizer->resetInternal() #1 /var/www/ps/public_html/includes/functions.php(1145): enshrined\svgSanitize\Sanitizer->sanitize('<?xml version="...') #2 /var/www/ps/public_html/includes/functions.php(1172): file_is_svg('/var/www/ps/pub...') #3 /var/www/ps/public_html/includes/functions.php(1249): make_thumbnail('/var/www/ps/pub...', 'proportional', 300, 300) #4 /var/www/ps/public_html/includes/functions.php(1277): generate_logo_url() #5 /var/www/ps/public_html/index.php(69): get_branding_layout(true) #6 {main} thrown in /var/www/ps/public_html/vendor/enshrined/svg-sanitize/src/Sanitizer.php on line 96`

I thought perhaps I was missing an SVG related include so I installed the related php-svg files but received no change in the error message. 

I went back to revision 1270 just to see if there was something that I missed, but it generates nearly the same error.  I'm assuming I'm missing something simple... Any suggestions?

**Comment by ignacionelson** [comment]
Hi! Have you downloaded the master from the repo directly? In that case you need to do
```
$ npm i
$ composer install
$ gulp

```
to download all dependencies and compile the assets
Hope that helps!

**Comment by riiwjohnson** [comment]
@ignacionelson it wasn't a direct fix, but it fixed it; I was missing the php-xml package from my install.  I knew it had to be something simple.  It appear that it isn't a default install on Debian's PHP.

**Comment by ignacionelson** [comment]
Oh, thanks for the heads up!
