### ISSUE TITLE
Asking to change your release naming scheme

### ISSUE THREAD

**Issue by WaffleThief123** [projectsend/projectsend#876]
Hey ProjectSend team, 

First and foremost, thanks for all the work you guys, gals, and nonbinary pals put into this project. It's downright amazing.

I had a quick request, I wanted to know if in your releases on github, if you would be able to tie the version number into the release notes, but change the actual zip file to projectsend.zip, so that it makes automation of pulling the latest build number for downstream projects lives easier. 

Many of them have download links hardcoded, and I suspect that making this change will make it easier to automate a download for them if they were to pull pull /releases/latest/projectsend.zip rather than /releases/latest/projectsend_releasenumer.zip

The reason I am bringing this up is that the linuxserver.io team has your builds hardcoded in github, and I would love for their lives to be easier with not having to update manually every release you push.
e.g. https://github.com/linuxserver/docker-projectsend/issues/17

Thanks Much!

**Comment by ignacionelson** [comment]
Sorry for not responding before and thank you for your comments!!
I've just updated the latest release by following your suggestion, thanks!
