### ISSUE TITLE
Sort "expiry" column like others columns

### ISSUE THREAD

**Issue by Sead13594** [projectsend/projectsend#880]
Hello everybody,

This tool is amazing. However, I would have liked to know if it would be possible (currently or during a future update), to add a possibility to sort (in manage-files) the "expiry" column exactly like the "uploaders" or "public permissions" columns. You can see the attached image for a better understanding of my question.

Many thanks in advance for any help!

![Capture d’écran 2020-12-28 140444](https://user-images.githubusercontent.com/75995862/103216557-a1f18400-4916-11eb-915f-de917ea7cbe7.png)

**Comment by ignacionelson** [comment]
Done on 08a6fbd
Not perfect as it only uses expires or not (does not order by expiry date). To do this I will need to separate the column into 2. Will look into doing that in the future!
