### ISSUE TITLE
Fufure Request :Filter unassigned file

### ISSUE THREAD

**Issue by iincitr** [projectsend/projectsend#886]
Hi,

Need to filtering for unassigned files. To find the files is very difficult in a large number of files.

thank you.
![projectsend file ](https://user-images.githubusercontent.com/58163198/135851731-32db1e4f-7332-4796-9a4d-3f221aa9c004.png)
![projectsend file filter](https://user-images.githubusercontent.com/58163198/135851738-45534cc6-d610-4228-b285-c26b77b8b924.png)

**Comment by iincitr** [comment]
Is there any progress?

**Comment by iincitr** [comment]
> Is there any progress?

**Comment by ignacionelson** [comment]
Done here cf64116d5d3ce0ef3001f0f66103dc1cd22552b1
If you are on r1415, you may simply replace manage-files.php on your installation

**Comment by ignacionelson** [comment]
![image](https://user-images.githubusercontent.com/6926562/170772027-b93b2931-a072-4ab6-ae6d-af2c862f58ef.png)

**Comment by iincitr** [comment]
Thank you:)

**Comment by ignacionelson** [comment]
Hope it helps!
