### ISSUE TITLE
Minor spelling/html fixes

### ISSUE THREAD

**Issue by rainyday4me** [projectsend/projectsend#887]
Very minor, but wanted to log these for you:

(1) File: text.strings.php

Line 39  'copy_ok' => __('Succesfully copied to clipboard','cftp_admin'), 
**Successfully** is misspelled

Line 48  'no_results' => __('No results where found.','cftp_admin'),
**where** should be ‘were’

(2) File: register.php
It appears that there is a </div> missing prior to the footer include at the bottom of the page.

**Comment by ignacionelson** [comment]
Thank you! Applied the changes here
https://github.com/projectsend/projectsend/commit/9aff1b8d6f290003f1b43ee3ecef6ee8248662b1

By the way, what is missing in register.php? You wrote:
It appears that there is **a missing prior** to the footer include at the bottom of the page.

Thanks!

**Comment by rainyday4me** [comment]
Thanks! I wrote (poorly) that there is a missing ending div prior to the footer include. :)
