### ISSUE TITLE
Group-membership-requests not working

### ISSUE THREAD

**Issue by schnudd31do3** [projectsend/projectsend#890]
While registering as client, I can choose the public groups where I would like to belong. Then in the client's section I can find the corresponding account-requests but there are no group-mebmership-requests.

I found that there were no entries made to the database table tbl_members_requests. After creating them manually (by phpmyadmin), the group-membership requests are shown in the account requests. But after accepting, they remain in the membership-requests. No changes were made to the clients "Groups on".

When successfully registered (but not assigned to groups) and I make a request to a group, the group-membership requests are shown in the account requests. But after accepting, they remain in the membership-requests. No changes were made to the clients "Groups on".

**Comment by ignacionelson** [comment]
Fixed on latest release
