### ISSUE TITLE
When X-Accel available for public download

### ISSUE THREAD

**Issue by 4allprograms** [projectsend/projectsend#895]
Hello, I just want to ask, when this features "X-Accel" available for Public Download? because this is only working for users

**Comment by ignacionelson** [comment]
Can you please check if this fixes the issue for you?
https://github.com/projectsend/projectsend/commit/dce96f0f30d8bbb84f3e2489e892f4aa437f335a

**Comment by 4allprograms** [comment]
No, it's not working at all...! I still got the same issue

**Comment by ignacionelson** [comment]
Are you getting any error on screen or on the log?

**Comment by 4allprograms** [comment]
the site can't be reached when I hit the "Download file" button

**Comment by 4allprograms** [comment]
sorry, I made mistake... Your code is working perfectly. Thank you very much
