### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by papazetis** [projectsend/projectsend#909]
Any solution I can make changes to css but without losing them on upgrade?

**Comment by protego-it** [comment]
You could clone the default template and create yours from it. But I updated recently to the latest version and literally everything in the code base changed, so it was useless anyway. Had to redo everything from scratch.
Quick and dirty solution is to add your custom css path in /includes/assets.php. Line 49

**Comment by ignacionelson** [comment]
You can now add custom css using the new assets manager (tools -> assets), or by creating a custom.css file in assets/css

**Comment by 4024051** [comment]
Im trying to update the css color theme from the app.  I have changed the main.css , used the custom tool for adding new code but it wont work. could not change the colors.
