### ISSUE TITLE
2FA 

### ISSUE THREAD

**Issue by deeks01** [projectsend/projectsend#919]
Hi - thanks for this beautiful project. 

My feature request would be 2-factor-authentication (2FA) so the data can be protected even better.
I use Duo more and more, also on my home projects.

**Comment by moscowchill** [comment]
That would be really nice

**Comment by ignacionelson** [comment]
Simple 2FA via email implemented in latest release. More providers will be added in the future

**Comment by dvgtrsnco** [comment]
Awesome Ignacio - thank you 🙏 !  will update my code soon!

Best regards,
Deeks

**Comment by ignacionelson** [comment]
Great!
Be aware of this issue  with this release
https://github.com/projectsend/projectsend/issues/1167
If you php and mysql dates do not match
It will be fixed on the next one, sorry!
