### ISSUE TITLE
Feature request: Auto delete of expired files

### ISSUE THREAD

**Issue by Mactory** [projectsend/projectsend#92]
I would love to see an auto deletion of expired files. Maybe expired files could be deleted a configureable amount of days after they expired.

**Comment by lenamtl** [comment]
+1

**Comment by baldzern4** [comment]
:+1:

**Comment by kgoldstraw** [comment]
+1

**Comment by lenamtl** [comment]
So it can be something like this
0 = do not deleted after expiration 
1 =  1 day after 
and so on

1 day after at what time?
Let say it set to expire on april 12th
so is going to be deleted april 13th at midnight?

We also need a cronjob that check and delete expired file based on the settings.

What do you think?

**Comment by cpcnw** [comment]
+1 Midnight on day of expiry should do it

**Comment by Mactory** [comment]
Just to be clear: Does midnight mean the END of the day or the BEGINNING?
In your example, I would delete the file at the END of April 13th.

**Comment by lenamtl** [comment]
Yes the end of the day

**Comment by crashff00** [comment]
As an extension to this request, could we also get the ability to set a default expiration time for files?  I have users that will upload files for clients without an expiration, and forget about them for weeks.  It would be nice to be able to set a configuration option for a default XX days before expiration applied to all files uploaded.

**Comment by Joohansson** [comment]
+1 For file specific setting and also a default setting that overrides. If this feature is added then projectsend fulfills all my needs. I searched a very long time for a system like this.

**Comment by Gerasch** [comment]
+1 @crashff00

**Comment by olimax** [comment]
did anything come of this?
it would be very useful to be able at least just list the expired files, like the Find Orphaned Files, or with a filter on the manage Files
or am I just missing something

**Comment by lenamtl** [comment]
@olimax You can create a custom filter for this.
I agree this can be useful for those who use the expiry option.

**Comment by olimax** [comment]
Thanks. I was just having a think about adding some sort of filters like WP to the file list
I'll see what I can come up with

**Comment by Tb0b** [comment]
+1 for the feature too :)

**Comment by Philtky** [comment]
+1 from 2019 :)

Hi @lenamtl, is it possible to know more about those custom filters? Would it be possible to create an auto-delete system with this?
Thank you!

**Comment by lenamtl** [comment]
Hi,
I have no idea about ETA (new PS version or updates)... 
I guess Ignacio will update us soon with his plans...

**Comment by ignacionelson** [comment]
I always find it really hard to find a point where I can say "this is worthy of a release". It has become harder lately with all the improvements to the code that I'm adding and the plans that I have to make PS more extensible, open and easier to develop.
Right now I have a list of ~10 very small things that I need to resolve (some are testing, some are minor code changes) and 1 large item that's my main focus (redoing the upload process, with a new class). 
I hope that after this new class is applied, everything will feel right to make the release.

**Comment by rose-a** [comment]
This is working now using the new cronjob feature! 🎉
