### ISSUE TITLE
Large amount of files issues 

### ISSUE THREAD

**Issue by vichanws** [projectsend/projectsend#94]
I have install the ProjectSend and I have insert 1500 files on it.
I found that it needs take 15 seconds to load the manage-files.php.
Is it normal? Is there anyway to improve the speed?

Thanks

**Comment by lenamtl** [comment]
Are they big file or not?
I'm using a pagination this may help in case of this situation.
Maybe a pruning the old files can be a temporary solution.

Also server hardware and internet connexion can be a the problem too.

Also check for possible PHP or Mysql or and checkusing chrome dev tool for potential 404 not find or js issue.

Are you using the latest package, have you made any code modification (customcode)

**Comment by Mactory** [comment]
maybe this is due to the on demand file size calculation which could take some time on such many files?

**Comment by vichanws** [comment]
Most of files are not over 2MB.
But there are 17 files are 100MB to 200 MB.

The calculation would affect the loading time?

**Comment by lenamtl** [comment]
I guess we should find a tool to test the performance for big files, lots of users and lots of file, we will need to check DB query too.

**Comment by lenamtl** [comment]
I think performance will be better  if we save the file mime and size in db

**Comment by lenamtl** [comment]
Anyone have a solution for this even if it's a hack

thanks

**Comment by lenamtl** [comment]
check here for a way to disable file size calculation.
#221

**Comment by lenamtl** [comment]
Latest release have real pagination on almost each page you can try it.

**Comment by ignacionelson** [comment]
This was fixed a while ago
