### ISSUE TITLE
Question: How to upload Files to Google Drive / Google Cloud

### ISSUE THREAD

**Issue by printing88** [projectsend/projectsend#941]
i really like using ProjectSend my problem is my Local Storage is running low, is it possible to upload files into google drive or google cloud service ??
Many thanks..

**Comment by printing88** [comment]
Is it possible to use Google Drive API https://developers.google.com/drive/api/v3/quickstart/php , to upload my files directly to google drive, I'm really running low on storage

**Comment by xzenor** [comment]
Try mounting your google drive as a virtual filesystem to your uploads folder.

https://ubunlog.com/en/mount-google-drive-locally/

It won't make things any faster though.. remember that you're gonna be sending and receiving the file at the same time when someone transfers a file. If you're low on bandwidth then this might not work for you.
I also don't know if ProjectSend may have an issue with this. I did not try this myself it just seems the most logic solution for your problem and worth a try.
