### ISSUE TITLE
Language choice not possible after update to PHP 8.0

### ISSUE THREAD

**Issue by ch1138** [projectsend/projectsend#943]
Yesterday, I updated PHP from 7.4 to 8.0.

Projectsend worked. There is a language issue, though.

I use the German translation. After updating the server to PHP 8.0, Projectsend displayed everything in English. German still is available in the pulldown menu, but choosing German does not change anything. Projectsend still will be in English (including emails sent by PS).

**Comment by krzysztofjeziorny** [comment]
I can confirm.
r1335, German translations work with PHP 7.4. Changing the PHP version to 8.1 leaves the language choice, but it has no effect and the strings are left in English.

**Comment by krzysztofjeziorny** [comment]
It may be another issue, but as the translations for German are complete, the first part of the Dashboard visible (the colourful blocks) is left untranslated.

<img width="1061" alt="Screenshot 2022-02-08 at 09 44 27" src="https://user-images.githubusercontent.com/872730/152950858-07cbc6de-25d6-42ca-be60-3447c232f8d6.png">

**Comment by ignacionelson** [comment]
Hi!
For php 8 you need to apply this change
https://github.com/projectsend/projectsend/commit/a3c8e66b0ba6e57ebe59e6202f7e9b8e18d6feb2
The next release will have this solved.

Regarding the counters, I've just applied a fix for that, thanks!
