### ISSUE TITLE
Issue with sharing of files. (Probably me :) )

### ISSUE THREAD

**Issue by paul-duxbury** [projectsend/projectsend#944]
not sure if this is me but is the following possible?

lets say you create 2 new clients and make them a member of a group just for those 2. when either of them login i want any file that is uploaded by either user to go in the group so that when the other logs in they see the file. Is this possible?

Basically a true file share between us and the client.

Thanks in advance.

Paul

**Comment by ignacionelson** [comment]
This would require some customization. Sorry. Groups are mostly internal, except public ones. 
Clients could be allowed to upload to any public groups they are part of, but this would mean that anyone could request access to those groups.
I'm currently working on adding folders which would solve this issue in a more elegant and classic way.
