### ISSUE TITLE
The upload file type extension case sensitive issue

### ISSUE THREAD

**Issue by jasimp** [projectsend/projectsend#946]
Please make the upload file type extension is non case sensitive
for eg: .if we set the file type to .jpg, we cannot upload file with extension .JPG also unable to add same extension with upper character if the lower character is already there and vice versa

thank you

**Comment by protego-it** [comment]
Yes, this is really unfortunate. Especially because if I put the uppercase file extension (TIF, JPG) in Options --> Security, it just merges back to lower case. 
![image](https://user-images.githubusercontent.com/59828196/120291268-6abb4080-c2c3-11eb-8229-f44b0b469783.png)

**Comment by ignacionelson** [comment]
This has been fixed for a while, sorry
