### ISSUE TITLE
Uploads bigger than 150mb gets stuck at random %

### ISSUE THREAD

**Issue by kreimerka** [projectsend/projectsend#948]
Hi, I installed projectsend on my goddaddy unlimited hosting. Everything works just fine, I can actually upload small files with no problems. Whenever I try to upload bigger files such as 150mb documents, it'll get stuck at 28%  and won't upload at all. I tried from different computers, different files, internet connections, reinstalled projectsend with new database and the behaviour is the same. Thank you very much!!

**Comment by ignacionelson** [comment]
Hi @kreimerka 
Have you checked the browser's console? There are 2 places where some useful information may be found
1- The console itself might show a JS error
2- The network tab can show you all ajax requests. As soon as one fails, you may get a php error as a response.  If not, try enabling the debug mode and see if something appears there.
Let me know if that helps!

**Comment by kreimerka** [comment]
Hi @ignacionelson 
Thank you for your quick response. These are the errors I'm getting.
Thank you again for your time!!

![Captura](https://user-images.githubusercontent.com/85133486/120251791-3fdfd680-c248-11eb-908e-1a83cfb0a27a.JPG)
![Captura2](https://user-images.githubusercontent.com/85133486/120251792-40786d00-c248-11eb-9cb3-36f4a08a6235.JPG)
![Captura3](https://user-images.githubusercontent.com/85133486/120251793-40786d00-c248-11eb-9817-a09b0b01a432.JPG)
![Captura4](https://user-images.githubusercontent.com/85133486/120251795-40786d00-c248-11eb-9abe-f0e2cd8672f3.JPG)

**Comment by ignacionelson** [comment]
Oh I see! Please click this one
![image](https://user-images.githubusercontent.com/6926562/120258764-066b9300-c269-11eb-88a4-ab31dee504e8.png)
to see the response and check if any error is there

**Comment by kreimerka** [comment]
Thank you! this is what the console shows. In the response tab I get a "failed to load response data".
![Captura](https://user-images.githubusercontent.com/85133486/120261938-8b04e400-c25e-11eb-928f-8a25dc8911a7.JPG)
![Captura2](https://user-images.githubusercontent.com/85133486/120262243-0ebed080-c25f-11eb-8aef-480b100f3119.JPG)

**Comment by ignacionelson** [comment]
I see that also the keep alive request is failing. So the server seems to be rejecting all xhr requests at that point.
The next step would be to check php's error log (if it's empty, enable debug mode in PS, and error reporting on php).

**Comment by kreimerka** [comment]
Hi! I'm not really a pro in this topics, I've been trying to locate the php error log with no luck. Could you please illustrate me on how to find it? Thank you very much in advance.

**Comment by ignacionelson** [comment]
@kreimerka that would depend on your server configuration. It would be better to ask your server provider, they might even have it in their documentation. Sorry for the late response!

**Comment by kreimerka** [comment]
Hi @ignacionelson I already spoke with my server provider and they told me that in my current hosting plan I have a post limit in php of 128M and that I should upgrade to a dedicated server in order to make it work with bigger uploads. Thank you for your time!!
