### ISSUE TITLE
Increase the number of showed items in the lists

### ISSUE THREAD

**Issue by PC-COLLEGE-Training** [projectsend/projectsend#953]
Hello Ignacio,

Is it possible to increase the number of showed items in the lists (e.g. "Manage system users") to more than 10 items?
It would help to get shown a large list of the available items in all categories.

Greetings
Iman

**Comment by ignacionelson** [comment]
Hi! Yes, you can change this in the general options page under the name "Pagination results per page". Hope that helps!

**Comment by PC-COLLEGE-Training** [comment]
Thanks a lot :)
