### ISSUE TITLE
Sorting files by title in client view @r1295

### ISSUE THREAD

**Issue by suhajda3** [projectsend/projectsend#970]
Seams to be broken again with r1295.

By supplying the arguments (?orderby=filename&order=asc) to the URL it works but clicking on Title or the Comment nothing happens.

_Originally posted by @ignacionelson in https://github.com/projectsend/projectsend/issues/465#issuecomment-327205294_

**Comment by alexschomb** [comment]
I just noticed that as well. The main reason for this is that the sorting hyperlinks in the `thead` don't include the `/my_files/` part in the link. As a result the user gets redirected to the wrong page when clicking the sorting links.
