### ISSUE TITLE
Footer image not loading 

### ISSUE THREAD

**Issue by moscowchill** [projectsend/projectsend#976]
![psend](https://user-images.githubusercontent.com/72578879/127575624-2ae1bc0d-9c8c-4294-8d7e-c87145b35f39.JPG)

Hi friends,
I'm not sure whats causing this double // in the URL. I do not seem to have this problem anywhere else..
Any idea on where to fix this? Source code maybe?

**Comment by ignacionelson** [comment]
Hi @sh0reline!
Do you see this // on any other asset? css, js, another image, etc?

**Comment by moscowchill** [comment]
Hi bro, thanks for the great project.

I don't think any other resources have this problem :(
Will confirm tommorow.

**Comment by moscowchill** [comment]
I tested most things and made sure everything working before testing email functions.

**Comment by moscowchill** [comment]
Any idea on how I can fix this?

**Comment by moscowchill** [comment]
Somehow worked fine when I tried it just now....
