### ISSUE TITLE
approve users page isn't fully accessible while need to approve them. 

### ISSUE THREAD

**Issue by hmdqr** [projectsend/projectsend#997]
Hi there, I am a blind user for this awesome project, and i have an issue while trying to approve a new users. 
I don't know how to click approve, could you please mmodify the script and make this box called "Selected clients actions:"
Beacuse this page isn't really accessible with my NVDA screen reader
I just have: 
"Apply selection", and "Delete requests"
first one will denied the user, is this an issue, or could you please add an action call approve user, or denied selected users?
Sorry cause i don't know how to explane it clearly. 
Any replies will be welcome. 
Thanks!

**Comment by eletromotiva** [comment]
Hey this is very easy, try this:

![step one](https://user-images.githubusercontent.com/81834105/133334628-70d5396d-453c-4a2b-b917-90d05b516ca5.png)
![step 2](https://user-images.githubusercontent.com/81834105/133334637-9df097b1-1303-488b-a334-c3a8d7554c59.png)
![step 3](https://user-images.githubusercontent.com/81834105/133334646-12c0f53f-7c05-4dcb-a877-88e4e367f52a.png)

**Comment by hmdqr** [comment]
hi @eletromotiva , that's correct, i do these steps and it's working, but the issue that i can click accept or Deny, the issue is my screen reader can't click this button , but the  selected clients actions box is working without any issues. 
Here, we just need to fix the accept or Deny button to works people have with anyone have a disability. 
The better way to use radio buttons, that will be so helpful. 
Thanks for your reply.

**Comment by eletromotiva** [comment]
@hamadqr Please close this problem.
